### ISSUE TITLE
[Feature]: Allow space keydowns in an `Editable` without submitting

### ISSUE THREAD

**Issue by ricketyBridges** [radix-vue/radix-vue#1008]
### Describe the feature

https://github.com/radix-vue/radix-vue/blob/52100dff9c33d552efc7db0181707e2d2ad6be6a/packages/radix-vue/src/Editable/EditableInput.vue#L47

Spacebar currently submits when submitMode is `enter`. Enforcing strict usage of shift-space is difficult in terms of user education, so exposing a prop to disable this or modifying to something like below would be appreciated.

``` js
if ((context.submitMode.value === 'enter' && event.key === kbd.ENTER) || (context.submitMode.value === 'both' && (event.key === kbd.SPACE || event.key === kbd.ENTER) && !event.shiftKey)) 
```

Willing to submit a PR if it's an acceptable change.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by epr3** [comment]
@ricketyBridges The spacebar submit implementation was me being a bit overzealous on that feature. Feel free to remove the key altogether from that conditional in L47.
