### ISSUE TITLE
[Bug]: `Dialog`: disableOutsidePointerEvents has no effect when `forceMount` is true

### ISSUE THREAD

**Issue by alexbassy** [radix-vue/radix-vue#1010]
### Environment

```bash
Developement/Production OS: macOS 14.5
Node version: 20.11.1
Package manager: npm 10.2.4
Radix Vue version: 1.8.4
Vue version: 3.4.3
CSS framework: scss
Client OS: macOS 14.5
Browser: Chrome 125.0.6422.142
```

### Link to minimal reproduction

https://stackblitz.com/edit/tdkd3r-c72xz8?file=src%2FApp.vue

### Steps to reproduce

- Add `forceMount` and `:disableOutsidePointerEvents="false"` props to `DialogContent`
- Try to click the button to open the dialog
- The dialog cannot be opened because body has `pointer-events: none`

### Describe the bug

When the aforementioned props are combined, the pointer events on body get disabled. This prevents clicking on the body to open the dialog. 

### Expected behavior

My use case: I want to move content from the page to a dialog for a "full screen mode" effect (while preserving the state of the UI)
- To do this, I use portals: one target in the content that Vue renders the component to normally, and another portal target inside the DialogContent
- For the portal mounting to work correctly, the portal targets must both be present in the DOM

This approach works with the `forceMount` and styling the closed dialog with `display: none`. However, `disableOutsidePointerEvents` is needed to prevent the body from being unclickable, which doesn't work when combined with `forceMount`.

### Context & Screenshots (if applicable)

This screenshot suggests that the prop is passed to DialogContent correctly but not to its children 

<img width="307" alt="image" src="https://github.com/radix-vue/radix-vue/assets/1243909/5acf4846-f318-4dcb-b206-09614e70f822">

**Comment by zernonia** [comment]
Hey @alexbassy .. try setting `DialogRoot` with `:modal="false"`. 

`disableOutsidePointerEvents` should be an internal prop because it ties closely with the modality of the dialog.

**Comment by zernonia** [comment]
Closing this as stale. If the issue still persist do let me know ya 😁
