### ISSUE TITLE
[Bug]: `Editable` is automatically triggered in `Popover`

### ISSUE THREAD

**Issue by ricketyBridges** [radix-vue/radix-vue#1016]
### Environment

```bash
Development/Production OS: Windows 10 19043.1110
Radix Vue version: 1.8.4
Vue version: 3.4+
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/izdn5j-zebu3y?file=package.json

### Steps to reproduce

Click the Popover trigger.

### Describe the bug

Editables nested in Popovers are set to editing mode when the parent Popover is opened. This only occurs when activateMode is focus (the default), so a focus event is potentially being caught from the Popover?

**Comment by epr3** [comment]
Hello @ricketyBridges,

The `Popover` auto focuses the first element in its content by default, therefore it interacts with the `Editable` component if it is the first focusable element inside the `PopoverContent`.

You can circumvent this behaviour by overriding the `openAutoFocus` event on `PopoverContent` like so: `@openAutoFocus="(e) => e.preventDefault()"`

**Comment by ricketyBridges** [comment]
Gotcha, thank you!
