### ISSUE TITLE
[Bug]: Combobox breaks down when there are more than 100 options

### ISSUE THREAD

**Issue by cyyynthia** [radix-vue/radix-vue#1040]
### Environment

```bash
Developement/Production OS: Arch Linux x86_64 6.9.2-arch1-1
Node version: 22.1.0
Package manager: yarn@1.22.22
Radix Vue version: 1.8.4+
Vue version: 3.4.30
Nuxt version: N/A
Nuxt mode: N/A
Nuxt target: N/A
CSS framework: None
Client OS: Arch Linux x86_64 6.9.2-arch1-1
Browser: Chromium Version 125.0.6422.112 (Official Build)
```

### Link to minimal reproduction

https://stackblitz.com/edit/cbpual?file=src%2FApp.vue

### Steps to reproduce

- Create a combobox with 100+ options
- Open the combobox
- Pick an option

### Describe the bug

A warning is show in console, and selecting the option does not make the value show as selected.

### Expected behavior

No warning to be logged, and the selector to work.

### Context & Screenshots (if applicable)

This issue existed before and was fixed (#551), but it appears there is a regression in 1.8.4 (works just fine in 1.8.3) causing the issue to occur again.

**Comment by zernonia** [comment]
Thanks for reporting the issue. Combobox will be refactored in v2, that would eliminate this issue and improve the performance 😁

**Comment by cyyynthia** [comment]
Noting today's discoveries here: to have the ability to restrict the height in a similar fashion to Select in our component lib we now are using ComboboxPortal + position="popper" align="start"; and that seems to fix the issue as we no longer see any warning show up in 1.8.4+

That can be considered a workaround for those who want to update to get latest bugfixes and the upcoming components in 1.9 😄
