### ISSUE TITLE
[Bug]: `Primitive` Hydration node mismatch

### ISSUE THREAD

**Issue by blasdfaa** [radix-vue/radix-vue#1083]
### Environment

```bash
Developement/Production OS: macOS Sonoma 14.5
Node version: 8.20.3
Package manager: npm@10.2.3
Radix Vue version: 1.8.5
Vue version: 3.4.31
Nuxt version: 3.12.2
Nuxt mode: universal
Nuxt target: server
CSS framework: unocss@0.61.0
Client OS: macOS Sonoma 14.5
Browser: Chrome 126.0.6478.116
```

### Link to minimal reproduction

https://stackblitz.com/edit/radix-primitive-hydration-issue?file=app.vue

### Steps to reproduce

Open the browser console and refresh the page

### Describe the bug

When using the `Primitive` component and when set `as="textarea"` I am getting a Hydration node mismatch warning

**Comment by abh1nash** [comment]
I had this issue as well. I think this is more a Vue/Nuxt issue, because they insert ` <!--[--><!--]-->` in the server as a child of `textarea` for some reason.

My workaround was to use `as-child` of `Primitive`. In your case, you could do the following:

```vue
        <InputBase as="template"
        as-child placeholder="textarea tag" >
             <textarea></textarea>
        </InputBase>
```

**Comment by zernonia** [comment]
Close as it's issue with Nuxt/Vue rendering textarea's `<slot>`. Either remove `<slot>` in Primitive component if it is a textarea, or just remove the `<slot>` entirely
