### ISSUE TITLE
[Feature]: AIChat

### ISSUE THREAD

**Issue by aquarius-wing** [radix-vue/radix-vue#1094]
### Describe the feature

I intend to develop a component for AI chat situations.

I have developed an basic version in https://github.com/aquarius-wing/radix-vue/tree/feat-ai-chat.

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hey @aquarius-wing .. Can you share more about this component? By first impression this is something custom and relatively straightforward, and it doesn't help dev solves the accessibility concern.

**Comment by zernonia** [comment]
Thanks for the suggestion @aquarius-wing .. However this component doesn't really fit in the project.. Thus will be closing this.
