### ISSUE TITLE
[Feature]: Method to Scroll to Top in a ScrollArea ScrowAreaViewport

### ISSUE THREAD

**Issue by scottagt** [radix-vue/radix-vue#1095]
### Describe the feature

I needed a way to scroll up to the top of a ScrollArea in the process of implementing an Infinite Scroll functionality and I created and exposed a function from ScrollArea that lets a parent component scroll it to ScrollArea's top.

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks @sadeghbarati  for transferring this. Yeah I believe this can be relatively straight forward to be implemented 😁

**Comment by scottagt** [comment]
This is great. Do I need to attach the code I wrote or make a PR request? Or is someone else going to basically implement it in a new way? Whatever works for me. I could attach the modified Vue component file here and an example that uses it and the scroll to top functionality if that's helpful to anyone.

**Comment by y4my4my4m** [comment]
What I ended up doing:
```vue
<ScrollArea ref="logsContainer">...</ScrollArea>
```
```typescript
const logsContainer = ref()

const scrollToBottom = () => {
  nextTick(() => {
    if (logsContainer.value) {
      const viewport = logsContainer.value.$el.querySelector('[data-radix-scroll-area-viewport]')
      if (viewport) {
        viewport.scrollTo({
          top: viewport.scrollHeight,
          behavior: 'smooth'
        })
      }
    }
  })
}
```

Not a good approach but it worked.
