### ISSUE TITLE
[Feature]: Property to pass in a scroll event handler to ScrollArea --> ScrollAreaViewport

### ISSUE THREAD

**Issue by scottagt** [radix-vue/radix-vue#1096]
### Describe the feature

I needed a way to detect if a ScrollArea was at the bottom of it's scroll view port in the process of implementing an Infinite Scroll functionality. I added a new property to ScrollArea that allows a parent component to pass a event handler function. ScrollArea passes this function from it's props to ScrollAreaViewport.

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Yoo @scottagt ! We are exposing `viewport` element in https://github.com/radix-vue/radix-vue/pull/1120

and you can use [`useScroll`](https://vueuse.org/core/useScroll/#usescroll) to obtain the scroll position and different state. 
From there you can check if it arrived to the bottom. 

```vue
const { x, y, arrivedState } = useScroll(() => scrollAreaRef.value?.viewport)
```

Furthermore, you can easily use [`useInfiniteScroll`](https://vueuse.org/core/useInfiniteScroll/#useinfinitescroll) as well. 

With that said I believe we don't need to expose additional event as this is something better to be handle by user, WDYT? 😁

**Comment by scottagt** [comment]
Hi @zernonia , this is great, thank ya'll very much (and also for the ref to vueuse useInfiniteScroll :) ) !

**Comment by zernonia** [comment]
Glad to hear that! No problem ya! 💚
