### ISSUE TITLE
[Bug]: Hover card Tooltip does not disappear when hover another hover card

### ISSUE THREAD

**Issue by Psycarlo** [radix-vue/radix-vue#1103]
### Environment

```bash
Package manager: pnpm@9.3.0
Radix Vue version: 1.9.0
Vue version: 3.4.30
CSS framework: tailwindcss@3.4.4
Browser: Chrome & Firefox
```

### Link to minimal reproduction

https://psyui.com/docs/visualizations/tracker

### Steps to reproduce

1. Open the reproduction link
2. Hover on a tracker hover card trigger
3. Hover another tracker card trigger

Note: Happens only sometimes - hover the first one and slowly drag the cursor to the next

### Describe the bug

Two hover cards side by side can trigger both when hovering only one.

### Expected behavior

Only show hover card content when hovering that specific hover card.

### Context & Screenshots (if applicable)

![](https://i.imgur.com/v1nUv1p.png)

Code: https://github.com/Psycarlo/psyui/blob/main/apps/www/src/lib/registry/ui/Tracker.vue

**Comment by zernonia** [comment]
Thanks for the issue @Psycarlo ! Might be related to https://github.com/radix-vue/radix-vue/issues/850 as both were using the same composables.

**Comment by Psycarlo** [comment]
@zernonia yes. Both are using `useGraceArea` and the default padding on `getPaddedExitPoints` is **5**.
Maybe we could add a prop to set padding to 0 or even remove the grace area? 🤔

**Comment by zernonia** [comment]
Beautiful site and exciting project right there @Psycarlo !! 🤩
