### ISSUE TITLE
[Feature]: Allow bringing your own date library.

### ISSUE THREAD

**Issue by genu** [radix-vue/radix-vue#1104]
### Describe the feature

Coming from momentjs and dayjs I find it extremely difficult to work with `@internationalized/date`. Not only is there very sporadic and confusing documentation, I find it that it becomes extremely verbose to do simple things, like date formatting.

In `dayjs` for example, I can do: ` dayjs(new Date()).format('MMMM D, YYYY')` with `@internationalized/date` it seems I need to do some conversion gymnatistics:

```ts
  <!-- output the month in short format. e.g.: Jan, Feb, etc. -->
    {{ formatter.custom(value.toDate(getLocalTimeZone()), {
      month: 'short',
    }) }}
 ```
 
 and even this just gives me only the month.
 
Maybe its because `@internationalized/date` is new, or maybe I'm new to it, but it seems very difficult to work with it. 

I don't know if its just me, but I'd like a date library that removes the complexity of dates and doesn't drag me into the complexity. `dayjs` and `momentjs` are popular because they do that well, and I can focus on building the app.

My recommendation
- Keep `@internationalized/date` internally, but allow working with regular `Date` objects outside
- OR Provide proper helpers that eliminate the need to "study up" on the `@internationalized/date` API. Helpers that allow simple date formatting (`format('MMMM D, YYYY')`, for example) and quick conversions
- OR provide a way to use my own date library so that its used throughout.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
You can use `toDate` function like

```ts
import { toDate } from 'radix-vue/date'
```

to transform `@internationalized/date` **DateValue** to normal **Date** object, 
then you can use your own date library to format the the date

**Comment by genu** [comment]
Thanks for the quick summery.

> ```ts
> const todayDateValue = ref(today(getLocalTimeZone())) as Ref<DateValue> // DateValue
> const calendarDateValue = ref(new CalendarDate(2023, 0, 20)) as Ref<DateValue> // DateValue
> ```

why is the casting necessary here and not inferred automatically?

**Comment by cyyynthia** [comment]
Yes. DateValue is a wider type that includes CalendarDate, ZonedDateTime, etc.. Casting is required because a CalendarDate is too specific to use in components, which use DateValue (TS complains because the component can't write a ZonedDateTime which it claims is able to do).

A safer way to express this is to do ref<DateValue>(...) which will widen the type while keeping all the assertions where needed

**Comment by genu** [comment]
I'm not sure if I'm not using it right, but in my testing, `toDate()` doesn't really work as expcted:

when I give it a `DateValue` there are type errors:

```shell
Argument of type 'import("/node_modules/@internationalized/date/dist/types").DateValue' is not assignable to parameter of 
            type 'import("/node_modules/radix-vue/node_modules/@internationalized/date/dist/types").DateValue'.
ts-plugin(2345)
```
