### ISSUE TITLE
[Feature]: Add ability to create circular progress bar

### ISSUE THREAD

**Issue by genu** [radix-vue/radix-vue#1110]
### Describe the feature

Something similar to the circular progress bar as illustrated here:  https://element-plus.org/en-US/component/progress.html#progress

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the suggestion @genu .. I believe the circular progress bar is up to user to craft and not a primitive.. 
I can add a demo example for this 😁
