### ISSUE TITLE
[Bug]: Date Picker (and possibly all related components) are not handling `disabled`

### ISSUE THREAD

**Issue by cyyynthia** [radix-vue/radix-vue#1129]
### Environment

```bash
Developement/Production OS: Arch Linux 6.9.9-arch1-1
Node version: 22.1.0
Package manager: pnpm@9.4.0
Radix Vue version: 1.8.3-1.9.1
Vue version: 3.4.31
Nuxt version: N/A
Nuxt mode: N/A
Nuxt target: N/A
CSS framework: N/A
Client OS: Arch Linux 6.9.9-arch1-1
Browser: Chromium 126.0.6478.126
```

### Link to minimal reproduction

https://stackblitz.com/edit/tp7vv9

### Steps to reproduce

First problem
- Try clicking on the picker trigger

Second problem
- Press Tab

### Describe the bug

The picker can still be opened despite the field being disabled, which I don't think is the intended behavior. Additionally, the field is still focusable.

### Expected behavior

The button to not open the calendar, and the field not to be focusable

**Comment by zernonia** [comment]
Thanks for the issue @cyyynthia ! That make sense! The field shouldn't be focusable and the button shouldn't trigger the calendar. 😁
