### ISSUE TITLE
[Feature]: allow custom children list in `<TreeRoot />`

### ISSUE THREAD

**Issue by Destiner** [radix-vue/radix-vue#1139]
### Describe the feature

Currently, `Tree` component requires you to provide data in a certain format. Specifically, it requires you to specify children as a `children`.

Take the file system schema as an example:

```ts
interface File {
  name: string;
  type: FileType;
}

interface Directory {
  name: string;
  files: File[];
  directories: Directory[];
}
```

I can convert `files` and `directories` into `children` on my end, but I will lose some of the type-safety. Also, converting recursive data structures is not convenient or error-prone.

As a solution, consider adding a `getChildren` prop to the `<Tree.Root />` similar to a `getKey` prop.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Make sense @Destiner ! I PR is welcome!! 🤩 
Let me know if you run into any difficulties ya 😁
