### ISSUE TITLE
bug: popover wont close after clicking inside popper

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#114]
**Describe the bug**
Poppover wont close when clicked outside after clicking inside popper

**To Reproduce**
1. Open the popover from the demo
2. Click inside the opened popper
3. Click outside, it wont close

**Expected behavior**
Popover should behave as usual and closed when clicked outside

**Comment by zernonia** [comment]
The refactoring the popper would fix this issue 😁
