### ISSUE TITLE
[Bug]: The link for `Motion One` leads to a 404 page

### ISSUE THREAD

**Issue by hotdogc1017** [radix-vue/radix-vue#1160]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/guides/animation.html#animating-with-vue-transition

### Steps to reproduce

.

### Describe the bug

The `Animation/Transition` section of the guide mentions a Web Animations API animation library: `Motion One` in the [Animating with Vue Transition](https://www.radix-vue.com/guides/animation.html#animating-with-vue-transition) section. I am very interested, but when I click the link to jump, I find a 404 page :disappointed_relieved: .

The correct url is:
```
https://motion.dev/vue/docs/quick-start
```
I am happy to provide a PR for this :grinning:

**Comment by hotdogc1017** [comment]
At the same time, the author has announced that the integration support for `Vue` has been abandoned, and I did not find any section related to `Vue` in the `Motion One` documentation.

Related discussion:

```
https://github.com/motiondivision/motionone/discussions/241
```

**Comment by zernonia** [comment]
We will not be porting MotionOne's to another Vue project for now. Perhaps we can hide the note for now? 😁

**Comment by hotdogc1017** [comment]
I think it's fine, by the way, Radix Vue is really great! 🚀
