### ISSUE TITLE
[Feature]: ScrollArea: Content with ellipsis CSS bursts out of container.

### ISSUE THREAD

**Issue by Lol1chw** [radix-vue/radix-vue#1163]
### Describe the feature

Recently encountered the same issue in radix-vue. I could create a PR with a solution to this issue use the suggestion https://github.com/radix-ui/primitives/issues/926#issuecomment-2203592086
Reference - https://github.com/radix-ui/primitives/issues/926
Reference pr - https://github.com/radix-ui/primitives/pull/2945

Example before fix:
![image](https://github.com/user-attachments/assets/f5455e37-9537-4c8e-a241-1657f86fd80b)

Example after fix: 
![image](https://github.com/user-attachments/assets/4af8903b-e131-4967-bb5a-75e3de43e30a)

### Additional information

- [X] I intend to submit a PR for this feature.
- [X] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Appreciate the issue and PR @Lol1chw !! 🙏🏻
