### ISSUE TITLE
[Bug]: Tabs Hydration attribute mismatch

### ISSUE THREAD

**Issue by brokuka** [radix-vue/radix-vue#1172]
### Environment

```bash
- Operating System: Linux && Windows
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, shadcn-nuxt@0.10.4
- Build Modules:    -
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-gvthbq?file=package.json,app.vue

### Steps to reproduce

Run stackblitz container and open dev console

### Describe the bug

Hydration attribute mismatch using tabs component (maybe not only tabs)

**Comment by zernonia** [comment]
@brokuka  please do the solution here https://github.com/radix-vue/radix-vue/issues/577#issuecomment-1980983686
