### ISSUE TITLE
[Feature]: prevent default when using esc on Dialog/AlertDialog

### ISSUE THREAD

**Issue by Ericlm** [radix-vue/radix-vue#1173]
### Describe the feature

The [Dialog of headlessUI](https://headlessui.com/v1/vue/dialog) prevents the esc key from the default behavior which is to move a fullscreen window to the desktop (on macOS). It would be great if the same behavior was applied to Radix for AlertDialog and Dialog.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by Ericlm** [comment]
I think it should be at the `DismissableLayer` level so that all components that can be dismissed with escape key would prevent default. 
Something like:
```ts
onKeyStroke('Escape', (event) => {
  const isHighestLayer = index.value === layers.value.size - 1
  if (!isHighestLayer)
    return

  emits('escapeKeyDown', event) // Sending the event untouched

  event.preventDefault() // Preventing default every time
  emits('dismiss') // Finally, dismissing the component
})
```
Maybe that preventing by default is "dangerous", but I don't see a case where not preventing it would be important 🤔

**Comment by zernonia** [comment]
This is already a supported feature. You can prevent `escapeKeyDown` on [DialogContent](https://www.radix-vue.com/components/dialog.html#content).

eg: `<DialogContent @escapeKeyDown.prevfent>`

**Comment by zernonia** [comment]
This is already a supported feature. You can prevent `escapeKeyDown` on [DialogContent](https://www.radix-vue.com/components/dialog.html#content).

eg: `<DialogContent @escapeKeyDown.prevfent>`

We prefer not to prevent default by default, as to allow user to control this behavior
