### ISSUE TITLE
Discord link on readme invalid

### ISSUE THREAD

**Issue by ThimoDEV** [radix-vue/radix-vue#119]
**Describe the bug**
The Discord link is not valid anymore

**To Reproduce**
-

**Expected behavior**
Valid invitation to the Discord server

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khairulhaaziq** [comment]
[fixed](https://github.com/radix-vue/radix-vue/commit/e5632c5b0859b3f66b41dd83608a22c3d1e8deba)

**Comment by santuan** [comment]
Hello! It seems that this link is currently not working.
https://discord.com/invite/jZUsrAADe5

I would love to join the channel.
Thanks  :)

**Comment by zernonia** [comment]
@santuan  Try this!

https://chat.radix-vue.com/

**Comment by santuan** [comment]
Needed to change the browser (brave showed link as invalid)
I managed to join, thanks again!
