### ISSUE TITLE
[Feature]: Year Selection in Date Picker

### ISSUE THREAD

**Issue by ElvinKyungu** [radix-vue/radix-vue#1199]
### Describe the feature

I would like to request an enhancement for the date picker component to allow users to click on the year and display a list of multiple years from which they can choose.

**Current Behavior**
Currently, the date picker allows users to navigate through months and select specific dates. However, there is no direct way to quickly navigate through years, which can be cumbersome for users who need to select dates far in the past or future.

**Proposed Behavior**
When a user clicks on the year in the date picker header, a dropdown or modal should appear, displaying a list of years. Users should be able to scroll through this list and select the desired year. This will enhance the user experience by making it easier to navigate to specific years without having to click through each month.

**Additional Details**
The year selection list should support both scrolling and direct input.
The list should cover a configurable range of years (e.g., 1900-2100).
Ensure the selected year updates the date picker's view accordingly.
Maintain the current style and theme of the date picker to ensure a consistent user interface.
Mockup/Screenshot
Here is a basic mockup of the proposed feature:

**Benefits**
Improved usability and user experience.
Faster date selection, especially for dates far in the past or future.
Enhanced functionality aligns with modern date picker components.
Potential Challenges
Ensuring compatibility with existing date picker functionality.
Managing the dropdown/modal interface across various devices and screen sizes.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Duplicated https://github.com/radix-vue/radix-vue/issues/741
