### ISSUE TITLE
[Feature]: Expose internal types for combox filter function

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#1203]
### Describe the feature

I want to move the filterFunction on `ComboboxRoot` to the script part of my component, but as I use typescript I need to type the arguments by myself and here's how it looks now:

```ts
type AcceptableValue = string | number | boolean | Record<string, any>;
type ArrayOrWrapped<T> = T extends any[] ? T : Array<T>;

function filterFunction(
    values: ArrayOrWrapped<AcceptableValue>,
    term: string,
): ArrayOrWrapped<AcceptableValue> {
    // ...
}
``` 

Would be much nicer if radix-vue had exported `AcceptableValue` and `ArrayOrWrapped` types.

```ts
import type { AcceptableValue, ArrayOrWrapped } from "radix-vue"

function filterFunction(
    values: ArrayOrWrapped<AcceptableValue>,
    term: string,
): ArrayOrWrapped<AcceptableValue> {
    // ...
}
``` 

Or make a type for the filter function and export it

```ts
export type ComboboxFilterFunction = (values: ArrayOrWrapped<AcceptableValue>, term: string) => ArrayOrWrapped<AcceptableValue>;

const filterFunction: ComboboxFilterFunction = (values, term) => {
    // ...
}
```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
In `v2` we will be removing this prop. However this addition to current v1 should be good for typing

**Comment by zernonia** [comment]
@MellKam  I realized we can do so right? 

```ts
type TFilterFunction  = ComboboxRootProps['filterFunction']
```

**Comment by MellKam** [comment]
@zernonia Actually yes, it works. Thanks!
