### ISSUE TITLE
[Feature]: How to render Dialog using v-if

### ISSUE THREAD

**Issue by JarvisH** [radix-vue/radix-vue#1206]
### Describe the feature

Hallo.

This may be a question of best practices and a new feature is perhaps not needed, but here goes:

When using Dialog components, they are rendered to the DOM using the `open` Property. This works just fine with a few exceptions:

- Any requests or logic executed inside such a modal component may need to be delayed until `open` is true.
- Any state set as refs of form values often needs to be reset when showing the Dialog.

Such manual cleanup could be avoided when using `v-if` to render the Dialog, as it gets remounted when shown:

```vue
// Does not reset state or prevent code execution
<SomeDialogComponent :open="showDialog" />

// Does reset state and prevent code execution
<SomeDialogComponent v-if="showDialog" />
```

`v-if` however does not play well with `<DialogPortal />` and Vue `<Transition />`, essentially breaking animations.

So the question is: could this easily be implemented in Radix? I managed to solve it using a wrapper component and provide/inject, but a built-in solution would be great. Or is the issue caused by bad practices on my part?

FYI my solution where the open state is handled internally via a wrapper component, which can listen to the `afterLeave` event of the Vue transition.

```vue
<DialogRender v-if="show" @after-leave="show=false">
    <SomeDialogComponent />
</DialogRender>
```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Dialogs are already removed from the DOM when it is closed, I think there is no need to use `v-if`

For best practices use `@vueuse/core` [**createReusableTemplate**](https://vueuse.org/core/createReusableTemplate/)

**Comment by zernonia** [comment]
@JarvisH  can you share the code for `SomeDialogComponent` ? Perhaps this would be better for a discussion since most likely it's about the component usage 😁
