### ISSUE TITLE
[Feature]: Allow selecting a single date using `DateRangePicker`

### ISSUE THREAD

**Issue by innocenzi** [radix-vue/radix-vue#1207]
### Describe the feature

There are situations where it's acceptable to have a range of the same day (eg. `[2024-01-01, 2024-01-01]`). I know `DatePicker` also exists, but in my situation I would like to be able to select both normal ranges, or a specific day.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hey @innocenzi ... Radix Vue offers primitives designed for different case, in your case you should be able to have a wrapper component that would received `v-model` as a `DateValue` or `DateValue[]`, and you render `DatePicker` or `DateRangePicker` respectively.

**Comment by innocenzi** [comment]
Thanks for the suggestion @zernonia. That wouldn't work in my case I think, since users can select either a single day or a range of days in every situation, not specific ones that I could determine with a condition. :(
