### ISSUE TITLE
[Bug]: use `aria-hidden="true"`, not `aria-hidden=""`

### ISSUE THREAD

**Issue by stefanprobst** [radix-vue/radix-vue#1210]
### Environment

```bash
Developement/Production OS: linux
Node version: 20.16.0
Package manager: pnpm@9.7.0
Radix Vue version: 1.9.3
Vue version: 3.4.37
Nuxt version: 3.12.4
CSS framework: tailwindcss@3.4.9
Client OS: linux
Browser: firefox
```

### Link to minimal reproduction

https://github.com/stefanprobst/issue-shadcn-vue-checkbox

### Steps to reproduce

- clone [repo](https://github.com/stefanprobst/issue-shadcn-vue-checkbox), `pnpm install`, `pnpm run dev`
- inspect checkbox in accessibility devtools

### Describe the bug

`aria-hidden=""` does not actually hide the element. when inspecting the `<input type="checkbox">` in devtools, you will see two elements with role=checkbox, the `<button role="checkbox">` and the `<input type="checkbox" aria-hidden="">`:

![Screenshot_20240810_115623](https://github.com/user-attachments/assets/873990f1-b2df-488f-a564-0cc2279b75da)

when setting `aria-hidden="true"` on the input element, you will see:

![Screenshot_20240810_115751](https://github.com/user-attachments/assets/5222b0e7-cecf-4aae-a50e-92f4e75f4d52)

### Context & Screenshots (if applicable)

the repro is for checkbox, but there may be other components affected as well.

**Comment by maxmaxme** [comment]
Hi! After the last update I get this error in the console when I try to use the [Combobox](https://www.radix-vue.com/components/combobox)

> Blocked aria-hidden on a <input> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <input type=​"text" aria-expanded=​"true" aria-controls=​"radix-vue-combobox-content-1" aria-disabled=​"false" aria-autocomplete=​"list" role=​"combobox" autocomplete=​"false" class=​"ComboboxInput" placeholder=​"Placeholder..." value aria-activedescendant=​"radix-vue-combobox-option-4">​

<img width="999" alt="Screenshot 2024-08-14 at 14 48 34" src="https://github.com/user-attachments/assets/7e8e6c3f-541b-44b7-a2bf-17aab08524e0">

**Comment by zernonia** [comment]
Thanks @maxmaxme ! I realized this issue too! Will push a fix soon!
