### ISSUE TITLE
[Bug]: Tooltip appearance issues with touch-devices

### ISSUE THREAD

**Issue by 7iomka** [radix-vue/radix-vue#1223]
### Environment

```bash
Developement/Production OS: MacOS 14.5 / Android 14.0
Node version: 18.20.3
Package manager: pnpm@8.6.0
Radix Vue version: 1.9.4
Vue version: 3.4.37
CSS framework: tailwindcss@3.4.9
Client OS: MacOS 14.5 / Android 14.0
Browser: Chrome latest
```

### Link to minimal reproduction

https://stackblitz.com/edit/mus4ig?file=components%2Ftooltip%2FTooltipContent.vue,layouts%2FLayoutDefault.vue,pages%2Findex%2F%2BPage.vue

### Steps to reproduce

- Open repo-link from chrome devtools (touch enabled) or any touch device
- Click on numbers

### Describe the bug

I see unexpected appearance issues on touch devices.
Tooltip content very quickly appears and hide.
Another strange behavior is that when we leave the page (go to another tab) and come back - the content will be visible!

### Expected behavior

I expected fallback behavior for hover events for touch devices to work exactly the same

### Context & Screenshots (if applicable)

Video with animation appearance classes enabled: 

https://github.com/user-attachments/assets/f2b17952-d431-490e-a87f-6581edfaf73b

Video without animation appearance classes enabled: 

https://github.com/user-attachments/assets/65c4d131-d60d-4654-86e8-69e2dec3811a

**Comment by zernonia** [comment]
Thanks for the issue @7iomka ! Seems like there's some error running the reproduction 😬
Also can't seems to reproduce the issue on touch-devices

**Comment by 7iomka** [comment]
> https://stackblitz.com/edit/mus4ig?file=components%2Ftooltip%2FTooltipContent.vue,layouts%2FLayoutDefault.vue,pages%2Findex%2F%2BPage.vue

Hello.
Fixed repro.

**Comment by zernonia** [comment]
Thanks for the issue @7iomka ! Seems like the tooltip was being render a split second causing the animation to flickers. Happening on https://www.shadcn-vue.com/docs/components/tooltip.html too. Looking into this 😁

**Comment by 7iomka** [comment]
@zernonia Hi.
Issue still present on touch devices.
https://stackblitz.com/edit/mus4ig?file=components%2Ftooltip%2FTooltipContent.vue,layouts%2FLayoutDefault.vue,pages%2Findex%2F%2BPage.vue


I tried different workarounds, like
```
    :delay-duration="200"
    :skip-delay-duration="100"
    disable-closing-trigger
```

but, unfortunately, tooltips opens randomly, one for 3-4 attempts when I click to different triggers.
Why this happens?
I think we need to find real workaround to have normal worked tooltips

**Comment by 7iomka** [comment]
@zernonia Any news on this?
