### ISSUE TITLE
feat: Add Nuxt module for Component autoImport

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#123]
We should have a module that would autoImport all component in `radix-vue`.

**Comment by khairulhaaziq** [comment]
disagree on this, for package absolutely no, we will get lost and will lose our trace of the sources. I think it is okay as is

**Comment by zernonia** [comment]
what do you mean will get lost, and lose our trace of the sources?


this module is meant for Nuxt user, to import all component via the `@nuxtjs/component`, thus no need to import manually.

They can just add the module in `nuxt.config.ts` as such: 
```js
  modules: ['radix-vue/nuxt']
```

**Comment by khairulhaaziq** [comment]
ahh I thought you're gonna add auto-import feature in the package, sorry misunderstood, that's neat then, yeah a nuxt module is really great!

**Comment by khairulhaaziq** [comment]
this might be useful
https://github.com/Hebilicious/nuxt-module-template

**Comment by owlnai** [comment]
I want to implement this! Got the module playground working. My plan is to add a `@radix-vue/nuxt` module and a Nuxt playground alongside the Vue 3 one so we can test both environments

**Comment by zernonia** [comment]
@owlnai  thanks for taking up this! I will add the Nuxt playground as Im tackling this issue (https://github.com/radix-vue/radix-vue/issues/228) currently. You can start with the modules folder first. 

Once the fixes for SSR (in this case Nuxt) is in, then you can update the playground 😁

**Comment by zernonia** [comment]
@owlnai  the above PR has been merged (which included Nuxt3 playground). Feel free to pull the latest `main`, and you should be able to Nuxt modules correctly 😁
