### ISSUE TITLE
[Feature]: Add clear-value functionality to the Select Component

### ISSUE THREAD

**Issue by nunonux** [radix-vue/radix-vue#1237]
### Describe the feature

When using the select component I noted that it lacks the functionality to clear the selected value, then I suggest that it would a good idea the Select Component have this feature..

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hi @nunonux .. you can easily set the `modelValue` to `''` to clear the value right? We do not necessarily need additional component IMO. Similar to native [select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) where there's no clear button

**Comment by nunonux** [comment]
I made a research and you are right, the behavior should be similar to the native select. I've done is put the select inside a context-menu with a clear action.

Thanks for the hard work and for this library.

**Comment by zernonia** [comment]
Glad that you found a solution for this! 💚

**Comment by hasan-ozbey** [comment]
> Hi [@nunonux](https://github.com/nunonux) .. you can easily set the `modelValue` to `''` to clear the value right? We do not necessarily need additional component IMO. Similar to native [select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) where there's no clear button

okay I'm sorry but this is a ridiculous answer. 

Reka UI is supposed to enhance user experience and simplify development. Native elements have UX limitations because they're basic; that's **exactly** why we rely on UI libraries in the first place!
