### ISSUE TITLE
[Feature]: TimeField Component

### ISSUE THREAD

**Issue by nunonux** [radix-vue/radix-vue#1241]
### Describe the feature

The library already have an DateField component and it would be great if there was a TimeField component. There are plans to implement the component or you can already use it?

I think a component like TimeField would make the library more robust.

PS: Thanks for the hard work creating and maintaining this awesome library.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sokhengpory** [comment]
[#900 (comment)](https://github.com/radix-vue/radix-vue/issues/962#issuecomment-2132841492) I'm currently using this approach

**Comment by nunonux** [comment]
Thanks for the help, with some modification I reached for what I wanted.
Strange, I searched the issues to find a solutions and didn't came across of it, maybe I was really tired.
