### ISSUE TITLE
[Bug]: `v-if` text is included in TooltipContent computed aria-label 

### ISSUE THREAD

**Issue by iammola** [radix-vue/radix-vue#1255]
Causing the tooltip role element to have content like
```html
<span id="..." role="tooltip">
  Filename: ... Page:  ... v-if
</span>
```

https://github.com/radix-vue/radix-vue/blob/b3fa7bd2879e4b615e7a2fe4e6a7249884cc545d/packages/radix-vue/src/Tooltip/TooltipContentImpl.vue#L68-L82/

The type property of the VNode should be respected, in this case the `Comment` symbol.

I do appreciate all the work put into this package. It's a beautiful work of art!

**Comment by zernonia** [comment]
Yoo @iammola ! Can you please elaborate on the issue? Perhaps a reproduction? 😁 I'm not really understanding the issue

**Comment by iammola** [comment]
Here you go @zernonia. https://codesandbox.io/p/devbox/fp249j. Thanks!

**Comment by zernonia** [comment]
Thanks for the reproduction @iammola . I understand the issue now 😁
