### ISSUE TITLE
[Feature]: Calling dialog using vue hooks

### ISSUE THREAD

**Issue by han1548772930** [radix-vue/radix-vue#1263]
### Describe the feature

Calling dialog using vue hooks

### Additional information

https://github.com/radix-vue/shadcn-vue/issues/748
Here is a way to do it, but there will be some problems if there is nesting
- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Hi 

https://github.com/webfansplz/vue-c2c

This might be helpful
