### ISSUE TITLE
[Bug]: Radio Group has disappearing focus

### ISSUE THREAD

**Issue by hrubysi** [radix-vue/radix-vue#1264]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/components/radio-group#radiogroup

### Steps to reproduce

1. Click any options of Radio Group
2. Click outside
3. Tab

### Describe the bug

Radio Group can make focus disappear when choice is first selected by mouse and then user uses tab to move around the form.
The focus goes to the wrapper `div[role="radiogroup"]` instead of some of the options.

### Expected behavior

Focus doesn't disappear.
Focus goes directly to some of the options instead of the wrapper div.

**Comment by zernonia** [comment]
@hrubysi  can you provide a better reproduction? the focus looks fine for me

**Comment by hrubysimon** [comment]
@zernonia  Would this help?
https://github.com/user-attachments/assets/84c2a619-a62e-4d5e-ae7d-26f9dae55c61

**Comment by zernonia** [comment]
Thanks @hrubysimon , but is it happening too on [Stackblitz](https://stackblitz.com/run?file=src%2FApp.vue)? Might be browser issue. Could you perhaps try other browser?

**Comment by hrubysimon** [comment]
@zernonia It happens on Brave, Chrome, Edge.
Only browser where it worked for me is Firefox.

It found about it in my project, so it's not just related to radix-vue.com

**Comment by zernonia** [comment]
Icic.. It's kinda weird.. Can you try it here and see? https://react-spectrum.adobe.com/react-aria/RadioGroup.html#radiogroup

**Comment by zernonia** [comment]
Icic. Lastly, can you check https://www.radix-ui.com/primitives/docs/components/radio-group ? The current project is referencing from the main Radix UI repo

**Comment by hrubysimon** [comment]
That also works well.

**Comment by hrubysimon** [comment]
It seems to me, that it might be caused by `isClickFocus.value` which is probably true after clicking with mouse, then the focus handler is skipped because of it and then it's set to false.

https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/RovingFocus/RovingFocusGroup.vue#L106

**Comment by hrubysimon** [comment]
Confirmed by console log. Not sure about the safari bug, so I'm going to leave it up to you.

**Comment by zernonia** [comment]
Appreciate the insight @hrubysimon !! I think I manage to trace the issue and the same is happening on Radix UI lol

![image](https://github.com/user-attachments/assets/9729f7bf-1cca-4d6f-aac0-e012e821f2f1)
