### ISSUE TITLE
[Feature]: use vue 3.5 `useId`

### ISSUE THREAD

**Issue by RayGuo-ergou** [radix-vue/radix-vue#1267]
### Describe the feature

Since vue released 3.5 and has a ssr friendly useId, would be better to switch to it.

I can think something like this for backward compatibility

```ts
import * as v from 'vue';

// @ts-expect-error vue 3.5
if (v.useId) {
  // @ts-expect-error vue 3.5
  return v.useId();
}
```

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by Dino-Kupinic** [comment]
![image](https://github.com/user-attachments/assets/97fdfc8d-3c3f-47a4-b2ca-299635df50ab)
Is this still required?
I'm on Nuxt 3.13.1 and Vue 3.5.3
![image](https://github.com/user-attachments/assets/3d4cbaab-6969-41ee-b937-bb6dba60a7c3)

**Comment by RayGuo-ergou** [comment]
The `ConfigProvider` is still required unless migrated vue's `useId` in this lib.

The error you see is because muxt changed their `useId` to be an alias of vue's. And it could be undefined if not in an instance (e.g. toast) so you have to handle it yourself.

**Comment by zernonia** [comment]
Correct @RayGuo-ergou . Your suggestion here should eliminate the need of passing `idFunction` in Nuxt 3.13.1 onwards, and hence avoiding the ts error above 😁

**Comment by RayGuo-ergou** [comment]
Hi @zernonia should still handle the typescript error above tho as: https://github.com/vuejs/core/blob/b1430f250d6aef7f866d9a670895d83596119b42/packages/runtime-core/src/helpers/useId.ts#L8

Even tho I am not a big fan of `!` but in this case I feel it's safe to do it as the places call `useId` should under a vue app instance.

But this should indeed resolve the hydration mismatch issue.

**Comment by Saeid-Za** [comment]
I was thinking to provide a default value for the config provider, at later stages we could mark useId as deprecated.
But wouldn't `import * from vue` disable tree shaking?
If so, could we sync import useId when version criteria is satisfied?

**Comment by RayGuo-ergou** [comment]
>  But wouldn't import * from "vue" disable tree shaking?

![image](https://github.com/user-attachments/assets/206fe78b-8769-4fd8-a986-79f2d7d338a9)

Tried to build a simple project in both way, the file size seems identical. I am guessing due to vue's well structure import, vite can auto tree shaking the import.

>  If so, could we sync import useId when version criteria is satisfied?

I would suggest the nuxt way, make the `useId` as alias of vue's `useId`

**Comment by RayGuo-ergou** [comment]
Did a quick test

```js
// index.js

import * as util from './util'

util.foo()

```

```js
// util.js

function foo() {
  console.log('foo')
}
function bar() {
  console.log('bar')
}

export {
  bar,
  foo,
}
```

run `pnpx rollup index.js -f esm -o bundle.js`

get

```bash
cat bundle.js
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: bundle.js
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ function foo() {
   2   │   console.log('foo');
   3   │ }
   4   │
   5   │ foo();
```

**Comment by donPuerto** [comment]
any update on how to resolve the issue?

**Comment by Dino-Kupinic** [comment]
> any update on how to resolve the issue?

We are waiting for a PR, you can still use `ConfigProvider` like i mentioned above. If you get an error just `<!-- @vue-ignore -->` 

```
<template>
  <!-- @vue-ignore -->
  <ConfigProvider :use-id="useIdFunction">
    <NuxtLayout>
      <NuxtPage />
      <Toaster />
    </NuxtLayout>
  </ConfigProvider>
</template>
```
