### ISSUE TITLE
[Bug]: Manually set value of Range Calendar not reflected in the view

### ISSUE THREAD

**Issue by kilobyte2007** [radix-vue/radix-vue#1272]
### Environment

```bash
See stackblitz.
```

### Link to minimal reproduction

https://stackblitz.com/edit/sjvn9m?file=src%2FApp.vue

### Steps to reproduce

1. Open the reproduction
2. Click the `Set range to last month ->` button
3. See that the value is not being changed

### Describe the bug

When the Range Calendar is initially rendered, and you don't interact with it - there's no way to update it's value from outside. Well, it actually updates the value but it seems that the view is not updated.

I tried looking into the source code to see if I can fix it myself, but not sure what is causing it.
I tried using `initial-focus` with `true` and `false`, and it didn't help as I thought the reason was that the calendar was expecting an interaction first.

### Expected behavior

The value should change and should be reflected in the calendar view.

**Comment by kyselberg** [comment]
Got the exact same issue
