### ISSUE TITLE
[Bug]: Event handler is not removed

### ISSUE THREAD

**Issue by teleskop150750** [radix-vue/radix-vue#1275]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://github.com/radix-vue/radix-vue/blob/6dbf5805da20f585536fc8534a06a25956002dfa/packages/radix-vue/src/FocusScope/FocusScope.vue#L164

### Steps to reproduce

https://github.com/radix-vue/radix-vue/blob/6dbf5805da20f585536fc8534a06a25956002dfa/packages/radix-vue/src/FocusScope/FocusScope.vue#L164

### Describe the bug

Event handler is not removed

**Comment by zernonia** [comment]
the listener is bind on `container` element, and seems like the `cleanupFn` does triggered, what do you mean it's not removed ya? 😁

**Comment by teleskop150750** [comment]
a new function is passed instead of a reference to the old one

[Example](https://github.com/perigee-ui/vue-primitives/blob/8629da60cf383487f82497b1db59a1bbfec99f3e/packages/vue-primitives/src/focus-scope/FocusScope.ts#L156)

**Comment by zernonia** [comment]
Ahh you are right. Good catch. However it doesn't affect much as when the component is unmounted, it will be gone anyway, thus not really a bug. Thus closing.

**Comment by teleskop150750** [comment]
@zernonia  and what are your differences from Oku or [my fork](https://github.com/perigee-ui/vue-primitives)
