### ISSUE TITLE
[Bug]: Hydration attribute mismatch

### ISSUE THREAD

**Issue by HaraldHenriksson** [radix-vue/radix-vue#1282]
### Environment

```bash
Developement/Production OS: MacOS 14.6.1
Node version: 20.11.1
Package manager: npm@10.2.4
Radix Vue version: 1.9.5
Vue version: 3.5.3
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
@nuxtjs/tailwindcss": 6.12.1
Client OS: MacOS 14.6.1
Browser: Chrome 128.0.6613.113
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/amazing-merkle-v27268?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0wc4x7c00073b6i419qbrdg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0wc4x7b00023b6ifti7h3qu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0wc4x7c00043b6i124sxr3p%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0wc4x7c00063b6iobbw6spr%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0wc4x7b00023b6ifti7h3qu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0wc4x7b00013b6i98jkwjkg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0wca0fl00023b6ipwmxl506%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0wc4x7b00023b6ifti7h3qu%2522%252C%2522activeTabId%2522%253A%2522cm0wca0fl00023b6ipwmxl506%2522%257D%252C%2522cm0wc4x7c00063b6iobbw6spr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0wc4x7c00053b6izfxh7uaf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%257D%255D%252C%2522id%2522%253A%2522cm0wc4x7c00063b6iobbw6spr%2522%252C%2522activeTabId%2522%253A%2522cm0wc4x7c00053b6izfxh7uaf%2522%257D%252C%2522cm0wc4x7c00043b6i124sxr3p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0wc4x7c00033b6i48sobnjz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm0wc4x7c00043b6i124sxr3p%2522%252C%2522activeTabId%2522%253A%2522cm0wc4x7c00033b6i48sobnjz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Create a Nuxt.js project with server-side rendering.

Install radix-vue

Add Accordation component: <script setup lang="ts">
import { AccordionContent, AccordionHeader, AccordionItem, AccordionRoot, AccordionTrigger } from 'radix-vue'

const accordionItems = [
  {
    value: 'item-1',
    title: 'Is it accessible?',
    content: 'Yes. It adheres to the WAI-ARIA design pattern.',
  },
  {
    value: 'item-2',
    title: 'Is it unstyled?',
    content: 'Yes. It\'s unstyled by default, giving you freedom over the look and feel.',
  },
  {
    value: 'item-3',
    title: 'Can it be animated?',
    content: 'Yes! You can use the transition prop to configure the animation.',
  },
]
</script>

<template>
  <AccordionRoot
    class="bg-mauve6 w-[300px] rounded-md shadow-[0_2px_10px] shadow-black/5"
    default-value="item-1"
    type="single"
    :collapsible="true"
  >
    <template
      v-for="item in accordionItems"
      :key="item.value"
    >
      <AccordionItem
        class="focus-within:shadow-mauve12 mt-px overflow-hidden first:mt-0 first:rounded-t last:rounded-b focus-within:relative focus-within:z-10 focus-within:shadow-[0_0_0_2px]"
        :value="item.value"
      >
        <AccordionHeader class="flex">
          <AccordionTrigger class="text-grass11 shadow-mauve6 hover:bg-mauve2 flex h-[45px] flex-1 cursor-default items-center justify-between bg-white px-5 text-[15px] leading-none shadow-[0_1px_0] outline-none group">
            <span>{{ item.title }}</span>
            <Icon
              icon="radix-icons:chevron-down"
              class="text-green10 ease-[cubic-bezier(0.87,_0,_0.13,_1)] transition-transform duration-300 group-data-[state=open]:rotate-180"
            />
          </AccordionTrigger>
        </AccordionHeader>
        <AccordionContent class="text-mauve11 bg-mauve2 data-[state=open]:animate-slideDown data-[state=closed]:animate-slideUp overflow-hidden text-[15px]">
          <div class="px-5 py-4">
            {{ item.content }}
          </div>
        </AccordionContent>
      </AccordionItem>
    </template>
  </AccordionRoot>
</template>

Run application with SSR(default)

Observe the issue 

  - rendered on server: id="radix-vue-collapsible-content-986"
  - expected on client: id="radix-vue-collapsible-content-15"

 

### Describe the bug

The ID's generated during server-side rendering differ from those generated on the client during hydration.

  - rendered on server: id="radix-vue-collapsible-content-986"
  - expected on client: id="radix-vue-collapsible-content-15"

### Expected behavior

The server and client IDs should match to prevent hydration mismatches during SSR.

### Context & Screenshots (if applicable)

![Screenshot 2024-09-10 at 13 40 51](https://github.com/user-attachments/assets/7422ea6c-c43f-4faf-a157-ddb79daf9a02)

**Comment by zernonia** [comment]
Duplicated of https://github.com/radix-vue/radix-vue/issues/577, please find the solution in the issue

**Comment by HaraldHenriksson** [comment]
@zernonia useId should not be needed in vue 3.5 if im correct? thanks for your reply

**Comment by zernonia** [comment]
Technically yes. But internally we are still using interal `useId`, and requires user to pass in `useId` function still. Here's a ticket for using newly introduced `useId` from Vue https://github.com/radix-vue/radix-vue/issues/1267
