### ISSUE TITLE
[Bug]: Combobox performance when using object-values

### ISSUE THREAD

**Issue by JarvisH** [radix-vue/radix-vue#1317]
### Environment

```bash
MacOS 14.4.1 (23E224)
Node version: 18.20.3
Package manager: pnpm@8.6.0
Radix Vue version: 1.9.6
Vue version: latest
```

### Link to minimal reproduction

https://stackblitz.com/edit/tjcvb4?file=src%2FApp.vue

### Steps to reproduce

In the stackblitz example, two comboboxes are present. The first uses a long list of objects, combined with external filtering made according to the documentation. When expanding the full list and entering a search value, the list is very laggy when filtering, sometimes taking 1-2 seconds to update. Note, the full list has to be visible while searching for the issue to really present itself. Closing the full unfiltered list is also very laggy.

Compare this to the second combobox where all options are simple strings. Filtering and closing the list is more or less instant.

### Describe the bug

I suspect the filtering lag has to do with this computed in `ComboboxItem.vue`:

```ts
const isInOption = computed(() =>
  rootContext.isUserInputted.value
    ? rootContext.searchTerm.value === ''
    || !!rootContext.filteredOptions.value.find(i => isEqual(i, props.value))
    : true)
```

If rendering a list of 500 items, we are calling `find` 500 times and find itself again calls `isEqual` between 1-500 times. This does not scale well, and is entirely redundant, as we are filtering the options externally and are not relying on any internal filtering. 

Why closing the list is laggy, I am not sure.

### Expected behavior

When filtering the list of options externally, internal filtering and hiding of options via `display:none` should be prevented.

**Comment by sunnylost** [comment]
I agree with this. Add a prop like `ignoreInternalFilter` to `ComboboxRoot` to skip the `isInOption` check.

**Comment by zernonia** [comment]
The refactor as discussed [previously](https://github.com/radix-vue/radix-vue/issues/498) was implemented on v2 😁 
Thus closing this ya
