### ISSUE TITLE
[Feature]: Allow string for `padding` and `margin` in `ScrollBodyOption`

### ISSUE THREAD

**Issue by Barbapapazes** [radix-vue/radix-vue#1319]
### Describe the feature

Hello,

Actually, it's only possible to pass a number which is converted to `px`. But this is annoying when everything in the page use `rem` because you have to convert value. Couldn't be possible to pass a string like `0.6rem` instead of `9.6`?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by hrynevychroman** [comment]
I will try to investigate this 🙌

**Comment by Barbapapazes** [comment]
> I will try to investigate this 🙌

It's related to these lines: https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/shared/useBodyScrollLock.ts#L67-L68

**Comment by hrynevychroman** [comment]
Yeah, I will open PR soon 🙌
