### ISSUE TITLE
[Bug]: DropdownMenu blocking scroll and overflowing on mobile

### ISSUE THREAD

**Issue by Albermonte** [radix-vue/radix-vue#1333]
### Environment

```bash
Developement/Production OS: -
Node version: -
Package manager: -
Radix Vue version: 1.9.6
Vue version: latest
CSS framework: tailwindcss@latest
Client OS: -
Browser: -
```

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/53d932?file=src/App.vue

### Steps to reproduce

Open the DropdownMenu in a samll mobile

### Describe the bug

When the DropdownMenu is bigger than the screen it will prevent scroll and overflow.

### Expected behavior

DropdownMenu should not overflow, having a max height and adding a scroll inside it.

### Context & Screenshots (if applicable)

Small screen:
![image](https://github.com/user-attachments/assets/7f8bfb2a-7f2a-4b15-9a52-03b85cfc019d)

Big screen:
![image](https://github.com/user-attachments/assets/418adcee-b8d3-4c3e-bacd-27f7af0720c7)

**Comment by zernonia** [comment]
@Albermonte  This seems like not an issue. `Dropdown` component blocks scrolling is expected, you can set `modal="false"` on `DropdownRoot` and it will not be blocked.

As for the max-height and scrolling, that depends on your css. In the demo we did not cater for extra small viewport, so not an issue also.
