### ISSUE TITLE
[Checkbox]feat: 2/3

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#135]
Phase 2 of this project development is about making all API such as props, emits and data-attributes, work as expected. Below is the list of API needed to be completely working to get through the phase 2 of development.

The list is structured as below:
Prop/emit/data-attributes | Type | Default
### Props
- [ ] asChild boolean false
- [ ] defaultChecked string - 
- [ ] checked string -
- [ ] onCheckedChange function -
- [ ] disabled boolean -
- [ ] required boolean -
- [ ] name string -
- [ ] value string on

### Data Attributes
- [ ] [data-state] "checked" | "unchecked" | "indeterminate"
- [ ] [data-disabled] present when disabled

### Props
- [ ] asChild boolean false
- [ ] forceMount boolean -

### Data Attributes
- [ ] [data-state] "open"|"closed"
- [ ] [data-disabled] present when disabled

**Comment by DennisSmuda** [comment]
@khairulhaaziq does this still need work? 🤔

**Comment by zernonia** [comment]
https://github.com/radix-vue/radix-vue/pull/359
