### ISSUE TITLE
[Tabs]feat: 2/3

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#145]
Phase 2 of this project development is about making all API such as props, emits and data-attributes, work as expected. Below is the list of API needed to be completely working to get through the phase 2 of development.

The list is structured as below:
Prop/emit/data-attributes | Type | Default
### Props
- [ ] asChild boolean false
- [ ] defaultValue string - 
- [ ] value string -
- [ ] onValueChange function -
- [ ] orientation "horizontal"|"vertical" "horizontal"
- [ ] dir "ltr" | "rtl" -
- [ ] activationMode "automatic" | "manual" -

### Data Attributes
- [ ] [data-orientation] "vertical"|"horizontal"

### Props
- [ ] asChild boolean false
- [ ] loop boolean true

### Data Attributes
- [ ] [data-orientation] "vertical"|"horizontal"

### Props
- [ ] asChild boolean false
- [ ] value* string -
- [ ] disabled boolean false

### Data Attributes
- [ ] [data-state] "active"|"inactive"
- [ ] [data-disabled] present when disabled
- [ ] [data-orientation] "vertical"|"horizontal"

## Related
#23

**Comment by onmax** [comment]
I am working on this. I see that there is a "Thumb" Component. I guess this is a mistake from copy and paste from another issue?

**Comment by khairulhaaziq** [comment]
Ah yes probably,

> I am working on this. I see that there is a "Thumb" Component. I guess this is a mistake from copy and paste from another issue?

Ah yes sorry. Please refer to original radix for confirmation

**Comment by onmax** [comment]
Should I fork the repo and create the draft PR from my forked repo or should I request access to push?

**Comment by khairulhaaziq** [comment]
@onmax you can fork it, create a new branch and then create draft pr

**Comment by khairulhaaziq** [comment]
closed with #182
