### ISSUE TITLE
[Toggle]feat: 2/3

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#146]
Phase 2 of this project development is about making all API such as props, emits and data-attributes, work as expected. Below is the list of API needed to be completely working to get through the phase 2 of development.

The list is structured as below:
Prop/emit/data-attributes | Type | Default
### Props
- [x] asChild boolean false
- [x] defaultPressed boolean - 
- [x] pressed boolean -
- [ ] onPressedChange function -
- [x] disabled boolean false

### Data Attributes
- [x] [data-state] "on"|"off"
- [x] [data-disabled] present when disabled

## Related
#24

**Comment by DennisSmuda** [comment]
@khairulhaaziq - why is this closed? 😅 
I'm almost done, just have to change `modelValue` to `pressed` 🙏

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq - why is this closed? 😅 I'm almost done, just have to change `modelValue` to `pressed` 🙏

sorry I closed a bunch of issues and overlook it, please continue 🙏
