### ISSUE TITLE
[Docs]bug: TOC active styles not applying

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#152]
bug: TOC active styles not applying

**Comment by zernonia** [comment]
@khairulhaaziq  What's the reason you add the `slug` pages, and the `useDocus` composable that was provided by Docus?
It's causing the TOC not applying the scrollspy correctly.


![image](https://github.com/radix-vue/radix-vue/assets/59365435/7b4dfb33-3186-42a8-bdeb-80a30fb7905f)

**Comment by khairulhaaziq** [comment]
@zernonia  solely for forcing dark mode. you can test by switching to light mode and removing the slug file. I dont know any alternatives currently but if there is feel free to replace it

**Comment by zernonia** [comment]
Hmm.. changing to light mode on Mac looks fine (after removing slug files), and TOC is working as expected

![image](https://github.com/radix-vue/radix-vue/assets/59365435/6422e2c2-e109-4022-a5a8-90786f7b399e)

**Comment by zernonia** [comment]
> Hmm.. changing to light mode on Mac looks fine (after removing slug files), and TOC is working as expected
> 

Ah I think I understand why it's showing 'light' for you. When initially we setup the docs, it was by set to `system` preferences, thus your browser cached that value locally.

If you clear cache, and turn on light mode, it should be all good now.

**Comment by khairulhaaziq** [comment]
> Hmm.. changing to light mode on Mac looks fine (after removing slug files), and TOC is working as expected
> 
> ![image](https://user-images.githubusercontent.com/59365435/252530944-6422e2c2-e109-4022-a5a8-90786f7b399e.png)

ok lets remove them, i'll do it in a sec

**Comment by khairulhaaziq** [comment]
fixed #108 https://github.com/radix-vue/radix-vue/pull/108/commits/b67732862d4a7a0b8dd0b1713f84b718112e0721
