### ISSUE TITLE
[Docs]feat: Add spotlight search

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#163]
Feat: Add spotlight / cmd+k search in docs

Example in vueuse docs:
<img width="1254" alt="Screenshot 2023-07-11 at 12 05 19 PM" src="https://github.com/radix-vue/radix-vue/assets/101852870/2cdcac76-a2d2-49eb-99ff-4dd7a55547d8">

**Comment by zernonia** [comment]
Came across this PR ytd! Maybe we can use it when released

https://github.com/nuxt-themes/docus/pull/930

**Comment by zernonia** [comment]
Since we moved to Vitepress, can check this out https://vitepress.dev/reference/default-theme-search#search

**Comment by khairulhaaziq** [comment]
solved
