### ISSUE TITLE
[Popper, Submenus]feat: add safe polygon feature

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#169]
enhancement: add safe polygon feature for better UX and accessibility:

### Reference
https://github.com/floating-ui/floating-ui/blob/073da89da80577565a69cebd786430e11ea9e3bc/packages/react/src/safePolygon.ts

https://floating-ui.com/docs/useHover#safepolygon

https://height.app/blog/guide-to-build-context-menus

https://github.com/radix-ui/primitives/pull/688 #214

**Comment by khairulhaaziq** [comment]
@zernonia do you think this can be done with floating ui? they have that feature supported in react.
ref:
https://github.com/radix-ui/primitives/pull/688
https://floating-ui.com/docs/useHover#safepolygon

**Comment by zernonia** [comment]
I think that's possible. I'm thinking to create a package `floating-ui/vue-composable` to have all the build in feature similar to React. That way we could benefit Vue community with that feature, and not limited to Radix-Vue. 

But yeah I can implement this 😁

**Comment by khairulhaaziq** [comment]
> I think that's possible. I'm thinking to create a package `floating-ui/vue-composable` to have all the build in feature similar to React. That way we could benefit Vue community with that feature, and not limited to Radix-Vue.
> 
> But yeah I can implement this here to test it out 😁

yeah thats a huge task, I think floating-ui team wouldnt mind if you lead the official floating-ui/vue package. but yeah, huge task 😂
