### ISSUE TITLE
[DOCS]bug: accordion animation bug

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#210]
if accordion directly loaded at https://www.radix-vue.com/components/accordion.html , the animation behaves rather weirdly

**Comment by zernonia** [comment]
@khairulhaaziq  what do you mean opened through a link ya? U mean when directly load https://www.radix-vue.com/components/accordion.html ?

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq what do you mean opened through a link ya? U mean when directly load https://www.radix-vue.com/components/accordion.html ?
> 
> If so, yeah I've noticed this too. Might be something related to SSR state. I will look into this as I've planned on improving `Presence` component 😁

correct haha. I dont know how to phrase it properly. Alright thanks!

**Comment by zernonia** [comment]
turns out that RadixUI also having this issue. So will deprioritize this ftm, until I refactor the `Presence` component 



https://github.com/radix-vue/radix-vue/assets/59365435/a93bd6c9-27b2-4e03-b6e2-905404c0700e
