### ISSUE TITLE
[Tooltip]: Trigger asChild doesn't work

### ISSUE THREAD

**Issue by steakscience** [radix-vue/radix-vue#221]
**Describe the bug**
The asChild prop doesn't work.

**To Reproduce**
After adding asChild, there won't be a trigger in the end result at all.

**Comment by khairulhaaziq** [comment]
@zernonia

**Comment by zernonia** [comment]
Hey @steakscience ,what do you mean yaa? It works perfectly fine. Care to create a reproduction?

![image](https://github.com/radix-vue/radix-vue/assets/59365435/e20d5591-f720-46f8-98ea-f8a80c4d85a8)
![image](https://github.com/radix-vue/radix-vue/assets/59365435/b13efed8-2924-470a-8f23-ab4c49d37b91)

**Comment by steakscience** [comment]
@zernonia Sure!

`<Tooltip>` component
```html
<template>
  <TooltipRoot>
    <TooltipTrigger asChild>
      <slot />
    </TooltipTrigger>
    <TooltipPortal>
      <TooltipContent>
        ...
      </TooltipContent>
    </TooltipPortal>
  </TooltipRoot>
</template>
```

In-use:
```html
<Tooltip>
  <Button>
    ...
  </Button>
</Tooltip>
```

Output: (missing stuff like `data-state="instant-open`, etc)
<img width="1014" alt="image" src="https://github.com/radix-vue/radix-vue/assets/2727095/5df1f48e-b634-40d1-993d-2a1a561aef66">

Output, when not using asChild:
<img width="1013" alt="image" src="https://github.com/radix-vue/radix-vue/assets/2727095/dbd7d892-2c53-49e3-b3f7-00d79ced7323">

**Comment by zernonia** [comment]
Thanks for the example above @steakscience  👍🏻
