### ISSUE TITLE
[Dropdown]:warning being printed out on render and onSelect event doesn't work on item

### ISSUE THREAD

**Issue by therealokoro** [radix-vue/radix-vue#222]
## Symbo() not found warning
This warning is printed out each time the dropdown is activated. I want to believe that is not such a good thing.

## onSelect event not working as expected.
Functions passed to the `onSelect` event do not get called at all. Which also means `e.preventDefault()` doesn't work and menu still closes

**Expected behavior**
No warnings printed to the console

**Screenshots**
![image](https://github.com/radix-vue/radix-vue/assets/41494675/0f534cf6-89b6-4b93-a76a-2e5dc25a6cac)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [latest]

**Comment by zernonia** [comment]
@therealokoro  this issue was fixed, and we've changed from Function props `onSelect` to `@select` (Vue's emit).
You can now prevent menu from closing by doing so `@select.prevent`! Cheers!
