### ISSUE TITLE
[Tooltip]: asChild doesn't keep all props

### ISSUE THREAD

**Issue by steakscience** [radix-vue/radix-vue#226]
**Describe the bug**
Related to #224
When using asChild with Tooltip, some props are not kept

**To Reproduce**
Use slots in tooltip trigger
```html
<TooltipTrigger asChild>
  <slot />
</TooltipTrigger>
```

I have props on my Button element
```html
<Tooltip>
  <Button type="tertiary" iconOnly>
    ...
  </Button>
</Tooltip>
```

**Result:**
<Button> loses the `type="tertiary"` prop, but keeps `iconOnly` boolean prop. Not sure why.

**Expected result:**
It should keep all props

@zernonia

**Comment by zernonia** [comment]
Hi @steakscience .. how do you know that the props are not kept ya? Does it not appear in your component?
But if you mean you check the element html via the console, it is missing, that is a [correct behavior](https://vuejs.org/guide/components/attrs.html#nested-component-inheritance).

**Comment by steakscience** [comment]
@zernonia Good point. 

In my case, I have class names that will be added if `type="tertiary"` but they are missing.

However, class names from `iconOnly` are there

**Comment by khairulhaaziq** [comment]
> @zernonia Good point. 
> 
> 
> 
> In my case, I have class names that will be added if `type="tertiary"` but they are missing.
> 
> 
> 
> However, class names from `iconOnly` are there

Can you share your logic for the conditional classes for types props?

**Comment by zernonia** [comment]
Can you do a console.log for "prop.type"? I wanna see if the component recevied this props

**Comment by steakscience** [comment]
@khairulhaaziq Sure, it's the same as the [class bindings in the Vue docs](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes)
<img width="910" alt="image" src="https://github.com/radix-vue/radix-vue/assets/2727095/582f7f43-3794-4adc-8f3d-f0b46ceadee3">

**Comment by steakscience** [comment]
@zernonia Looks like it received the props? But also `button` isn't a prop
<img width="1391" alt="image" src="https://github.com/radix-vue/radix-vue/assets/2727095/51de0b24-2f61-4a0e-af76-9eb9509ef69e">

**Comment by zernonia** [comment]
Hmmm.. icic.. cause the `TooltipTrigger` is having a type 'button' here, which is why it cause the bug.
I would need to overwrite the type if the child component (in this case your Button) has a prop type.

Thanks for the info @steakscience 

![image](https://github.com/radix-vue/radix-vue/assets/59365435/a5e46f2f-441d-4914-acf8-36542fb80b05)

**Comment by steakscience** [comment]
If it ends up that you want to keep tooltiptrigger as a button, I suggest allowing `as="template"` for people who want to skip the button

Thanks! :)
