### ISSUE TITLE
Incorrect default value for TooltipContent "side" props

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#235]
From the docs:
![image](https://github.com/radix-vue/radix-vue/assets/51422045/250e73f1-c983-43df-b10c-7b058e14050e)
Actual code: https://github.com/radix-vue/radix-vue/blob/93794472f5194f510e0c780996d79b7a59a6a0b9/packages/radix-vue/src/Tooltip/TooltipContent.vue#L18-L21

"top" => "bottom" ?

**Comment by khairulhaaziq** [comment]
thanks! fixed #175
