### ISSUE TITLE
Title Tooltip trigger position not visible on the Histoire page

### ISSUE THREAD

**Issue by misbahansori** [radix-vue/radix-vue#239]
When I'm trying to fix the tooltip component, the tooltip trigger position is in the top left corner. In that case, the tooltip content is not visible. 

<img width="808" alt="Screenshot 2023-07-24 at 06 23 06" src="https://github.com/radix-vue/radix-vue/assets/20674057/0b111ef4-9de7-461d-9189-bb7399f2a85f">

It's also a problem with most of the components. I think it would be better if the components were displayed in the center of the page.

I would be happy to help with this issue if you think it's a good idea.

**Comment by khairulhaaziq** [comment]
yes please, you can fix it

**Comment by zernonia** [comment]
You can look at `Accordion` story, where we have some grid layout, which would put components in the center 😁
