### ISSUE TITLE
Add onMouseOver Prop to MenubarTrigger for Mouse Hover Menu Expansion

### ISSUE THREAD

**Issue by dwzkit** [radix-vue/radix-vue#240]
**Is your feature request related to a problem? Please describe.**
No a bug

**Describe the solution you'd like**
I am using the MenubarTrigger component in my project and have a requirement to expand the MenubarItem when the mouse hovers over the MenubarTrigger, not just on click.

Currently, the MenubarTrigger component listens for a click event to expand the MenubarItem. I'm interested in having an additional prop, let's call it onMouseOver, that when set to true, enables the MenubarItem to expand when the mouse hovers over the MenubarTrigger.

The expected behavior would look something like this:
```
<MenubarTrigger
    onMouseOver={true} // new prop
    class="py-2 px-3 outline-none select-none font-semibold leading-none rounded text-grass11 text-[13px] flex items-center justify-between gap-[2px] data-[highlighted]:bg-green4 data-[state=open]:bg-green4"
>
  Edit
</MenubarTrigger>

```

**Describe alternatives you've considered**
With this prop set to true, when the mouse hovers over the MenubarTrigger, the MenubarItem would expand as if the MenubarTrigger had been clicked.

This feature would give developers more flexibility when designing their user interface, allowing for either click or hover interactions to expand the menu.

Please let me know if there's any additional information you need for this feature request. I appreciate your consideration.

**Additional context**

**Comment by khairulhaaziq** [comment]
Hi thank you, the Menubar state is able to be controlled, meaning you can control the state manually, and able to put a reactive value to choose which menubar item should be opened however you want. So I think what you can do is, create a function to manage the menubar state and handle it via the hover event:

```vue
<script setup>
ref menubarValue = ref('')

function openMenubar(item) {
  menubarValue.value = item
}
</script>

<template>
  <MenubarRoot @mouseout="openMenubar('')">
    <MenubarMenu value="item-1">
      <MenubarTrigger @mouseover="openMenubar('item-1')"></MenubarTrigger>
    </MenubarMenu>
    <MenubarMenu value="item-2">
      <MenubarTrigger @mouseover="openMenubar('item-2')"></MenubarTrigger>
    </MenubarMenu>
  </MenubarRoot>
</template>
```

lmk is this doesnt work

**Comment by khairulhaaziq** [comment]
Hi I saw you close this issue. @dwzkit does it work fine? Let us know if theres any issues!
