### ISSUE TITLE
[Vue warn] Component emitted an undefined event.

### ISSUE THREAD

**Issue by uyloal** [radix-vue/radix-vue#252]
**Describe the bug**

`defineEmits` has a different event name with the key of `useVModel`.

`useVModel` will emit two events: `update:modelValue` and `update:open`

```ts
...

const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
}>();

const open = useVModel(props, "open", emit, {
  defaultValue: props.defaultOpen,
  passive: true,

...
```

Included components:
- AlertDialogRoot
- DialogRoot

**Screenshots**
![image](https://github.com/radix-vue/radix-vue/assets/37807381/06dcab5b-63e8-4dc9-a49b-1d5acf0b17a1)

**Desktop (please complete the following information):**
 - Device: desktop
 - OS: macOS 13.4
 - Browser [chrome]
 - Version [latest]

**Comment by khairulhaaziq** [comment]
hi do you want to work on this issue? idk what's exactly the issue

**Comment by uyloal** [comment]
@khairulhaaziq Yes, I have created a pr #253
