### ISSUE TITLE
[Dialog]: mobile browser scroll unlock

### ISSUE THREAD

**Issue by Zhengqbbb** [radix-vue/radix-vue#256]
**Describe the bug**
 Mobile browser scroll unlock

**To Reproduce**
1. Use mobile browser to https://www.radix-vue.com/components/dialog.html
2. Open dialog. Scroll unlocked

**Expected behavior**
Scroll will be locked

**Screenshots**

https://github.com/radix-vue/radix-vue/assets/40693636/4df83801-c0e4-42bd-bd8a-2cf3f34881b3

**Smartphone (please complete the following information):**
 - Device: iPhone
 - Browser Chrome

**Comment by Zhengqbbb** [comment]
Desktop (please complete the following information)
 - OS: MacOS 13.4.1 
 - Browser: safari
 - Version 16.5.2 (18615.2.9.11.10)

Also have the same problem, not sure if it's a safari problem.

**Comment by khairulhaaziq** [comment]
thanks! we'll look into it!

**Comment by khairulhaaziq** [comment]
closed with #265
