### ISSUE TITLE
Tooltip: Trigger overrides cursor styles

### ISSUE THREAD

**Issue by steakscience** [radix-vue/radix-vue#258]
**Describe the bug**
`<TooltipTrigger>` has an inline style `cursor: default`

This should not be included and will override any styles from child elements

**Comment by khairulhaaziq** [comment]
hi yeah sorry about that, do you want to create a pr and fix the issue?

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq Got it

thanks so much! haha I love getting more people involved!
