### ISSUE TITLE
Invalid watch source for Accordion

### ISSUE THREAD

**Issue by BayBreezy** [radix-vue/radix-vue#259]
Hello,

Thank you for working on this. I am a Nuxt person. I tried recreating the components on the shadcn-ui website with the components from this package and I am getting this warning in the terminal and browser console. It may be Nuxt 3 specific, I am not sure.

**Describe the bug**
I keep gettting this warning in the browser and in the VSCode terminal:
`[Vue warn]: Invalid watch source:  item-1 A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types.`

**To Reproduce**

This is the component that I created:

<details>
<summary>Click to see code</summary>

```vue
<template>
  <AccordionRoot class="w-full" :collapsible="collapsible" v-model="model" :type="type">
    <template v-for="(item, i) in items">
      <AccordionItem class="border-b" :value="item.value">
        <AccordionHeader>
          <AccordionTrigger
            class="flex w-full flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180"
          >
            <span>{{ item.title }}</span>
            <Icon class="h-4 w-4 shrink-0 transition-transform duration-200" :name="icon" />
          </AccordionTrigger>
        </AccordionHeader>

        <AccordionContent class="content overflow-hidden text-sm transition-all">
          <div class="py-4 pt-0" v-html="item.content" />
        </AccordionContent>
      </AccordionItem>
    </template>
  </AccordionRoot>
</template>
<script setup lang="ts">
  import {
    AccordionContent,
    AccordionHeader,
    AccordionItem,
    AccordionRoot,
    AccordionTrigger,
  } from "radix-vue";
  import type { AccordionRootProps } from "radix-vue/dist/Accordion";

  const props = withDefaults(
    defineProps<{
      modelValue?: AccordionRootProps["modelValue"];
      type?: AccordionRootProps["type"];
      collapsible?: AccordionRootProps["collapsible"];
      items: {
        title: string;
        content: string;
        value: string;
      }[];
      icon?: string;
    }>(),
    {
      type: "single",
      collapsible: true,
      icon: "heroicons:chevron-down",
    }
  );

  const emit = defineEmits<{
    "update:modelValue": [arg: AccordionRootProps["modelValue"]];
  }>();

  const model = computed({
    get: () => props.modelValue ?? [],
    set: (value: AccordionRootProps["modelValue"]) => emit("update:modelValue", value),
  });
</script>

<style scoped>
  .content[data-state="open"] {
    animation: down 200ms ease-out;
  }
  .content[data-state="closed"] {
    animation: up 100ms ease-out;
  }

  @keyframes down {
    from {
      height: 0;
    }
    to {
      height: var(--radix-accordion-content-height);
    }
  }

  @keyframes up {
    from {
      height: var(--radix-accordion-content-height);
    }
    to {
      height: 0;
      opacity: 0;
    }
  }
</style>
```
</details>

This is how the component is being used:

<details>
<summary>Click to see usage</summary>

```vue
<template>
  <div class="w-[450px]">
    <UIAccordion :items="accordionItems" v-model="item" />
  </div>
</template>

<script setup lang="ts">
  const item = ref("item-1");
  const accordionItems = [
    {
      value: "item-1",
      title: "Is it accessible?",
      content: "Yes. It adheres to the WAI-ARIA design pattern.",
    },
    {
      value: "item-2",
      title: "Is it unstyled?",
      content: "Yes. It's unstyled by default, giving you freedom over the look and feel.",
    },
    {
      value: "item-3",
      title: "Can it be animated?",
      content: "Yes! You can use the transition prop to configure the animation.",
    },
  ];
</script>
```
</details>

**Expected behavior**
Well, I expect no warnings

**Screenshots**
Browser
<img width="1418" alt="image" src="https://github.com/radix-vue/radix-vue/assets/53905713/56e859e2-869e-4342-b6bd-db5a15a83d0d">

Terminal
<img width="1075" alt="image" src="https://github.com/radix-vue/radix-vue/assets/53905713/4a78e59e-7ff1-4f67-839a-0dbc972d5ef3">

**Desktop (please complete the following information):**
 - OS: MacOS & Windows
 - Browser Chrome Browser

**Additional context**
Nuxt Info:

- Operating System: `Darwin`
- Node Version:     `v16.19.1`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `app`
- Runtime Modules:  `nuxt-icon@0.4.2`, `@nuxtjs/tailwindcss@6.8.0`, `@morev/vue-transitions/nuxt@2.3.6`
- Build Modules:    `-`

**Comment by khairulhaaziq** [comment]
thanks! can you provide a reproduction so we can have a more clear understanding of the issue?

**Comment by BayBreezy** [comment]
I will make the changes & let you know soon. Thanks

**Comment by BayBreezy** [comment]
@khairulhaaziq here is a link to the reproduction: https://stackblitz.com/edit/nuxt-starter-ws3qeq?file=components%2FUI%2FAccordion.vue

I tried using useVmodel but got the same results.

**Comment by BayBreezy** [comment]
Remember that this does not break anything, so there is no need to stress over it. I was just bringing it to your attention so it can be looked at later.

**Comment by khairulhaaziq** [comment]
hi yeah sorry this is on our side. yeah I dont think it is an issue, we will try and find a fix when we have time someday probably, but not a problem at all I think. Thanks so much for the stackblitz, wish everyone does that! Btw are you working on something like shadcn?

**Comment by BayBreezy** [comment]
No problem, it can be updated some day in the future. For now, it does not break anything.

Yes, I have created shadcn for Nuxt many times over lol. I decided to create it again when I saw this package being worked on. 
The reason why I keep starting over is because I have to be installing packages from all over the place to get the functionality I need and documenting is a pain. I will share the link to the last iteration that I worked on. 
My hope is that I can rewrite it one final time with Radix Vue

**Comment by khairulhaaziq** [comment]
> No problem, it can be updated some day in the future. For now, it does not break anything.
> 
> Yes, I have created shadcn for Nuxt many times over lol. I decided to create it again when I saw this package being worked on. The reason why I keep starting over is because I have to be installing packages from all over the place to get the functionality I need and documenting is a pain. I will share the link to the last iteration that I worked on. My hope is that I can rewrite it one final time with Radix Vue

yeah please share it I personally need it 😂. you can contact us directly in discord if you have any more issues

**Comment by BayBreezy** [comment]
Here it is:
Website: [duxt-ui.netlify.app](https://duxt-ui.netlify.app/)
Repo: https://github.com/BayBreezy/duxt-ui
