### ISSUE TITLE
[Presence][Collapsible][Accordion]: a way to prevent content from being rendered when hidden

### ISSUE THREAD

**Issue by renatodeleao** [radix-vue/radix-vue#260]
**Is your feature request related to a problem? Please describe.**
When rendering a long list of collapsible elements — either directly or by using an accordion — collapsible content is still fully rendered into the DOM when closed (display: none) which can affect the page rendering performance. More noticeable when collapsed content is not just simple text but heavy component compositions.

https://github.com/radix-vue/radix-vue/blob/50a951b166d6b17f8cc25bfe61b7e07516dc5031/packages/radix-vue/src/Presence/Presence.vue#L30-L35

**Describe the solution you'd like**
1. Either a way to customize the output via prop: `<Collapsible collapse-mode="display|render" />` (Pseudo-idea)
1. Follow radix-ui implementation and render `CollapsibleContent` slot content when open, remove when closed [^1][^2][^3].

**Possible side-effects**
This change will probably affect the way `Presence` transitions work (not sure) 🤔 .

**Last note**
Amazing work done with this lib and thanks for the effort of bringing Radix to the `Vue` community! 🙏 

[^1]: https://github.com/radix-ui/primitives/blob/eca6babd188df465f64f23f3584738b85dba610e/packages/react/presence/src/Presence.tsx#L24
[^2]: https://www.radix-ui.com/docs/primitives/components/collapsible
[^3]: https://www.radix-ui.com/docs/primitives/components/accordion

**Comment by khairulhaaziq** [comment]
great suggestion! @zernonia

**Comment by khairulhaaziq** [comment]
do you want to try and fix the issue?

**Comment by zernonia** [comment]
Yeah this is included in [Presne](https://github.com/radix-vue/radix-vue/pull/245)
