### ISSUE TITLE
Color aliasing / Style tokens

### ISSUE THREAD

**Issue by samzuercher** [radix-vue/radix-vue#271]
Instead of directly applying colors in templates like 'bg-violet' [here](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Select/Select.story.vue) it might be better to use aliases for colors e.g. 'primary', 'secondary'. That would make customization and theming (dark mode) a lot easier. It should also reduce your work, as you could just reuse the same colors.

**Comment by zernonia** [comment]
Thanks for the suggestion @samzuercher .. currently we are focusing on the component core function itself, rather than the UI. However, you are free to create a PR for this and help contributing 😁

**Comment by samzuercher** [comment]
I had a look into this and saw, that it is not so easy.. There are multiple philosophies: Material has a quite comprehensive [color system](https://m3.material.io/styles/color/the-color-system/tokens) around theming, bootstrap is doing it differently and probably there are more solutions.

Instead of creating a new color-system (which would mean a ton of work and expertise) it might be best to adapt an existing one. Material seems to be one of the most comprehensive and to me makes a lot sense. It might be technically possible to use e.g. the [material theme builder](https://m3.material.io/theme-builder) by exporting/importing the generated .css-definitions (e.g. --md-sys-color-on-primary).

I am mostly a backend-developer and am lacking expertise in the frontend. Someone with a deeper understanding of theming and material should propose a color-token-concept.

**Comment by zernonia** [comment]
Thanks for the comment @samzuercher . As Radix Vue is just primitive components, and it doesn't include any styling out of the box. This discussion could be better discuss in library that build on top of this. 😁

Cheers!

**Comment by samzuercher** [comment]
@zernonia : Not sure. Radix Vue is primitive components, fine. But radix-vue is using theming itself even with dark-mode: [https://www.radix-vue.com/components/select.html](https://www.radix-vue.com/components/select.html). So these are already samples built on top of Radix Vue. 

Also every UI these days should use theming. Therefore I think theming including transitions should be part of a component library, probably similar to [https://fluent2.microsoft.design/components/web/react/fluentprovider/code](https://fluent2.microsoft.design/components/web/react/fluentprovider/code)

I understand that this is quite some work, but it would also mean a huge advantage for radix vue.
