### ISSUE TITLE
[AlertDialog] prevent body from content shift when overflow is hidden

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#273]
I think `useScrollLock` hook from vueuse doesn't fit for our purpose, because it sets overflow to "hidden" and causes content shift.

https://github.com/radix-vue/radix-vue/blob/24124e7f43b6dc04b01be4946cefa2ad3a70d8b2/packages/radix-vue/src/AlertDialog/AlertDialogRoot.vue#L44-L48

In original radix alert dialog they just use `pointer-events: none;`. My suggestion:

```ts
watch(open, (open) => {
  if (open) {
    document.body.style.pointerEvents = "none";
  } else {
  	document.body.style.pointerEvents = null;
  }
})
```

**Comment by khairulhaaziq** [comment]
you were the one removed it hahah. yeah just create a PR and propose your solution

**Comment by MellKam** [comment]
> you were the one removed it hahah. yeah just create a PR and propose your solution

Sorr of, I just merged the main branch with these changes and thought that it worked the same as before. XDDD

**Comment by khairulhaaziq** [comment]
> > you were the one removed it hahah. yeah just create a PR and propose your solution
> 
> Sorr of, I just merged the main branch with these changes and thought that it worked the same as before. XDDD

create a pr for this, if it takes too long I might revert first
