### ISSUE TITLE
Tooltip: Skip delay

### ISSUE THREAD

**Issue by steakscience** [radix-vue/radix-vue#283]
**Describe the bug**
No more option for skip delay duration

`<TooltipProvider>` is gone, so there is no way to set skip delay duration anymore

This would be great to add back somehow

<img width="751" alt="image" src="https://github.com/radix-vue/radix-vue/assets/2727095/9b513c3c-a7fa-4387-ab7b-b9b1db986231">

**Comment by zernonia** [comment]
@onmax  I realized we don't have `<TooltipProvider>` for that component, however I believe we can just add `skipDelayDuration` to the `<TooltipRoot>`, and provide the value from there.
