### ISSUE TITLE
[Popover] Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by Zhengqbbb** [radix-vue/radix-vue#285]
**Describe the bug**
console error : Unable to preventDefault inside passive event listener invocation.

**To Reproduce**
1. Go to https://www.radix-vue.com/components/popover.html
2. F12

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/radix-vue/radix-vue/assets/40693636/15e31cfd-94c6-4a9b-861f-7bd74ddefe31

**Comment by zernonia** [comment]
@onmax  this PR https://github.com/radix-vue/radix-vue/pull/251 does fix the issue with `preventDefault` right? 😁 By using the `useEmitsCancellableEvents`
