### ISSUE TITLE
[Slider]: can't set the max prop to any number unless 100

### ISSUE THREAD

**Issue by kaiser-9527** [radix-vue/radix-vue#288]
When set the prop `:max='150'`, the component acting weird

[codesandbox demo](https://codesandbox.io/p/sandbox/radix-vue-slider-forked-zmg7mm?file=%2Fsrc%2FApp.vue%3A13%2C17)

**Comment by awweather** [comment]
Will second this, the slider max value does not work properly.  I see your working on it already, so I'm excited!
