### ISSUE TITLE
"as", "asChild" props dont work on `DropdownMenuItem` component

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#315]
I will try to make a codesandbox reproduction today.

```vue
<DropdownMenuItem asChild>
	<RouterLink
		to="/profile"
		class="inline-flex w-full ..."
	>
		<UserIcon class="h-[18px] w-[18px] stroke-white/60" />
		Profile
	</RouterLink>
</DropdownMenuItem>
```

**Comment by zernonia** [comment]
Ahh thanks for catching that @MellKam ! Seems like I've missed out adding `as` and `asChild` props to the `MenuItem.vue`. Could you help create a PR for this? Should be quick and easy! 😁
