### ISSUE TITLE
[Bug]: Missing `as-child` Prop in `PopperArrow` 

### ISSUE THREAD

**Issue by onmax** [radix-vue/radix-vue#353]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/components/popover.html#arrow

### Steps to reproduce

Read below

### Describe the bug

The docs state that there is a `as-child` prop into the `PopoverArrow`, which uses `PopperArrow`. 

`PopperArrow` does not include `as-child`. See [source code](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Popper/PopperArrow.vue)

### Expected behavior

Have a prop in `PopperArrow`.

[Radix UI](https://www.radix-ui.com/primitives/docs/components/popover#arrow)

**Comment by zernonia** [comment]
Im sorry I didnt look at this closer previously.
We did already extends `PrimitiveProps`  in `PopperArrowProps`, so `PopoverArrow` should have `asChild` props already.

Please check again @onmax

**Comment by onmax** [comment]
Yes. The Prop definition has the prop in fact, but the I don't think is using that prop at all. Iread the code, and I didn't see where `as-child` is used. Maybe I missed it 🥲

Nonetheless, when I try to use it, I don't think is working. 

I placed a random SVG to see if I see something different to the `polygon` Radix uses, but I still see the radix. Here the playground:

https://codesandbox.io/p/sandbox/sq6yyd?file=%2Fsrc%2FApp.vue%3A1%2C1-36%2C1

Thanks for the help :)

**Comment by zernonia** [comment]
Yeah you are right @onmax ! There's a missing binding of props in `PopperArrow.vue` 😁
