### ISSUE TITLE
[Feature]: Do you plan to integrate command palette component

### ISSUE THREAD

**Issue by sultaniman** [radix-vue/radix-vue#357]
### Describe the feature

Hi,

Thanks for this work! I am wondering if you plan to integrate a command palette component for example one has [nuxtlabs/ui](https://ui.nuxtlabs.com/navigation/command-palette)?

Thanks.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
I have plan to imlpement [Combobox](https://github.com/radix-vue/radix-vue/issues/343). Think should be similar to that

**Comment by sultaniman** [comment]
@zernonia that's awesome, since the original component in `nuxtlabs/ui` seems to be implemented on top of it.
