### ISSUE TITLE
[Bug]: Click to open in DropdownMenu triggers click in the items

### ISSUE THREAD

**Issue by onmax** [radix-vue/radix-vue#366]
### Environment

```bash
All
```

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/radix-vue-dropdownmenu-forked-cwmzgk?file=%2Fsrc%2FApp.vue%3A329%2C8

### Steps to reproduce

Position the MenuContent on top of the trigger. In the reproduction link I provided you can see at the end I used:

```css
<style>
[data-radix-popper-content-wrapper] {
  translate: 0 -45px;
}
</style>
```

### Describe the bug

When you position the menu items on top of the trigger (a common pattern for dropdown with an icon as a trigger), the click used to open the menu also triggers the click in the items in the list.

### Expected behavior

Just open the menu

### Conext & Screenshots (if applicable)

https://gyazo.com/2a5c8ca621decf7722ec35a273ec754b

**Comment by zernonia** [comment]
the main issue is with `@pointerdown` with the Trigger component, related to this issue from [Radix UI](https://github.com/radix-ui/primitives/issues/2418).

Will change to use `@click` instead 😁


https://github.com/radix-vue/radix-vue/assets/59365435/01ca8076-9fcd-4acf-aa3c-179485983e26
