### ISSUE TITLE
[Feature]: Editable

### ISSUE THREAD

**Issue by dasmikko** [radix-vue/radix-vue#384]
### Describe the feature

https://ark-ui.com/docs/react/components/editable

This would be a nice addition.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
This is interesting. Any example showcasing how it works? It would provide a good reference for anyone taking this up 😁

**Comment by dasmikko** [comment]
Sure! Zagjs has a great example of the component. :)

https://zagjs.com/components/react/editable
