### ISSUE TITLE
[Bug]: Layout shift due to scrollbar removal

### ISSUE THREAD

**Issue by innocenzi** [radix-vue/radix-vue#385]
### Environment

```bash
Firefox: 117.0
Chrome: 116.0.5845.179
```

### Link to minimal reproduction

This can be seen on the docs.

https://www.radix-vue.com/components/context-menu.html

### Steps to reproduce

Open a component that removes the scrollbar.

### Describe the bug

Certain components, such as the Alert Dialog or the Context Menu, disable scrolling. Effectively, they remove the scrollbar from the body, which in turn causes a layout shift.

Example on Firefox:

https://github.com/radix-vue/radix-vue/assets/16060559/cc6d91d7-25f6-4ad8-8557-015895e303de

Example on Chrome:

https://github.com/radix-vue/radix-vue/assets/16060559/f0b9b51a-cefc-4a4c-a5f0-14821468ff85

### Expected behavior

The scrollbar can be removed, but there should not be any layout shift. 

For reference, Headless UI [adds a padding to the page](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/hooks/document-overflow/adjust-scrollbar-padding.ts) after removing the scrollbar to avoid this issue.

**Comment by zernonia** [comment]
@innocenzi  we are using padding. But it depends on how the website container was layout to center to elements. So I wouldn't say this is a bug, but some `docs` website improvement

**Comment by innocenzi** [comment]
Do you think it would be acceptable to provide an option to not disable the scrollbar to avoid situations where redoing the entire layout is not acceptable?

**Comment by innocenzi** [comment]
> Also, Im thinking of adding a props to prevent bodylock to some component.
That was what I was asking about. That would be great!

**Comment by ojvribeiro** [comment]
Applyig the right padding to `<html>` instead of `<body>` solves it _partially_, but it will still affect fixed positioned elements.

![fixing-cls](https://github.com/radix-vue/radix-vue/assets/8026741/dd5fd490-38a7-439e-b677-87f721f10737)

**Comment by ojvribeiro** [comment]
Deleted my previous comment since I realized it does not make any difference at all.

**Comment by nikuscs** [comment]
This a important one in my opinion, layout shift should not happen at any point

**Comment by zernonia** [comment]
Yup I acknowledge that layout shift is an important one. After looking at https://github.com/radix-ui/primitives/discussions/1586#discussioncomment-3302669, seems like it is super tricky to handle this as there's no universal solution to prevent scroll without shifting layout 😅  

As there's so many different approach in constructing the layout..  


My proposed solution:

1. we add a `ScrollBodyProvider`, which could be provided in `App.vue`
2. props for `ScrollBodyProvider`

```ts
// default: true
// `true` - enable bodyLock with default padding/margin settings  (see below)
// `false` - padding/margin will be 0. Thus not applying
enabled: boolean

// default: true
// `true` -  auto calculate the scrollbar width
// `false` - set padding to 0
// `number` - pixel for scrollbar width
padding: boolean | number

// default false
// `true` -  auto calculate the scrollbar width
// `false` - set margin to 0
// `number` - pixel for scrollbar width
margin: boolean | number 
```

3. it is (optional) to provide this provider, if none detected it will be default.
4. add a `--scrollbar-width` css variables. (User can based on this variables to styling padding for fixed elements)


I believe doing so would cater for all layout cases. Let me know what you guys think! 😁 
Feel free to provide suggestions ya!

**Comment by asiz15** [comment]
Any updates on this? :smile:
