### ISSUE TITLE
[Bug]: Teleport was anchor before element, thus `z-index: auto` would render element underneath other element 

### ISSUE THREAD

**Issue by benny-noumena** [radix-vue/radix-vue#387]
### Environment

```bash
Browser: All on OS X
```

### Link to minimal reproduction

https://www.radix-vue.com/

### Steps to reproduce

Got to the [website](https://www.radix-vue.com/) and check the popover.

### Describe the bug

The Z-Index for the popover is set to **auto** which overrides **z-index: 1000** of the popover. Therefore the popover is rendered below the container.

<img width="585" alt="image" src="https://github.com/radix-vue/radix-vue/assets/94522639/ca853e94-7ac5-4de1-bb37-ef0c6293afee">

**Comment by benny-noumena** [comment]
I tired all browser, Edge, Firefox, Chrome, Safari on OS X Monterey.

<img width="440" alt="image" src="https://github.com/radix-vue/radix-vue/assets/94522639/6945279a-fcc9-4c98-9363-aefe4b4367c1">

**Comment by zernonia** [comment]
Ahh I found the issue. Somehow the popper was teleported "before" the elements (especially after ssr). That should be a better fix. 

We dont need `[data-radix-popper-content-wrapper]` anymore as it was a fallback for previous implementation. 😁

**Comment by benny-noumena** [comment]
Great! Awesome work. Many thanks 👏

**Comment by Minglu-Huo** [comment]
I'm encountering the same issue with Chrome browser versions below 101, whether using Radix 1.9.17 or Reka.  Could you advise on how to resolve this？ @zernonia
