### ISSUE TITLE
[Bug]: Tooltip colliding with window border

### ISSUE THREAD

**Issue by onmax** [radix-vue/radix-vue#393]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/cw9ks8?file=%2Fsrc%2Fglobal.css

### Steps to reproduce

1. Put a tooltip next to a window border
2. Open the tooltip

### Describe the bug

Tooltip is colliding with window

In React they push the Tooltip to the left as you can see in the screenshot below

### Expected behavior

Just move the Tooltip content to the left in this case

### Conext & Screenshots (if applicable)

Currently in Vue
![image](https://github.com/radix-vue/radix-vue/assets/22072217/bf6e9c77-f7b8-4fc7-9998-94214e23ef32)

In React
![image](https://github.com/radix-vue/radix-vue/assets/22072217/679a968f-eed5-4fa8-9631-15e260dc862f)

**Comment by zernonia** [comment]
I think this should be easy. The `avoidCollisions` was set to false due to Vue automatically casting boolean to Boolean props.
Using the default popper content props in `TooltipContent` should fix it 😁
