### ISSUE TITLE
[Feature]: Detect hover events outside of dropdown menu/menu

### ISSUE THREAD

**Issue by Serpentarius13** [radix-vue/radix-vue#394]
### Describe the feature

Hey, thanks for the lib! I have a proposition for Dropdown menu functionality (or any other menu). Currently @interactOutside only works on click events (maybe some else, I dont know). Would be nice to see the same event, but for mouse out to detect it outside content+trigger, but not each separately

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
What do you mean "detect it outside content+trigger" ya?
You mean when *hovering* outside of menu and close it?

**Comment by zernonia** [comment]
@Serpentarius13  I believe you can do this with native `@mouseleave` event. Since no response for week, will close it as stale

**Comment by Serpentarius13** [comment]
@zernonia Sorry for not responding, got blown away by work :D I meant something like @mouseleave, but for entirity of select dropdown, i.e. when you hover out of trigger & menu. Right now the functionality works either with trigger or with menu, and when you get your mouse out of any of them, it fires
