### ISSUE TITLE
[Bug]: [Vue warn]: props default key "X" has no corresponding declaration

### ISSUE THREAD

**Issue by DamianGlowala** [radix-vue/radix-vue#397]
### Environment

```bash
Developement/Production OS: Windows 11
Node version: 16.20.1
Package manager: pnpm@8.7.0
Radix Vue version: 0.1.33
Nuxt version: 3.7.1
Nuxt mode: universal
Nuxt target: server
```

### Link to minimal reproduction

n/a

### Steps to reproduce

Receiving warnings when used as a Nuxt module on v0.1.33. If the error message is insufficient to find the cause of the issue, I will try to provide more information.

### Describe the bug

![image](https://github.com/radix-vue/radix-vue/assets/48835293/272802e1-1d41-45ba-9c0a-7b8a21ca2e7b)

**Comment by MellKam** [comment]
the same issue, but with vite spa

<img src="https://github.com/radix-vue/radix-vue/assets/51422045/b9d67280-0430-4a6a-8fc0-bd48018bd0d2" />

**Comment by MellKam** [comment]
I think it has to do with the spread of props in this commit. 6bef195af397f507b31f73f6abe0f06aedc57a1e

https://github.com/radix-vue/radix-vue/blob/69b336ddea1c847ff7a272ac178f02f918144671/packages/radix-vue/src/HoverCard/HoverCardContent.vue#L15-L17

https://github.com/radix-vue/radix-vue/blob/69b336ddea1c847ff7a272ac178f02f918144671/packages/radix-vue/src/Select/SelectContent.vue#L15-L19

**Comment by vesper8** [comment]
Same issue when using the sample dropdown from https://www.radix-vue.com/components/dropdown-menu.html

**Comment by zernonia** [comment]
Yup @MellKam . I didn't realize that if a props is not declare, it would throw warning when some default value was provided. Thanks guys for noticing!

**Comment by BayBreezy** [comment]
Just adding that now, the Select component is not rendering anything once you select a value. This is in Nuxt 3.7 with Radix-vue v0.1.33

**Comment by BayBreezy** [comment]
Ohhhh... I was wondering why it was working on the website and not in my library lol. Well, hopefully you come up with a fix soon :)

**Comment by zernonia** [comment]
Yeah breaking my head how to achieve it reliably 😂
