### ISSUE TITLE
[Feature]: Multiple/Stacking Dialogs

### ISSUE THREAD

**Issue by phppirate** [radix-vue/radix-vue#399]
### Describe the feature

Currently, when you have more than one dialog open and press the close button, everything works as expected. The Dialog with the close button will close, and the next dialog will stay open. But when pressing the `escape` key, both the dialogs will close.

I am unsure if this is better put as a Feature Request or a Bug, but here it is.

The Feature I am requesting is simply that when the escape key is pressed with multiple dialogs open only the topmost of the dialogs should close.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@phppirate  could you provide a minimal reproduction? Think seems like a bug 😁

**Comment by phppirate** [comment]
You know what, on attempting to reproduce the issue I realized I was mixing Headless UI Dialogs with Radix Vue Dialogs 🤦 , which obviously would not work. 

I rebuilt the feature with only the Radix Vue Dialog, and it is working as expected. Sorry about that. I will close this issue.

**Comment by zernonia** [comment]
No problem @phppirate ! Next time do provide a minimal reproduction if you encountered any issue yaa.. This will help you, and us maintainer to nail the problem quickly! Appreciate it! 😁
