### ISSUE TITLE
[Bug]: Popper closing animation not working

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#419]

**Comment by aethr** [comment]
I believe this issue has resurfaced, although I have only just started using this library, so it may be my own error. I have a component roughly like:

```vue
<template>
  <PopoverRoot>
    ...
    <PopoverPortal to="#teleports">
      <PopoverContent
        class="popover"
        :as="UiPanel"
        side="bottom"
        :side-offset="5"
        v-bind="$attrs"
      >
        <slot name="default" />

        <PopoverClose class="popover-close" aria-label="Close">x</PopoverClose>
        <PopoverArrow class="popover-arrow" />
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>

<style lang="scss">
@keyframes popIn {
  from {
    opacity: 0;
    transform: scale(0);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

.popover {
  --popover-padding: var(--spacing-s);

  z-index: 100;
  position: relative;
  padding: var(--popover-padding);
  transform-origin: var(--radix-popover-content-transform-origin);

  &[data-state="open"] {
    animation: popIn 0.2s ease;
  }
  &[data-state="closed"] {
    animation: popIn 0.2s ease reverse;
  }
}
// ... some styles excluded
</style>
```

The `&[data-state="open"]` animation works fine, but the `[data-state="closed"]` animation isn't being shown. It seems like the element is removed from the DOM immediately when the close button is clicked.

If necessary I could try and create a minimal reproduction somewhere.

Version:
```json
    "radix-vue": "^1.9.2",
```

**Comment by timmaier** [comment]
I also believe this issue has resurfaced. I implemented the Popover animation found at the docs here: https://www.radix-vue.com/components/popover.html#collision-aware-animations

The slideUp works but the slideOut does not it seems to derender immediately as @aethr has found.
