### ISSUE TITLE
[Feature]: Ability to transition `left` property on `<span>` wrapping `<SliderThumb>`

### ISSUE THREAD

**Issue by DamianGlowala** [radix-vue/radix-vue#422]
### Describe the feature

It would be great to be able to sprinkle a smooth transition both to the slider thumb (`left` property) and range (`right` property) whenever the slider's value changes programmatically.

As much as I can add styles to the range to achieve this, the `<span>` element wrapping the slider's thumb isn't accessible from the markup, hence why this issue exists :)

How it could possibly look like once transitions are added:

https://github.com/radix-vue/radix-vue/assets/48835293/3e1dc991-ce94-4b42-ae16-dd3f44a2e84f

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by DamianGlowala** [comment]
I certainly agree with you that applying a transition would require adding some logic to distinguish whether the slider is updated programmatically or by the user. Otherwise, it would cause a mess when dragging the thumb. Adding it would be completely opt-in and it would be up to the developer to take care of the concern you raised. This issue is purely about not being able to access all the markup that Radix Vue generates, and therefore not being able to transition a relevant CSS property.

Animating a thumb is as easy as adding e.g.:
```
transition: left 300ms ease;
```

I wonder whether the below `<span>` is needed as a wrapper? Could we merge these inline styles with the actual thumb? This way, it could easily solve the above issue :)

![image](https://github.com/radix-vue/radix-vue/assets/48835293/91ffbe3d-c264-4143-9170-251499e5881c)

**Comment by DamianGlowala** [comment]
@zernonia I am fairly confident that removing the wrapping `<span>` tag and moving these inline `transform` styles to the actual thumb component works 😄 We might not need it at all :)

**Comment by zernonia** [comment]
Yup. I dont see any downside of it.. and allow devs to directly apply classes they want.. 👍🏻
