### ISSUE TITLE
[Bug]: Checkbox disabled props does not work

### ISSUE THREAD

**Issue by mittalyashu** [radix-vue/radix-vue#424]
### Environment

```bash
Node version: v18
Package manager: pnpm@8.6.12
Radix Vue version: 0.3.2
Vue version: 3.3.4
```

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-pujuwx

### Steps to reproduce

1. Open the above link
2. Open dev tools
3. Click on the checkbox

### Describe the bug

The `CheckboxRoot` has `:disabled` props pass and the Checkbox is still intractable.

As you can see in the screenshot provided below.

### Expected behavior

The checkbox should not be intractable when it is disabled.

### Conext & Screenshots (if applicable)

![CleanShot 2023-09-27 at 12 56 43](https://github.com/radix-vue/radix-vue/assets/29014463/80c9efaa-fc21-4779-9c4a-61672c02d9f7)

**Comment by zernonia** [comment]
this is not a bug. The checkbox is not interactable. You are clicking another button that change the state of `v-model`

**Comment by mittalyashu** [comment]
I have even tried using a `localValue` to intercept the incoming value change.

```
const localValue = ref<boolean | 'indeterminate'>(false);

watch(
  () => props.modelValue,
  value => {
    if (props.disabled) return;
    localValue.value = value;
  },
);

onMounted(() => {
  localValue.value = props.modelValue;
});

function input(e: boolean) {
  if (props.disabled) return;
  emit('update:modelValue', e);
}
```

Even with that there seems to be some odd behaviour being shown in HTML and Vue Devtools.

In HTML, the checkbox shows the checked state on toggling even after disabling it.
but while checking the props state in Vue devtools, the value remains `false`.
