### ISSUE TITLE
[Bug]: `@floating-ui/*` dependencies is both added to bundle and installed in client's `node_modules`

### ISSUE THREAD

**Issue by floroz** [radix-vue/radix-vue#443]
### Environment

```bash
N/A
```

### Link to minimal reproduction

N/A

### Steps to reproduce

N/A

### Describe the bug

I was looking at the build setup of the library and I noticed that `@floating-ui/vue` and `@floating-ui/dom` [are shipped as `dependencies` in `package.json`](https://github.com/radix-vue/radix-vue/blob/a066730bf659d3a871fb50eb213e71d43ffb9c0b/packages/radix-vue/package.json#L47).

This means that when client are going to install `radix-vue` they will also install a copy of those two libraries in their `node_modules`.

At the same time, in the `vite.config.ts`,[ the only `build.rollupOptions.external` dependency declared is `vue`](https://github.com/radix-vue/radix-vue/blob/a066730bf659d3a871fb50eb213e71d43ffb9c0b/packages/radix-vue/vite.config.ts#L33).

This means, that the library also does bundle the functions from floating-ui directly into the `index.js`.

Is my understanding correct?

### Expected behavior

Either 

- declare `@floating-ui/*` to `external` to avoid bundling the references

or

- move `@floating-ui/*` from `dependencies` to `devDependencies` to avoid client to having to install it in their node_modules.

**Comment by sadeghbarati** [comment]
It could[1] or should be `dependencies` but it  must mark as external in vite.config 

Also `vue` and `@vueuse/core` should be in `peerDependencies`

since Vue support (simple) external types from `^3.3.0`


[1]: `floating-ui` also can be in peerDependencies too

**Comment by floroz** [comment]
> It could[1](#user-content-fn-1-225669535f5c749a229c43ec90e8603b) or should be `dependencies` but it must mark as external in vite.config
> 
> Also `vue` and `@vueuse/core` should be in `peerDependencies`
> 
> since Vue support (simple) external types from `^3.3.0`
> 
> ## Footnotes
> 1. `floating-ui` also can be in peerDependencies too [↩](#user-content-fnref-1-225669535f5c749a229c43ec90e8603b)

@sadeghbarati adding `@vueuse/core` to `peerDependencies` would have the trade-off of locking the end users to that version range (if `@vueuse/core` bumps their major, and clients want to upgrade, we would need to hope it doesn't break the existing API used by `radix-vue`).

I'm not too familiar with the release cadence of that package and the lifecycle of their major versions.

What do you think? 

My team is building a large component library and we're facing similar challenges and decisions, so we're trying to gain a broader perspective on some of the best practices around the `vue` ecosystem of third-party libraries.

**Comment by zernonia** [comment]
Hey @floroz ! We've included `@floating-ui` as a dependencies as many of our components depend on it, and we would like to stick with the targeted version to make sure `radix-vue`'s component work as expected.

You are right about setting `@floating-ui/vue`, `@floating-ui/dom` as external, and `output.globals`! It shouldn't be bundled into `index.js`.
