### ISSUE TITLE
[Bug]: ComboboxInput not focusing even after setting `auto-focus`

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#444]
Native html attribute `auto-focus` seems to be working inconsistently.. So let's change it to `js` approach

**Comment by Helios69** [comment]
I have exactly the opposite problem: the combobox is autofocused by default, and auto-focus="false" isn't working.
@zernonia

**Comment by XamzatJR** [comment]
Did you find any workarounds?
