### ISSUE TITLE
[Feature] Expose outside click event on DialogContent

### ISSUE THREAD

**Issue by mrcageman** [radix-vue/radix-vue#445]
### Describe the feature

Currently, the default behavior for clicking outside the DialogContent is to close the dialog. 

In some cases, however, one might want to prevent this behavior, e.g. when the contents inside the dialog have changed and we want to notify the user of unsaved changes before closing. 

The original radix-ui forwards the `onPointerDownOutside` and `onInteractionOutside` allowing for them to be overridden. 

Consider adding the same option for this project in order to align the APIs/features of both libraries. 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
DialogContent does support those behaviour by preventing the default closing action.

I see that the docs is missing this piece of info!

Can you try using the following code and let me know if it works! We definitely need to update the docs!

```ts
   <DialogContent
        @pointer-down-outside.prevent
        @interact-outside.prevent
        @escapeKeyDown="handleEvent"
      >
```


![image](https://github.com/radix-vue/radix-vue/assets/59365435/42b4ef3b-2a45-4bf9-8c7a-863abbbe9a58)

**Comment by mrcageman** [comment]
Awesome! It works as expected :) 

Thanks

**Comment by zernonia** [comment]
Glad to hear that! Thanks for reporting the issue! 😁
