### ISSUE TITLE
[Bug]: Two issues with GSelect: list goes out of view, resizeObserver issue

### ISSUE THREAD

**Issue by maelp** [radix-vue/radix-vue#451]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

None

### Steps to reproduce

I'm cross-linking an issue from shadcn-vue which is what I use https://github.com/radix-vue/shadcn-vue/issues/114

The idea is:

 - when a list of option is very long, it goes "out of the screen" and doesn't allow to scroll, thus some options are not available. Don't know if this is a radix-vue or a shadcn-vue issue, and what's the best way to handle this? Ideally with a resizeObserver and monitoring the size of the options
 - I wanted to have "custom items" in my Select, but when I have items of different height, but this cause an issue that I'll describe below:

So I'm using a dropdown list, where the items inside can have different height depending on the type.

To make it nicer, I'd like that once I selected the option, the selected item shows with the minimal possible height, so I'm using "h-auto" (otherwise I'd have to fix the height to the maximal one, like using "h-16" — when I do this it works without issue)

If I do this, then the item displays correctly, but when I change item **for a different height item** (the bug doesn't appear when I select another item of the same height), it triggers a "ResizeObserver loop completed with undelivered notifications." error

I guess it might be linked to that error ? https://github.com/radix-ui/primitives/issues/2313

### Describe the bug

Described above

**Comment by zernonia** [comment]
I dont understand the struggle here.
Why not just set a height to viewport? `<SelectViewport class="p-[5px] max-h-[500px] ">`.
Why not removing the set height for each item? 

https://codesandbox.io/p/sandbox/5rmrl7?file=src%2FApp.vue

**Comment by maelp** [comment]
I'll try to clarify:

- initially I didn't want to set any height on the viewport, because I figutred out this was the role of radix-vue, in order to choose the best height (for instance, if my list is higher than 500px and fits in screen, then I'd like it to be displayed in full)
- also setting a max-height won't prevent the list from going out of the screen (for instance if it's near the bottom of the screen)
- there is no "set height" for each item, it's just that each item in the list has different content, and thus different height (in my case: some items have a "subtitle" below which changes the height)

setting a max-h solves the issue, but still feels improper somehow, I guess that resizeObserver should not cause an issue even when the list has items with different heights

**Comment by romansp** [comment]
@maelp it's possible to constrain content height and width automatically as described in the docs [here](https://www.radix-vue.com/components/select.html#constrain-the-content-size). `floating-ui` computes available size and radix expose these as `--radix-popper-available-height` and `--radix-popper-available-width` CSS variables on the floating element. 

So you can use them these way with tailwindcss:

```vue
<SelectViewport
  class="overflow-auto max-h-[--radix-popper-available-height] max-w-[--radix-popper-available-width]"
>
```

Here's an updated sandbox: https://codesandbox.io/p/sandbox/radix-vue-hovercard-forked-h3j46j?file=%2Fsrc%2FApp.vue%3A53%2C47-53%2C78. 

Is that what you're trying to achieve?

**Comment by maelp** [comment]
Interesting thanks! So I solved my issue by doing this: removing the "popper" and set "replace item" (or I don't remember the other option name), and adding the "DropdownUpButton" and "DropdownDownButton" which are in the radix-vue example, but not in shadcn, and this was working

But I guess your solution is the correct one when we set popper. Shouldn't this be added by default to the styles of SelectViewport in the radix-vue example and in shadcn?

**Comment by maelp** [comment]
Does this also work with the Combobox from radix-vue and from shadcn? Perhaps we should also add this (I'd love to have similar DropdownUpButton and DropdownDownButton in the Combobox shadcn example for instance, would that be complicated to add?)

**Comment by sadeghbarati** [comment]
> Does this also work with the Combobox from radix-vue and from shadcn? Perhaps we should also add this (I'd love to have similar DropdownUpButton and DropdownDownButton in the Combobox shadcn example for instance, would that be complicated to add?)

Yes for sure

[**--radix-popper-available-width/height availability**](https://github.com/search?q=repo%3Aradix-vue%2Fradix-vue%20radix-popper-available-height&type=code)


- Combobox -> PopoverContent
- DropdownMenu -> DropdownMenuContent, DropdownMenuSubContent
- Select -> SelectContent

**Comment by maelp** [comment]
@sadeghbarati I tried to add this in the shadcn combobox example

```
    <PopoverContent
      class="w-[200px] p-0"
      style="max-height: --radix-combobox-content-available-height"
    >
```
or

```
    <PopoverContent
      class="w-[200px] p-0"
      style="max-height: --radix-popover-content-available-height"
    >
```


but it didn't work?

**Comment by maelp** [comment]
hmmmm forgot the "var(--radix-...)"

but if I do this, it seems it doesn't take into account the "search" field so it does that if I add the style to "CommandGroup"

<img width="227" alt="image" src="https://github.com/radix-vue/radix-vue/assets/15458/f99b3abc-28e0-4b8d-aa4b-76bac7f6b5dd">


(and if I add the style to "PopoverContent", it works but of course the "search field" scrolls with the rest instead of staying fixed

**Comment by maelp** [comment]
I did this trick which seems to work enough, this is my code for a kind of Combobox which allows both single-value select and multi-value select

```
<script setup lang="ts">
import {
  computed,
  withDefaults,
  defineProps,
  defineEmits,
  ref,
  watchEffect,
} from "vue";
import { Check, ChevronsUpDown } from "lucide-vue-next";
import {
  cn,
  Button,
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  Popover,
  PopoverContent,
  PopoverTrigger,
  type GComboboxOption,
} from "../index";
import { useVModel } from "@vueuse/core";

// The code is a bit complex because it allows for either a modelValue of string | undefined or a modelValue of string[] (if "multiple" is selected)

const props = withDefaults(
  defineProps<{
    options: GComboboxOption[];
    modelValue: undefined | string | string[];
    multiple?: boolean;
  }>(),
  { multiple: false }
);

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | string[]): void;
}>();

function isArrayOfString(value: any): value is string[] {
  return (
    Array.isArray(value) && value.every((item) => typeof item === "string")
  );
}

function isStringOrUndefined(value: any): value is string | undefined {
  return value === undefined || typeof value === "string";
}

const modelValue = useVModel(props, "modelValue", emits);
// We use an internalModelValue because the Command widget returns the whole `{value: string, title: string}` as value, and we wanted the outer component v-model to only contain the value, for practicality
const internalModelValue = ref<undefined | GComboboxOption | GComboboxOption[]>(
  undefined
);

const open = ref(false);

const findItem = (value: string) =>
  props.options.find((t) => t.value === value);

const filterFunction = (list: GComboboxOption[], query: string) => {
  return list.filter((i) =>
    i.title.toLowerCase().includes(query.toLowerCase())
  );
};

watchEffect(() => {
  if (props.multiple) {
    if (!isArrayOfString(props.modelValue)) {
      throw new Error("Expected modelValue to be a string[]");
    }
    internalModelValue.value = props.modelValue
      .map((t) => findItem(t))
      .filter((item) => item !== undefined) as GComboboxOption[];
  } else {
    if (!isStringOrUndefined(props.modelValue)) {
      throw new Error("Expected modelValue to be string | undefined");
    }
    internalModelValue.value =
      props.modelValue === undefined ? undefined : findItem(props.modelValue);
  }
});

const selectedValues = computed(() => {
  const emptyValue = "Select...";
  if (props.multiple) {
    let options = modelValue.value as string[];
    const titleOptions = options
      .map((t) => findItem(t)?.title)
      .filter((t) => t !== undefined);
    titleOptions.sort();
    return options.length > 0 ? titleOptions.join(", ") : emptyValue;
  } else {
    return modelValue.value !== undefined
      ? findItem(modelValue.value as string)?.title
      : emptyValue;
  }
});

const toggleValue = (item: string | object) => {
  open.value = false;
  const option = item as GComboboxOption;
  if (props.multiple) {
    if (!isArrayOfString(modelValue.value)) {
      throw new Error("Expected modelValue to be a string[]");
    }
    if (modelValue.value.includes(option.value)) {
      const idx = modelValue.value.indexOf(option.value);
      modelValue.value = [
        ...modelValue.value.slice(0, idx),
        ...modelValue.value.slice(idx + 1),
      ];
    } else {
      if (!Array.isArray(modelValue.value)) {
        throw new Error("Expected modelValue to be an array");
      }
      modelValue.value.push(option.value);
    }
  } else {
    if (!isStringOrUndefined(props.modelValue)) {
      throw new Error("Expected modelValue to be string | undefined");
    }
    modelValue.value = option.value;
  }
};
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        variant="outline"
        role="combobox"
        :aria-expanded="open"
        class="w-[200px] flex justify-between"
      >
        <div class="overflow-hidden whitespace-nowrap overflow-ellipsis">
          {{ selectedValues }}
        </div>
        <ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
      </Button>
    </PopoverTrigger>
    <PopoverContent class="w-[200px] p-0">
      <Command
        v-model="internalModelValue"
        :filter-function="filterFunction"
        :multiple="props.multiple"
      >
        <CommandInput placeholder="Search..." />
        <div>
          <slot name="before"></slot>
        </div>
        <CommandEmpty>No item found.</CommandEmpty>
        <!-- the 0.85 * max-height is kind of a hack, otherwise either I have to add the scroll to the PopoverContent, but then the CommandInput also scrolls, or it doesn't show some of the items -->
        <CommandGroup
          class="overflow-y-scroll"
          style="max-height: calc(0.85 * var(--radix-popper-available-height))"
        >
          <CommandItem
            v-for="option in options"
            :key="option.value"
            :value="option"
            @select="toggleValue"
          >
            <Check
              :class="
                cn(
                  'mr-2 h-4 w-4',
                  (
                    props.multiple
                      ? modelValue?.includes(option.value)
                      : modelValue === option.value
                  )
                    ? 'opacity-100'
                    : 'opacity-0'
                )
              "
            />
            {{ option.title }}
          </CommandItem>
        </CommandGroup>
      </Command>
    </PopoverContent>
  </Popover>
</template>
```

**Comment by zernonia** [comment]
@maelp  I really want to help but could you use the Stackblitz link to create reproduction instead of just sending the code here. If not.. I will have to close this ticket

**Comment by maelp** [comment]
Hey sorry about that, I guess I updated some dependencies to the latest radix version and now it seems to work as expected, closing the issue
