### ISSUE TITLE
[Bug]: Dropdown menu inside of dialog modal closes the modal instead of opening the dropdown

### ISSUE THREAD

**Issue by vesper8** [radix-vue/radix-vue#457]
### Environment

```bash
Vue 3,Vite 4
```

### Link to minimal reproduction

---

### Steps to reproduce

I suppose this is to do with both components using the DialogRoot?

If you place (or nest) a https://www.radix-vue.com/components/dropdown-menu.html inside of a https://www.radix-vue.com/components/dialog.html then it ends up closing the dialog instead of showing the dropdown menu

### Describe the bug

See above

**Comment by vesper8** [comment]
The same thing happens if you place a https://www.radix-vue.com/components/select.html inside of a https://www.radix-vue.com/components/dialog.html

**Comment by zernonia** [comment]
could you create a minimal reproduction? Yes it is self-explanatory but it will help us setup much quicker and nailed the issue accurately.

**Comment by zernonia** [comment]
@vesper8  can you recreate it? I've just check both case "DropdownMenu in Dialog", "Select in Dialog", all seems to work fine.

**Comment by zernonia** [comment]
@vesper8  any update on this? Else will be closed 😁
