### ISSUE TITLE
[Bug]: Cannot import and use `RadixVueResolver` as per documentation instructions

### ISSUE THREAD

**Issue by Bobakanoosh** [radix-vue/radix-vue#477]
### Environment

```bash
Developement/Production OS: None
Node version: 18.2.1
Package manager: pnpm@8.9.0
Radix Vue version: 1.0.2
Vue version: 3.3.4
CSS framework: None
Client OS: Windows 11 Pro 64-Bit (10.0, Build 22621)
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/vue3-vite-typescript-starter-edvjlj?file=vite.config.ts

### Steps to reproduce

1. Try to run `pnpm dev`
2. You will see an error in the console 
```
Package subpath './resolver' is not defined by "exports" in /home/projects/vue3-vite-typescript-starter-edvjlj/node_modules/radix-vue/package.json
```

### Describe the bug

This is actually a different error than I get locally, but still happens at the same time. I cannot use the unplugin-vue-component resolver on a fresh vite project.

I get this error locally:
```
ERROR: [plugin: externalize-deps] Failed to resolve "radix-vue/resolver". This package is ESM only but it was tried to load by 'require'. See http://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
```

**Comment by enkot** [comment]
@zernonia This problem still exists and can be reproduced by the link in the description.
