### ISSUE TITLE
[Bug]: `as` props showing  Typescript error when passing a Component

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#483]
Typescript shouldn't show error as `as` props do accept **Component**.

![image](https://github.com/radix-vue/radix-vue/assets/59365435/2213c457-854b-45ab-8d11-96d86a4b3c0e)

**Comment by MellKam** [comment]
Is this what you want to achive?

```vue
<template>
	<UiDropdownItem as-child>
		<NuxtLink href="/app/profile">Profile</UiDropdownItem>
	</UiDropdownItem>
</template>
```

Or do you want to add the ability to pass a component directly to the "as" props? If so, then I think it's better to rename this issue to feature request (not a bug).

**Comment by zernonia** [comment]
@MellKam  the `as` prop is already accepting Component.. just the "type" for it is incorrect.
Yes using `asChild` works.. 😁
