### ISSUE TITLE
[Bug]: Floating UI elements x-axis overflow on mobile

### ISSUE THREAD

**Issue by ChrisGV04** [radix-vue/radix-vue#485]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/components/menubar.html

### Steps to reproduce

View the docs in a small screen size and open the last menu trigger that says "Profiles"

### Describe the bug

The menu dropdown that opens after clicking the menu item overflows the screen on the right side.

### Expected behavior

I'm not sure if this only happens in the docs website or if it would happen in any app that uses Radix Vue. However, I know that floating UI has the `flip()` middleware to fix this issue.

I would expect that the dropdown renders from the right side to the left so that everything stays inside the screen. This behavior should happen on every component that works as a floating window.

Edit: I just discovered Radix Vue (it's amazing btw) so I haven't used it in any project. That's why I don't know if this issue only happens on the docs website and if it can be fixed on other apps with the `data-side` and `data-align` properties.

### Conext & Screenshots (if applicable)

![Screen Shot 2023-10-31 at 22 08 55](https://github.com/radix-vue/radix-vue/assets/47041342/36da7d3a-bbff-405e-ab5e-d9e280a8dfac)

**Comment by zernonia** [comment]
Thanks for the issue @ChrisGV04 . Yeah it should `avoidCollisions` but the props was not forwarded correctly. Will push this fix ASAP 😁

**Comment by ChrisGV04** [comment]
Hi @zernonia! That's great.
Then was it an issue specific to the `Menubar` component only, or was it also happening on other floating ui components as well?

**Comment by zernonia** [comment]
It happens for `DropdownMenu` as well. Essentially the base component `Menu` not forwarding correct props 😁
