### ISSUE TITLE
[Bug]: PrimitiveProps is not exported from `radix-vue`

### ISSUE THREAD

**Issue by BayBreezy** [radix-vue/radix-vue#511]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 18.x
Package manager: npm
Radix Vue version: 1.1.2
Vue version: 3.3.8
Nuxt version: 3.8.1
Nuxt mode: universal
Nuxt target: server
CSS framework: none
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

N/A

### Steps to reproduce

- Create a new Nuxt 3 project
- Install Radix-Vue
- Try importing `PrimitiveProps` from radix-vue like so `import { type PrimitiveProps } from "radix-vue";`
You will get the error:
`Module '"radix-vue"' has no exported member 'PrimitiveProps'`

It has to be imported like so for now:
`import { type PrimitiveProps } from "radix-vue/dist/Primitive/Primitive";`

### Describe the bug

The `PrimitiveProps` type cannot be imported from the default package.

### Expected behavior

I expect to be able to import the `PrimitiveProps` type from 'radix-vue'

### Conext & Screenshots (if applicable)

<img width="650" alt="image" src="https://github.com/radix-vue/radix-vue/assets/53905713/7ed9902a-0aea-469f-afdb-131a28a7a4f2">

**Comment by zernonia** [comment]
Yeah forgot to export prop type for "Utilities" component. The fix for this is simple and straightforward 😉

**Comment by BayBreezy** [comment]
Thank you! I was not sure how to fix it, so i didn't do the PR. I looked at what you did. Thanks
