### ISSUE TITLE
[Bug]: Closing & Opening Dialog in quick succession causing Scroll issue

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#512]
### Environment

```bash
Radix Vue version: 1.1.2
```

### Link to minimal reproduction

https://stackblitz.com/edit/kgeztv?file=package.json

### Steps to reproduce

Click the 'button'

### Describe the bug

Observe the body is lock and no longer scrollable

### Expected behavior

The document body should be scrollable still

**Comment by maelp** [comment]
👍
