### ISSUE TITLE
[Bug]: dialog breaks focus flow if something is rendered on input change

### ISSUE THREAD

**Issue by enkot** [radix-vue/radix-vue#518]
### Environment

```bash
Radix Vue version: 1.1.3
```

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/radix-vue-select-forked-y4j783?file=/src/App.vue:28,38

### Steps to reproduce

1. Open dialog
2. Type something in the input
3. Press `Tab`
4. Dialog content is focused

### Describe the bug

I have an input and icon after it that should be shown on input change. 
If you type something in the input and want to focus the next input by pressing `Tab` - the focus switches to the dialog content but not input.

### Expected behavior

Next input should be focused when you press `Tab`.

**Comment by enkot** [comment]
It happens here:

**Comment by zernonia** [comment]
Thanks for the issue @enkot ! Yeah the `MutationObserver` is the culprit here. I will look into this, and see if I can find a proper solution for this 😁

**Comment by enkot** [comment]
@zernonia Thanks for the quick feedback and fix 💪

**Comment by zernonia** [comment]
No problem @enkot ! thanks for logging the issue! Truly appreciate it!! ❤️
