### ISSUE TITLE
[Bug]: HoverCard - Nuxt - Hydration children mismatch

### ISSUE THREAD

**Issue by damienroche** [radix-vue/radix-vue#521]
### Environment

```bash
Developement/Production OS: Mac Ventura 13.5.2
Node version: 20.9.0
Package manager: pnpm@8.10.5
Radix Vue version: 1.0.2
Nuxt version: 3.8.0
Nuxt mode: universal
Nuxt target: server
CSS framework: @nuxt/tailwindcss@6.8.1
Client OS: Mac Ventura 13.5.2
Browser: Chrome 119.0.6045.123
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-3-6c1nuk?file=pages%2Findex.vue

### Steps to reproduce

Add HoverCard component with nuxt or
check stackblitz reproduction link and run `pnpm i && pnpm dev`

### Describe the bug

When I use HoverCard component with nuxt,
I have the following rendering issue :

<img width="623" alt="Capture d’écran 2023-11-17 à 10 26 58" src="https://github.com/radix-vue/radix-vue/assets/1529058/e96dc93c-02ac-4f24-ae40-111653b6de12">

And the [trigger appears twice after page is loaded](https://capture.dropbox.com/LAFGqy4ebMQ2dOR5) :
<img width="576" alt="Capture d’écran 2023-11-17 à 10 43 33" src="https://github.com/radix-vue/radix-vue/assets/1529058/5d759bc3-08c8-47fb-b0b7-ee161960de61">

**Comment by damienroche** [comment]
fixed by setting `asChild: true` to Trigger component.

**Comment by zernonia** [comment]
Hey @damienroche . The reprodution link is not showing the case you are describing above.

Also note:
If you have `<a>` nested inside another `<a>`, it will throw hydration issue (This is expected). So you should set `asChild: true`.
