### ISSUE TITLE
[Bug]: Dialog component doesn't set "overflow: hidden" and other necessary styles when used in Astro island

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#524]
### Environment

```bash
Node version: 20.9.0
Package manager: pnpm@8.10.5
Radix Vue version: 1.1.3
Vue version: 3.3.8
```

### Link to minimal reproduction

https://codesandbox.io/p/github/MellKam/astro-radix-vue-bug/main

### Steps to reproduce

https://github.com/MellKam/astro-radix-vue-bug

### Describe the bug

Dialog should set overflow hidden when it is open and `modal` property on DialogRoot is `true`, but it is not. 

Here is the body style property when the dialog is open on the radix-vue.com:

`padding-right: 14px; margin-right: 0px; --scrollbar-width: 14px; overflow: hidden; pointer-events: none;`

And here's what it looks like in Astro:

`pointer-events: none;`

**Comment by zernonia** [comment]
Thanks @MellKam ! Not sure how does Astro island works exactly. Might be related to `isClient` being return as `false` in `useBodyScrollLock`.

**Comment by MellKam** [comment]
@zernonia Oh, that's something new to me. For some reason I thought that this didn't require an overlay. Thank you for your help!

**Comment by codiini** [comment]
@zernonia Is there a way to remove the padding applied while keeping <DialogOverlay>?

Here's a minimum code example

```
  <DialogRoot v-model:open="open" class="relative z-50">
    <DialogPortal>
      <DialogOverlay class="fixed inset-none z-50" />
      <DialogContent
        class="fixed right-none top-none z-50 flex h-full flex-col"
      >
        <DialogTitle>
          <slot name="header" />

          <DialogClose
            :aria-label="ariaLabelClose"
            class="absolute right-sm top-sm"
          >
            <span aria-hidden>
              <IconClose class="icon-md" />
            </span>
          </DialogClose>
        </DialogTitle>

        <main class="grow p-sm">
          <slot name="content" />
        </main>

        <footer
          class="sticky bottom-none z-20 border-t border-neutral-light bg-white p-sm"
        >
          <slot name="footer-sticky" />
        </footer>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
```
