### ISSUE TITLE
[Bug]: Multiple (Dropdown) Submenus after another don't work properly and stack visually

### ISSUE THREAD

**Issue by spaceemotion** [radix-vue/radix-vue#526]
### Environment

```bash
Developement/Production OS: Linux WSL 2
Node version: 20.2.0
Package manager: pnpm@8.9.2
Radix Vue version: 1.1.2
Vue version: 3.3.8
Nuxt version: -
Nuxt mode: -
Nuxt target: -
CSS framework: tailwindcss@3.3.5
Client OS: Windows 10 19045.3693
Browser: Edge 119.0.2151.72
```

### Link to minimal reproduction

https://stackblitz.com/edit/qibher?file=src%2FApp.vue

### Steps to reproduce

1. Create a Menu with multiple Submenus after another.
2. Move with the mouse in a fast movement over the elements, slowly moving towards the right.
3. All menu items are getting triggered as they are within the "clipping path"

### Describe the bug

Due to the Triangle-Clip-Path the submenu should stay open the closer the mouse gets to the content rect. there is an error in that logic though, as it doesn't seem to stop additional sub menu triggers from picking it up too. I guess something needs to be canceled?

### Expected behavior

Only the first submenu should be open as long as i was within the clip path.

### Conext & Screenshots (if applicable)

![image](https://github.com/radix-vue/radix-vue/assets/429147/e68ddddf-2761-4fb3-9a2b-26ae7a1fb0e5)

**Comment by spaceemotion** [comment]
@zernonia i think there is still an issue with this:

![image](https://github.com/radix-vue/radix-vue/assets/429147/0a709cd5-c070-4980-98c2-0778ed03f988)

As long as the focus is inside the window, the menu works fine. But when you hover over the menu while the current tab is not in focus, the new fix breaks.

One of my blind users also says that they're now no longer able to see the nested menus through their screen reader, whereas they previously were able to do so.

**Comment by zernonia** [comment]
@spaceemotion  can you record a video how the stacking issue still breaking? I've tested with your steps here and cant reproduce it.

As for the accessibility issue.. can you help create another ticket with relevant information? 😁
