### ISSUE TITLE
[Feature]: Autocomplete

### ISSUE THREAD

**Issue by asiz15** [radix-vue/radix-vue#537]
### Describe the feature

Thanks for your work!. I think a very useful component could be an Autocomplete.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by asiz15** [comment]
@zernonia Thanks for your reply and sorry for the delay. 
You are right, the combobox component is enough. I am creating a custom component based on the combobox. I need to emit a custom on enter keypress for the input. Currently if there are suggestions, this selects the highlighted element. How can I prevent this behavior? Can you point me in the right direction ? 

Thanks!

**Comment by romansp** [comment]
@asiz15 It's possible to prevent default select behavior by calling `event.preventDefault()` for `@select` event on `ComboboxItem`. [Here's an example in the docs](https://www.radix-vue.com/components/combobox.html#prevent-select-behavior).
