### ISSUE TITLE
[Bug]: DialogContent within DialogOverlay is removed from the accessibility tree

### ISSUE THREAD

**Issue by hoonweiting** [radix-vue/radix-vue#538]
### Environment

```bash
Developement/Production OS: macOS 11.6.2
Node version: (whatever Stackblitz uses)
Package manager: (whatever Stackblitz uses)
Radix Vue version: 1.2.2
Vue version: latest
Nuxt version: -
Nuxt mode: -
Nuxt target: -
CSS framework: -
Client OS: macOS 11.6.2
Browser: Chrome 119.0.6045.159
```

### Link to minimal reproduction

https://stackblitz.com/edit/7vppeo?file=src%2FApp.vue

### Steps to reproduce

1. Set up a Dialog, with DialogContent nested in a DialogOverlay

### Describe the bug

The DialogOverlay has `aria-hidden="true"` set, which means its descendants are removed from the accessibility tree and are not exposed to assistive technologies.

### Expected behavior

The content in DialogContent is exposed to assistive technologies, when the author chooses to nest DialogContent within DialogOverlay.

### Conext & Screenshots (if applicable)

It is an example given in the docs, so I would expect it to work. (Alternatively, we can prohibit nesting DialogContent within a DialogOverlay, and remove the example from the docs, although I don't feel too enthusiastic about that 😅)

<img width="396" alt="image" src="https://github.com/radix-vue/radix-vue/assets/59229084/f573299f-88af-4a11-8c30-78eba90713c8">

By the way, thank you for this library!

**Comment by hoonweiting** [comment]
Thank you @zernonia for addressing this so quickly!

**Comment by zernonia** [comment]
You're welcome @hoonweiting ! Thanks for logging the issue! 💚
