### ISSUE TITLE
[Bug]: Dialog adds `pointer-events: none` when using `force-mount` and `v-show`

### ISSUE THREAD

**Issue by enkot** [radix-vue/radix-vue#539]
### Environment

```bash
Node version: 16.17.0
Package manager: yarn@1.22.19
Radix Vue version: 1.2.3
Vue version: 3.3.4
Browser: Chrome 118.0.5993.88 (Official Build) (arm64)
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-select-forked-wlfxvx?file=%2Fsrc%2FApp.vue%3A16%2C22

### Steps to reproduce

Check the body style, it has `pointer-events: none`, but the dialog is closed.

### Describe the bug

I need to display the dialog using v-show (so that the contents of the dialog are in SSR), but currently it adds `pointer-events: none` to the body when the dialog is closed when using `force-mount` in `<dialog-content>` with `v-show`.
Works fine when using `v-if`.

### Expected behavior

Shoudn't add any styles to the body on init when dialog is closed.

**Comment by zernonia** [comment]
Hey @enkot . I believe this can be solve by my comment here. 😁

https://github.com/radix-vue/radix-vue/issues/688#issuecomment-1951951927
