### ISSUE TITLE
[Bug]: DialogClose overrides accessible name given by child content

### ISSUE THREAD

**Issue by hoonweiting** [radix-vue/radix-vue#541]
### Environment

```bash
Developement/Production OS: macOS 11.6.2
Node version: (whatever Stackblitz uses)
Package manager: (whatever Stackblitz uses)
Radix Vue version: 1.2.3
Vue version: latest
Nuxt version: -
Nuxt mode: -
Nuxt target: -
CSS framework: -
Client OS: macOS 11.6.2
Browser: Chrome 119.0.6045.159
```

### Link to minimal reproduction

https://www.radix-vue.com/components/dialog.html

### Steps to reproduce

1. Use DialogClose to wrap any button that closes the modal, whether `as-child` or `<MyCustomButton :as="DialogClose">`

### Describe the bug

The resulting HTML is `<button aria-label="Close" ...>{{ the button's content }}</button>`.

This means that the button's accessible name is overridden by the `aria-label="Close"`, and "Close" will be what is announced by screen readers, for example.

### Expected behavior

I'm not really sure what the best solution is. Personally, I interpret DialogClose as the preferred way of closing a Radix Vue Dialog. It doesn't necessarily have to be a "Close" button, it could be a "Cancel" or an "Okay" button (which otherwise behave the same as a "Close" button). I would like to be able to use DialogClose in such cases too, instead of needing to manually control the state myself.

Maybe it should be the consumer's responsibility to give the 'Close' button an accessible name, like in Radix UI?

### Conext & Screenshots (if applicable)

It's also a problem for AlertDialogAction and AlertDialogCancel.

**Comment by hoonweiting** [comment]
Here's a Stackblitz: https://stackblitz.com/edit/tcw2rz?file=src%2FApp.vue

Sorry, I'm not sure how to best get my message across in a repro, it's essentially the same as the example in the docs, so I removed the unimportant content and added some comments 😅 

<img width="368" alt="image" src="https://github.com/radix-vue/radix-vue/assets/59229084/8f8dab8d-aaad-47a3-ace8-2d6920e4efb6">

What I want to get at is that when I write:

```vue
<template>
  ...
    <DialogClose as-child>
      <button type="button"> My button </button>
    </DialogClose>
  ...
</template>
```

I expect the resulting HTML:

```html
<button type="button"> My button </button>
```

Which screen readers would announce as "My button".

Instead, this is the resulting HTML:

```html
<button type="button" aria-label="Close"> My button </button>
```

And screen readers announce it as "Close" instead of "My button", which is problematic because the phrase announced by the screen reader doesn't match or contain the button's visual label. This means that screen reader users are misled as to what button actually does.

---

Maybe I can bring up this line:

https://github.com/radix-vue/radix-vue/blob/523c323b517bcb7010646cd8980a78cd87d797b7/packages/radix-vue/src/Dialog/DialogClose.vue#L22

I believe it enforces `aria-label="Close"` on DialogClose. This makes sense if the DialogClose is used as a "Close" button, but it does not make sense in all other cases, such as when the button has a visual label of "Cancel", or if the web page/app is in a language other than English.

---

Personally, I don't know what the best solution is.

I think it should be the user's responsibility to give 'x' buttons an accessible name. I think this is preferable for i18n considerations too.

If not, the docs need to better explain how a user is supposed to close a Dialog if they don't want `aria-label="Close"`.

**Comment by sadeghbarati** [comment]
just a proposal

Adding boolean `accessible` prop to Primitive component to filter out `aria-*` attributes,

with `accessible`: **false** prop, it's user duty to provide the accessibility to the component


---

@hoonweiting 

Another way is to remove `aria-label="Close"` is to add `:aria-label="null"` to the `DialogClose.vue` component

**Comment by zernonia** [comment]
I see your use case now @hoonweiting . I have 3 solution for you.

1. set aria-label to `null` or `undefined` (easy)
```vue
<DialogClose as-child>
    <button type="button"  :aria-label="undefined">My button</button>
</DialogClose>
```


2.  set your own `aria-label` (easy)
```vue
<DialogClose as-child>
    <button  aria-label="My button">My button</button>
</DialogClose>
```


3. close the modal programmatically using your own button (medium)
assume your have `v-model:open="open"`
```html
 <button  type="button" @click="open = false">My button</button>
```


I believe this is what you need right? If so we can "close" this issue 😁

**Comment by hoonweiting** [comment]
@zernonia I suppose so, but I would rather not need to set `aria-label` at all. I suppose I expect DialogClose to close the modal, without imposing any specific label. This is what PopoverClose and ToastClose do, they don't impose `aria-label="Close"`.

If we would still like to continue imposing `aria-label="Close"` in DialogClose, then perhaps we can update the docs to better inform users that they'll need to (un)set `aria-label` themselves?

**Comment by zernonia** [comment]
Your comment on PopoverClose/ToastClose made me wonder why the aria-label was set in `DialogClose`. Then I check the original design from [Radix UI](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L473-L484) and realise it doesn't impose the `aria-label`!

Let's remove it then in our source code. @hoonweiting  do you want to help contribute to this changes? 😁

**Comment by hoonweiting** [comment]
@zernonia Sure, that sounds good! I'll make a PR when I get some time today.

**Comment by zernonia** [comment]
Appreciate it @hoonweiting ! 🙌🏼
