### ISSUE TITLE
[Bug]: displayValue prop on combobox does nothing

### ISSUE THREAD

**Issue by dasmikko** [radix-vue/radix-vue#545]
### Environment

```bash
Developement/Production OS: Oracle linux 9
Node version: 20.10.0
Package manager: npm@10.2.3
Radix Vue version: 1.2.3
Vue version: 3.3.4
CSS framework: tailwindcss@3.3.5
Client OS: Oracle Linux 9
Browser: Chrome latest
```

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-bmgfe9?file=src%2FApp.vue

### Steps to reproduce

Use the combobox. The displayValue method is never called

### Describe the bug

The prop displayValue isn't doing anything

### Expected behavior

Method to be called, and use the returned value

**Comment by zernonia** [comment]
Thanks for the issue! the `displayValue` current only trigger if the `modelValue` is an object. But now that I think about it it could be any type.
