### ISSUE TITLE
[Bug]: modelValue elements in `PinInput` are being mutated directly

### ISSUE THREAD

**Issue by Scalamando** [radix-vue/radix-vue#549]
### Environment

```bash
Developement/Production OS: Windows 10 19045.3693
Node version: 20.10.0
Package manager: pnpm@8.11.0
Radix Vue version: 1.2.4
Vue version: 3.3.10
CSS framework: tailwindcss@3.3.5
Client OS: Windows 10 19045.3693
Browser: Edge 119.0.2151.97, Firefox 120.0.1
```

### Link to minimal reproduction

https://stackblitz.com/edit/3bjcu7?file=src%2FApp.vue

### Steps to reproduce

1. Instantiate a `ref<string[]>`
2. Associate the created ref with a PinInputRoot using the `:model-value` prop.
3. Observe that the ref is modified directly, even in the absence of an `@update:model-value` handler.

### Describe the bug

The individual elements of the `model-value` prop in a PinInputRoot component are [directly mutated](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/PinInput/PinInputInput.vue#L36). Consequently, this results in the corresponding ref being updated even when no `@update:model-value` handler is used.

I will create a PR for this shortly.

### Expected behavior

If no `@update:model-value` handler is provided, the ref assigned to the `model-value` prop of a PinInputRoot should remain unaltered.

**Comment by zernonia** [comment]
That make sense! Thanks for the issue and the PR @Scalamando !
