### ISSUE TITLE
[Bug]:  If the number of ComboboxItems exceeds 100, open it and you'll get a warning from vue.

### ISSUE THREAD

**Issue by l1m2e** [radix-vue/radix-vue#551]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-combobox-forked-d345xm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpwvtz8g00073j6gm52gw92k%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpwvtz8f00023j6gq24j98k0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpwvtz8f00043j6geyoo0aci%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpwvtz8g00063j6g6wthby0j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B71.3319014371117%252C28.668098562888304%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpwvtz8f00023j6gq24j98k0%2522%253A%257B%2522id%2522%253A%2522clpwvtz8f00023j6gq24j98k0%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpwvtz8g00063j6g6wthby0j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpwvtz8g00053j6g95xn1ua5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpwvtz8g00063j6g6wthby0j%2522%252C%2522activeTabId%2522%253A%2522clpwvtz8g00053j6g95xn1ua5%2522%257D%252C%2522clpwvtz8f00043j6geyoo0aci%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpwvtz8f00033j6g1zmchvxf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clpwvtz8f00043j6geyoo0aci%2522%252C%2522activeTabId%2522%253A%2522clpwvtz8f00033j6g1zmchvxf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

open combobox 

### Describe the bug

[Vue warn]: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

**Comment by Melchyore** [comment]
Hello, I have the same problem.

**Comment by oaleynik** [comment]
Temporary workaround would be to not use ComboboxViewport. Here is a good example of such abstraction: https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/command/CommandList.vue

**Comment by zernonia** [comment]
I will look into this soon. Together with integrating possible Virtual list packages

**Comment by kristofferdamborg** [comment]
> I will look into this soon. Together with integrating possible Virtual list packages

@zernonia You're a star! 🌟

**Comment by oaleynik** [comment]
> > Temporary workaround would be to not use ComboboxViewport. Here is a good example of such abstraction: https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/ui/command/CommandList.vue
> 
> 
> 
> Hi @oaleynik
> 
> 
> 
> Do you care to explain how your workaround works? The link your sending, is a copy of the current CommandList in shadcn.

That's correct - that's what I found in shadcn - CommandList uses Combobox without ComboboxViewport. Without viewport component I didn't see the error anymore.

**Comment by Philistino** [comment]
Love the idea of virtualization here! I want to use this component as a facet filter for a data table and it is currently too slow with the number of values I need to show.  I appreciate all you are doing with radix-vue and shadcn-vue!

**Comment by JarvisH** [comment]
Any new developments? Am having to same issue with recursive warning. In addition performance is very slow when rendering the list using an array of objects:

```
<ComboboxItem
          v-for="(option, index) in options"
          :key="index"
          :value="option" <-- if option is a string or number, it is fast. When an object it is slow.
        >
```

**Comment by Flowko** [comment]
@zernonia since listbox dev is done, do we need to change something to opt in to the new component ?

**Comment by cyyynthia** [comment]
It appears there's been a regression in 1.8.4 and I'm encountering this again. Works just fine in 1.8.3.

**Comment by timmaier** [comment]
We're also experiencing slowness when opening with 150+ set of items.

**Comment by kristofferdamborg** [comment]
I don't really see how you would implement the new ListBox (https://github.com/radix-vue/radix-vue/pull/766) with ComboBox to fix this issue. Does anyone have a solution for this?
