### ISSUE TITLE
[Bug]: ComboboxPortal does not work properly. The Content is placed at the bottom

### ISSUE THREAD

**Issue by Helios69** [radix-vue/radix-vue#552]
### Environment

```bash
Developement/Production OS: MacOS
Node version: 18.18.1
Package manager: yarn
Radix Vue version: 1.2.3
Vue version: 3.3.4
CSS framework: tailwindcss@3.3.3
Client OS: MacOS
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/13gqeb?file=src%2FApp.vue

### Steps to reproduce

Just copy/paste the Combobox with Portal example from docs. It does not work properly.

### Describe the bug

 ComboboxPortal does not work properly. The Content is placed at the bottom of the page, not relative to the parent.

### Expected behavior

The content should be placed right after the combobox input.

**Comment by romansp** [comment]
@Helios69 All of radix-vue `Portal` components will portal the content part into the `body` by default. It's often required to ensure that content is rendered properly on top and to avoid z-index trickery. But `Portal` components are optional to use.

If you don't need this behavior and want to place the content right after the combobox input then remove `ComboboxPortal` entirely.

**Comment by Helios69** [comment]
@romansp no, i want to use the portal. Just look at how the Popover with Portal works. The popover is rendered properly, but also outside of the root app. No need to manually adjust the styles, play with the references to the body element and so on. Taking into consideration that popover also uses portal, and it works, i think the combobox portal has a bug.

**Comment by zernonia** [comment]
Sorry for the confusion here @Helios69 .

The docs doesn't reflect clearly the usage or `Portal` in `Combobox`. Essentially Portal would only be auto position if we enabled `popper` position in `ComboboxContent`.

You can check out this [example](https://stackblitz.com/edit/vq5tt5?file=src%2FApp.vue).

I will also update the docs to clearly indicate this confusion.
https://github.com/radix-vue/radix-vue/commit/7db3c89b8106fad5168fcba943ffd5bee920a5af

Hope this helps! 😁

**Comment by Helios69** [comment]
@zernonia Thanks! Much clearer now.

**Comment by Helios69** [comment]
Upd: It works with position: popper, but i'm getting this annoying error in my browser console.
cc: @romansp  @zernonia 

<img width="1510" alt="image" src="https://github.com/radix-vue/radix-vue/assets/59232835/af44cc0f-5a24-4c3f-af11-5896613fa9ca">

**Comment by zernonia** [comment]
Hmmm.. that's new @Helios69 . Could you open another ticket with the reproduction with the error shown above please? 😁
