### ISSUE TITLE
[Bug]: Multiple errors and warnings in console when using ComboboxPortal with position="popper" and as-child set to true. 

### ISSUE THREAD

**Issue by Helios69** [radix-vue/radix-vue#559]
### Environment

```bash
Developement/Production OS: MacOS
Node version: 18.18.1
Package manager: yarn
Radix Vue version: 1.2.3
Vue version: 3.3.4
CSS framework: tailwindcss@3.3.3
Client OS: MacOS
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/sa41ta?file=src%2FApp.vue

### Steps to reproduce

1. Create a combobox with ComboboxPortal and position set to popper and as-child set to true. 
2. Open dropdown.
3. Check browser console.

### Describe the bug

Multiple errors and warnings in console when using ComboboxPortal with position="popper"

![image](https://github.com/radix-vue/radix-vue/assets/59232835/f58abc53-ccca-4d64-ada5-869cbca433f1)

**Comment by zernonia** [comment]
@Helios69  do provide a minimal reproduction for this yaa.. I can't seems to recreate this

**Comment by Helios69** [comment]
@zernonia it's reproducible with as-child prop:
https://stackblitz.com/edit/sa41ta?file=src%2FApp.vue
