### ISSUE TITLE
[Bug]: TabsIndicator ssr error

### ISSUE THREAD

**Issue by teleskop150750** [radix-vue/radix-vue#560]
### Environment

```bash
Developement/Production OS: Ubuntu 22
Node version: 20
Package manager: yarn
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.7.3
Client OS: Ubuntu 22
Browser: Chrome 120
```

### Link to minimal reproduction

https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Tabs/TabsIndicator.vue#L27C9-L27C18

### Steps to reproduce

-

### Describe the bug

[  `const activeTab = context.tabsList.value?.querySelector('[role="tab"][data-state="active"]') as HTMLButtonElement`](https://github.com/radix-vue/radix-vue/blob/5958d4fef3e576ad18ceb7ab86604566ab6d0a84/packages/radix-vue/src/Tabs/TabsIndicator.vue#L27C9-L27C18)

Nuxt sst Error: cannot read properties offsetWidth

![image](https://github.com/radix-vue/radix-vue/assets/62594983/73f12d7f-c40e-4908-baac-29115fe3275e)

**Comment by teleskop150750** [comment]
there is no error in this version

![image](https://github.com/radix-vue/radix-vue/assets/62594983/0d7d3771-6837-47e0-80e7-12ddfafba865)

**Comment by zernonia** [comment]
Thanks for the issue @teleskop150750 ! PR are welcomed! 😁
