### ISSUE TITLE
[Bug]: Tooltip content overflowing

### ISSUE THREAD

**Issue by kristofferdamborg** [radix-vue/radix-vue#567]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/xq9e26-ujdlmd?file=src%2FApp.vue

### Steps to reproduce

1. Put a tooltip with a long content text next to a window border
2. Open the tooltip

### Describe the bug

Tooltip is colliding with window

### Expected behavior

Set the width/height of the tooltip content to avoid collision

### Conext & Screenshots (if applicable)

With default props on TooltipContent:
![image](https://github.com/radix-vue/radix-vue/assets/25890205/707c19f8-e178-4afa-a8f0-cb6f0b8751a4)

With `avoidCollisions` prop set to `true` (which it should be by default?) on TooltipContent. Note that the content is still overflowing in the right side:
![image](https://github.com/radix-vue/radix-vue/assets/25890205/f86eedc7-26a2-46f3-95f7-c6d85ed16ecb)

**Comment by zernonia** [comment]
Thanks for the issue @kristofferdamborg . This seems like it's part of the design from `radix-ui`, it has the similar issue there. The main culprit is `minWidth: 'max-content',` being set in the `PopperContent` component.

To resolve this, you would need to add `max-w-[100vw]` (or any other desired with) to `TooltipContext`.
Hope this helps 😁

**Comment by kristofferdamborg** [comment]
> Thanks for the issue @kristofferdamborg . This seems like it's part of the design from `radix-ui`, it has the similar issue there. The main culprit is `minWidth: 'max-content',` being set in the `PopperContent` component.
> 
> To resolve this, you would need to add `max-w-[100vw]` (or any other desired with) to `TooltipContext`. Hope this helps 😁

@zernonia Thank you for the quick reply! By `TooltipContext`, do you mean the `TooltipContent` component or something else? :)

**Comment by zernonia** [comment]
Ahh by bad.. typo here.. I mean `TooltipContent`

**Comment by zernonia** [comment]
I believe this would solve your issue right?  I will close this off ya 😁

**Comment by kristofferdamborg** [comment]
> I believe this would solve your issue right? I will close this off ya 😁

It worked perfectly, thank you! 🎉
