### ISSUE TITLE
[Feature]: Support for calling toast by function

### ISSUE THREAD

**Issue by Cupkiller-vip** [radix-vue/radix-vue#574]
### Describe the feature

Is it possible to implement a function call similar to the way Message is called in element-plus?
https://element-plus.org/en-US/component/message.html

In most scenarios, what the project needs more than anything else is a short reminder message. Repeatedly writing toast in different components is really tedious, I tried to find simple reuse methods in the documentation, however, the Imperative API is just calling the methods exposed in defineExpose, and you still need to write toast in the template.

I then tried to create a new component via toast, using createVNode and render to mount the component in a function, and then exposing that function. But unfortunately it didn't work efficiently and encountered errors about teleport vs props etc. during the mounting process.

The above was translated with the help of a translation tool, so I apologize if it was confusing for you.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Abstraction for creating and managing new render trees (mixing pure JS and Vue API) would mess with Vue Devtools 

<details><summary>Before</summary>
<p>

![image](https://github.com/radix-vue/radix-vue/assets/17789047/178ca910-80ff-4725-9f86-57c98a63d2e7)

</p>
</details> 

<details><summary>After</summary>
<p>

![image](https://github.com/radix-vue/radix-vue/assets/17789047/fa3c99ea-e746-4572-90cb-1d6d3a90f2e8)

</p>
</details> 

---

You can check `shadcn-vue` [Toast Component](https://github.com/radix-vue/shadcn-vue/tree/dev/apps/www/src/lib/registry/default/ui/toast) source for implement your toast components based on `radix-vue` components

or simply use [`vue-sooner`](https://github.com/xiaoluoboding/vue-sonner) or [`notivue`](https://github.com/smastrom/notivue)
