### ISSUE TITLE
[Feature]: Add ScrollButtons to Combobox component

### ISSUE THREAD

**Issue by npldevfr** [radix-vue/radix-vue#586]
### Describe the feature

It would be fantastic to incorporate the functionalities of the [Select](https://www.radix-vue.com/components/select.html#scrolldownbutton) component into a combobox by including both the ScrollDownButton and ScrollUpButton components.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Select component is designed to match the MacOS native select, but not Combobox. Thus we are not going to implement this. 😁
