### ISSUE TITLE
[Docs]: Can't see the input text at label example

### ISSUE THREAD

**Issue by Sma11X** [radix-vue/radix-vue#597]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/components/label.html

### Steps to reproduce

- Enter the `label` doc page

### Describe the bug

The default text color is set to white (same color as input background).

**Comment by zernonia** [comment]
Thanks for the issue @Sma11X . Seems like `.bg-blackA5` class was being overwritten. Do you wan to help contribute to this fix? 😁

**Comment by Sma11X** [comment]
> Do you wan to help contribute to this fix? 😁

I'm not that familiar with the docs and not sure why set all input background to white 😂.

**Comment by zernonia** [comment]
https://github.com/radix-vue/radix-vue/commit/44cbd4617cdac7111081b0f52e01ac9e165d3d58
