### ISSUE TITLE
[Feature]: Autosize Textarea

### ISSUE THREAD

**Issue by peter-emad99** [radix-vue/radix-vue#598]
### Describe the feature

reference from element-plus package https://github.com/element-plus/element-plus/blob/4a3318f7b1f472ea6ee35cc653e2d5b401ce7ce4/packages/components/input/src/input.vue#L342C8-L342C8

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the suggestion @peter-emad99 . 

However, `radix-vue` focus on building Primitive. As `textarea` is already a native element, we don't plan on adding this.

If you are looking for "Autosize Textarea" feature, you can checkout [useTextareaAutosize](https://vueuse.org/core/useTextareaAutosize/#usetextareaautosize)
