### ISSUE TITLE
[Bug]: DropdownMenuItem contains disabled="false"

### ISSUE THREAD

**Issue by JacksonBowe** [radix-vue/radix-vue#600]
### Environment

```bash
Package manager: npm@10.0.0
Radix Vue version: ^1.2.6
Vue version: 3.0.0
CSS framework: tailwindcss@3.4.0
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/github/JacksonBowe/shadcn-quasar?file=src%2Fcomponents%2Fui%2Fdropdown-menu%2FSDropdownMenuItem.vue

### Steps to reproduce

Appears to only happen with certain frameworks. I am using Quasar Framework and get the issue. If I use base Vite then the issue doesn't occur.
Note: even with base Vite the superflous `disabled="false"` is still present

### Describe the bug

Due to the `disabled="false"` prop something is happening in my setup that ignores the `false` and disables the element. No idea why the `false` isn't being respected.

### Expected behavior

`disabled` prop should not be present if `false`

### Context & Screenshots (if applicable)

Attached is a comparison between Radix and Radix-Vue (both snippets taken from docs webpage). 

Note that the Radix component does not contain `disabled="false"`

![image](https://github.com/radix-vue/radix-vue/assets/26427343/bb0365d2-6c3c-43c9-9797-2acce2f1f519)

**Comment by zernonia** [comment]
Make sense @MellKam . We can remove the `disabled` attributes in `MenuItemImpl.vue`!

**Comment by sadeghbarati** [comment]
> Note that even if any `MenuItem` component in the original radix-ui has `disabled={true}`, it does not display the disabled attribute at all. Only `aria-disabled` and `data-disabled`. I think this is mainly because menu items are by default just a `div` and it doesn't have a disabled state. So, I think we should do the same thing. Just remove disabled attribute at all

@MellKam 

What If I used (just for example) 

```html
<DropdownMenuItem as-child>
    <Button>asd</Button>
</DropdownMenuItem>
```

If we remove disabled attribute, only data-disabled and data-disabled with pass down to Button Component so button appearance will look disabled but not completely disabled

I don't know why it's disabled act like this `disabled="false"` is should be removed when it's value is false or undefined

**Comment by MellKam** [comment]
@sadeghbarati Yeah, in that case you will need to pass disabled twice. First to MenuItem and then to your button. I agree that it may not be obvious. 

This can get even more tricky when you use ’as’ props

’’’vue
<MenuItem as="button" disabled>
  I should be disabled, but I'm not :(
</MenuItem>
’’’

**Comment by zernonia** [comment]
Good point @sadeghbarati . 

what if we do ` :disabled="disabled ? '' : undefined"`, so we only show `disabled` attribute when it is actually disabled. I believe that would solve the issue with Quasar, as well as not needing extra disabled attribute for asChild with button element.
