### ISSUE TITLE
[Bug]: Slider Thumb position should be doesn't reset when prop disable is true

### ISSUE THREAD

**Issue by adirizky54** [radix-vue/radix-vue#612]
### Environment

```bash
Developement/Production OS: MacOS
Node version: 20.10.0
Package manager: npm@10.2.3
Radix Vue version: 1.3.1
Vue version: 3.4.13
Nuxt version: 3.9.1
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-8ryhek?file=app.vue

### Steps to reproduce

You can check on reproduction link that i provide

### Describe the bug

Slider Thumb position reset to zero when prop disabled is true

### Expected behavior

Slider Thumb Position should be stay refer to latest value like in [Slider from RadixUI](https://www.radix-ui.com/themes/playground#slider)
<img width="210" alt="Screenshot 2024-01-15 at 15 25 51" src="https://github.com/radix-vue/radix-vue/assets/24888851/9dad1c46-2f02-4f74-bd84-5bdf9205e6f1">

### Context & Screenshots (if applicable)

https://github.com/radix-vue/radix-vue/assets/24888851/46942fe8-f6f4-47e7-9b79-91867c8c1a5d

**Comment by adirizky54** [comment]
Thanks @zernonia ✨

**Comment by zernonia** [comment]
Thanks for trying out Radix Vue, and reporting the issue!! 💚
