### ISSUE TITLE
[Bug]: Scroll doesn't work inside modal on iOS

### ISSUE THREAD

**Issue by enkot** [radix-vue/radix-vue#614]
### Environment

```bash
Developement/Production OS: macOS Sonoma 14.1.2 (23B92)
Node version: 20.9.0
Package manager: yarn@1.22.19
Radix Vue version: 1.3.1
Vue version: 3.4.14
CSS framework: tailwindcss@3.3.3
Browser: Chrome 120.0.6099.216
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-select-forked-5jsrsm

### Steps to reproduce

1. Toggle device toolbar (iPhone 14 Pro Max)
2. Open modal
3. Try to scroll using touch move

### Describe the bug

Scroll doesn't work.

Looks like it is a regression after https://github.com/radix-vue/radix-vue/pull/593.

### Expected behavior

Scroll works.

### Context & Screenshots (if applicable)

[Vite_Vue_TS_Radix.webm](https://github.com/radix-vue/radix-vue/assets/10506522/4a96a948-8dff-424f-bdb4-070b5df5416b)

**Comment by zernonia** [comment]
You are rigth @enkot !
