### ISSUE TITLE
[Bug]: Prop defaultValue Slider doesn't work

### ISSUE THREAD

**Issue by adirizky54** [radix-vue/radix-vue#618]
### Environment

```bash
Developement/Production OS: MacOS
Node version: 20.10.0
Package manager: npm@10.2.3
Radix Vue version: 1.3.1
Vue version: 3.4.13
Nuxt version: 3.9.1
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-8ryhek?file=app.vue

### Steps to reproduce

You can check on reproduction link that i provide

### Describe the bug

Prop `defaultValue` doesn't work like when we use `v-model`

### Context & Screenshots (if applicable)

<img width="1292" alt="Screenshot 2024-01-16 at 12 27 15" src="https://github.com/radix-vue/radix-vue/assets/24888851/b12e4184-dad2-4ce3-ba06-f34a0fe68fc6">

**Comment by zernonia** [comment]
The default value array doesn't match the number of `Thumb`. Setting the `modelValue` as array with 2 value render the component correctly.

https://stackblitz.com/edit/nuxt-starter-waeen6?file=app.vue

**Comment by adirizky54** [comment]
I see @zernonia got your point , i will close this invalid issue 😁
