### ISSUE TITLE
[Bug]: Error Hydration Mismatch when using TabsRoot on Nuxt 

### ISSUE THREAD

**Issue by adirizky54** [radix-vue/radix-vue#619]
### Environment

```bash
Developement/Production OS: MacOS
Node version: 20.10.0
Package manager: npm@10.2.3
Radix Vue version: 1.3.1
Vue version: 3.4.13
Nuxt version: 3.9.1
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-8ryhek?file=app.vue

### Steps to reproduce

You can check on reproduction link that i provide

### Describe the bug

When use prop `v-model` or `defaultValue` at TabsRoot component i got error Hydration Mismatch

### Context & Screenshots (if applicable)

<img width="1680" alt="Screenshot 2024-01-16 at 13 53 42" src="https://github.com/radix-vue/radix-vue/assets/24888851/d8d39f1f-2921-43a0-96e4-58025fd8882a">

**Comment by zernonia** [comment]
Hydration issue will be keep track here 😁

**Comment by adirizky54** [comment]
Is it related to this discussion @zernonia ? [Auto-Generated IDs + SSR (Hydration Mismatch issue)](https://github.com/radix-vue/radix-vue/discussions/558)

**Comment by zernonia** [comment]
AHHH my bad.. I copied the link and not paste it lol! Yes that's the discussion 😁
