### ISSUE TITLE
[Bug]: Prevent dismissing Dialog when interacting with Toasts (Overlay Components) or native scrollbar

### ISSUE THREAD

**Issue by sadeghbarati** [radix-vue/radix-vue#624]
### Environment

```bash
Radix Vue version: 1.3.2
Vue version: 3.4
```

### Link to minimal reproduction

https://stackblitz.com/edit/t2zzma?file=src%2FApp.vue

Discord Chat:

https://discord.com/channels/1121805548782878813/1194995659758120971

### Steps to reproduce

https://github.com/radix-vue/shadcn-vue/assets/17789047/87dbfc3f-a0db-488f-9ebc-b37553012266

### Describe the bug

Dialog Component will dismiss want to interact with Toasts or native scrollbar 

### Expected behavior

Dialog must remain open, and it should be dismissed when I click on `DialogOverlay`

**Comment by zernonia** [comment]
Thanks guys! After looking deeper into the example I realized this happened on [Radix UI](https://codesandbox.io/p/devbox/zealous-ritchie-mr8vq8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpqjevo800083b6lntu1pnjs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpqjevo800033b6lcjrc8mnu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpqjevo800053b6l6p4adh35%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpqjevo800073b6l38re6pr9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpqjevo800033b6lcjrc8mnu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpqjevo800023b6l4tjgts7z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpqjevo800033b6lcjrc8mnu%2522%252C%2522activeTabId%2522%253A%2522clpqjevo800023b6l4tjgts7z%2522%257D%252C%2522clpqjevo800073b6l38re6pr9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpqjevo800063b6lxgdysmoj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpqjevo800073b6l38re6pr9%2522%252C%2522activeTabId%2522%253A%2522clpqjevo800063b6lxgdysmoj%2522%257D%252C%2522clpqjevo800053b6l6p4adh35%2522%253A%257B%2522id%2522%253A%2522clpqjevo800053b6l6p4adh35%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpqjevo800043b6ly3dj35s7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpqjevo800043b6ly3dj35s7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) as well. I think the fixes might not be simple.

**Comment by AlexGodbehere** [comment]
Related: https://discord.com/channels/1121805548782878813/1194995659758120971
