### ISSUE TITLE
[Feature]: Associate a label to a Select

### ISSUE THREAD

**Issue by jeppe-smith** [radix-vue/radix-vue#626]
### Describe the feature

We should be able to focus a SelectTrigger by clicking on an associated label. Like in this example here. But currently you would have to use `asChild` and render a button with an id to get this functionality.

```
<label for="fruit">Friut</label>
<SelectRoot>
  <SelectTrigger id="fruit">
    <SelectValue placeholder="Please select a fruit" />
  </SelectTrigger>
</SelectRoot>
```

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Sorry @jeppe-smith  I dun quite understand. https://stackblitz.com/edit/vkhvi8?file=src%2FApp.vue shows `SelectTrigger` already receiving `id` as inherited attribute.

**Comment by zernonia** [comment]
Closed as not applicable.The `SelectTrigger` already receiving the `id` attribute via attribute fallback. Example provided in the link above
