### ISSUE TITLE
[Bug]: "Enter" on Toggle Groups not working

### ISSUE THREAD

**Issue by aaazzam** [radix-vue/radix-vue#638]
### Describe the feature

In the radix-vue documentation toggle-groups don't toggle in response to Enter (as opposed to radix-ui, where it does), just space bar. 

Would love to see this parity between the react and vue versions. 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Interesting. This seems like a bug. It was meant to be triggered by "Space/Enter"

![image](https://github.com/radix-vue/radix-vue/assets/59365435/2095333d-796d-4c74-bf06-0c701dde968c)

**Comment by runyasak** [comment]
Hi. I have created a PR to resolve this issue.
Please feel free to review my code: #639  😁
