### ISSUE TITLE
[Feature]: convert text to tags on blur and on tab in tags component

### ISSUE THREAD

**Issue by vesper8** [radix-vue/radix-vue#641]
### Describe the feature

currently it will convert the text to tags only when you press enter, or when you paste if you have the add-on-paste enabled. But I would also like to have add-on-blur and add-on-tab, or have some mechanism for enabling either or both of these functionalities. Only having it work on enter is unintuitive and leads to unexpected user errors.

Many thanks for considering

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by vesper8** [comment]
I was able to work around this in my project by adding `@change="handleChange"` to `TagsInputInput` and then adding

```

      handleChange(e) {
        this.modelValue.push(e.target.value);
        e.target.value = '';
      },
```

But I wish this was baked in

**Comment by zernonia** [comment]
Good suggestion @vesper8 !
