### ISSUE TITLE
[Bug]: scoped styles do not work on certain components

### ISSUE THREAD

**Issue by cyyynthia** [radix-vue/radix-vue#651]
### Environment

```bash
Developement/Production OS: Arch Linux x86_64 6.7.1-arch1-1
Node version: 20.11.0
Package manager: yarn@1.22.21
Radix Vue version: 1.3.2
Vue version: 3.4.15
Nuxt version: N/A
Nuxt mode: N/A
Nuxt target: N/A
CSS framework: None
Client OS: Arch Linux x86_64 6.7.1-arch1-1
Browser: Chromium 121.0.6167.85 Arch Linux
```

### Link to minimal reproduction

https://stackblitz.com/edit/rhvkkt

### Steps to reproduce

- Create a simple popover menu
- Apply a class to `PopoverMenuContent`
- Apply some style using `style scoped`

### Describe the bug

Vue uses `data-v-xxxxxxxx` attributes for scoped CSS. It then uses it to make a selector that is limited to a given scope.

In the case of `PopoverMenuContent`, the data attribute is set on the popper content wrapper, and the class on the menu content. This causes the generated CSS selector (`.class[data-v-xxxxxxxx]`) to not be able to select the menu contents.

### Expected behavior

Scoping should work and the style should be applied.

### Context & Screenshots (if applicable)

Screenshots taken from the minimal reproduction linked above.

Without `scoped`:
![image](https://github.com/radix-vue/radix-vue/assets/9999055/6d265840-4828-40e6-aed8-0304761da573)

With `scoped`:
![image](https://github.com/radix-vue/radix-vue/assets/9999055/87012abc-b914-4643-9fbb-04e75e2ca087)

**Comment by zernonia** [comment]
In this case you need to set it as :deep, so that the style applies to child components.

Please read https://vuejs.org/api/sfc-css-features.html#deep-selectors

**Comment by cyyynthia** [comment]
Oh, I actually feel quite silly not having thought of that! Thank you for pointing this out, works like a charm.

I definitely think this is worth mentioning in the docs (especially in the [Styling](https://www.radix-vue.com/guides/styling.html) section), I'll open a PR to add this neat bit of information for the next person that ends up down the same road as me.
