### ISSUE TITLE
[Feature]: Preventing default behaviour in Accordion

### ISSUE THREAD

**Issue by onmax** [radix-vue/radix-vue#660]
### Describe the feature

Like other components in the catalog, I would like to add an option to prevent the default behavior of item in the Accordion.

I would like to restrict the Accordion to open/close depending on the logic of my own code.

I think we have two options:
- Add a second argument called `event` to the current `update:modelValue` emit.
- Add two new emits: `@open` and `@close` to the `AccordionItem` that emits an event. Then the user can use this event to prevent default behaviour.

I think the second one is the best, but maybe I am missing something :/ 

PD: Not sure if there is another way of achieving what I want at the moment

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@onmax  you can control the Accordion by passing `modelValue` right? 😁

**Comment by onmax** [comment]
mmm, yeah you are right. I think doing something like should work:

```ts
watch(open, () => {
	// logic
}, { flush: 'sync' })
```
