### ISSUE TITLE
[Bug]: ComboboxInput throws warning due to passing Component in `as`

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#667]
@zernonia, we would need, I think, also to omit the `as` attribute and pass it manually otherwise, we get this warning

> [Vue warn]: Vue received a Component that was made a reactive object. This can lead to unnecessary performance overhead and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`.

```vue
<script>
// ...
const pickedProps = reactiveOmit(props, 'as', 'autoFocus')
// ...
</script>

<template>
// ...
<Primitive
  v-bind="pickedProps"
  :as="props.as"
  // ...
</template>
```

_Originally posted by @iamandrewluca in https://github.com/radix-vue/radix-vue/pull/649#discussion_r1479576691_

**Comment by zernonia** [comment]
@iamandrewluca can you share what version of Vue you are using? I tested on latest `shadcn-vue` repo (Vue 3.4.15) and it seems good tho. Not seeing the warning.

**Comment by iamandrewluca** [comment]
v3.4.15

**Comment by iamandrewluca** [comment]
v3.4.15

https://github.com/radix-vue/radix-vue/assets/1881266/8eb3bf8a-55c1-4164-8c51-ba22eddec24c

**Comment by zernonia** [comment]
Ahh! It's actually because of `reactiveOmit` https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Combobox/ComboboxInput.vue#L68 and not `useForwardProps`

**Comment by iamandrewluca** [comment]
@zernonia, Thanks a lot!
