### ISSUE TITLE
[Feature]: 2.7 support?

### ISSUE THREAD

**Issue by aviorp** [radix-vue/radix-vue#675]
### Describe the feature

is that library supported in vue 2.7 ?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
Hi @aviorp Vue 2 reached the end of life even if other maintainers work on it, it's not worth it cause they may face too many issues

take a look at this project and head to dist folder 😢 

https://www.npmjs.com/package/@smooth-scrollbar-contrib/vue-test?activeTab=code

**Comment by zernonia** [comment]
Yup. As @sadeghbarati  pointed out that there's no plan to support 2.7.

In `radix-vue`, we mainly utliized the Composition API, and Provide/Inject context for all the components. We found the compatibility issue and `vue-demi` just can't solved easily.

Hopefully you'll understand.
