### ISSUE TITLE
[Bug]: Dialog forceMount breaks the whole dialog system

### ISSUE THREAD

**Issue by CIMEOS** [radix-vue/radix-vue#688]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/c4lrn6?file=src%2FApp.vue

### Steps to reproduce

add ForceMount on the `DialogContent` 

### Describe the bug

When the dialog is closed and has `aria-expanded="false"`
- the body automatically has `pointers-events:none;`
- `#app` has `aria-hidden="true`
- the events @pointer-down-outside and @focus-outside prevent us from opening the dialog because if we click on the trigger, they are called to close the dialog immediatly

### Expected behavior

- the dialog events and effetcs should only be initialized when the dialog is opened (aria-hidden:false) and not be based on the dialog's presence.

### Context & Screenshots (if applicable)

We are using the dialog for a filters popin - and to keep the filters existing, we need to force mount that popin so that the refs don't disapear when we close it. By doing so, we realised that we couldn't click on the page anymore even when the popin is closed (because of the pointer-event:none on the body) and that even if we manage to dance around that, the events on the DialogContent prevent us to keep the dialog opened since we logically click outside of the content to open it.

**Comment by zernonia** [comment]
Can you tried `keep-alive` to persist the state of the refs instead? https://vuejs.org/guide/built-ins/keep-alive

**Comment by zernonia** [comment]
Or. Could you try passing `modal:false` when hiding? then set as `true` when you open it. This way the `pointers-events:none;` wouldn't be added unless you open it.

**Comment by CIMEOS** [comment]
I tried `keep-alive` around the `DialogContent`, `DialogPortal` and even `DialogRoot` but nothing seems to work.
But 'playing" with the modal boolean seems to work ! Thank you !

**Comment by zernonia** [comment]
Glad to hear that @CIMEOS . I will proceed to close this ticket ya! 😁
