### ISSUE TITLE
[Bug]: Transitions are not working when opening/closing/navigating the Navigation menu component

### ISSUE THREAD

**Issue by fayazara** [radix-vue/radix-vue#689]
### Environment

```bash
Developement/Production OS: MacBook Pro 2020 Intel Core i5
Node version: 18.17.0
Package manager: pnpm@8.6.1
Radix Vue version: 1.4.4
Vue version: 3.4.19
Nuxt version: 3.10.2
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.4.1
Client OS: Mac OS Sonoma 14.1.1
Browser: Chrome 121.0.6167.184
```

### Link to minimal reproduction

https://stackblitz.com/edit/github-fk8usg?file=tailwind.config.js

### Steps to reproduce

Open the stackblitz and click on any of the menu items, you can see that the navigation menu opens without any transitions as seen in the demo in the docs

### Describe the bug

The navigation menu transitions are not working when open/cloding the navigation menu, and when you move from one item to another

Some notes
1. The navigation menu indicator's transitions as expected
2. The height transitions smoothly as expected.
3. the stackblitz link provided in the docs behave the same as my reproduction, not transitions when opening/closing/navigating the menu (video attached)

### Expected behavior

Transitions should happen correctly as per the docs demo - https://www.radix-vue.com/components/navigation-menu.html

### Context & Screenshots (if applicable)

https://github.com/radix-vue/radix-vue/assets/15716057/1182204f-bfed-4b9e-95a3-4f937d4bef17

**Comment by zernonia** [comment]
Hey @fayazara .. after looking at your Stackblitz, it seems like it is not generating the related keyframes/animation as mentioned in `tailwind.config`. I believe it's not related to `radix-vue`, but some other tailwind related config.

**Comment by fayazara** [comment]
> Hey @fayazara .. after looking at your Stackblitz, it seems like it is not generating the related keyframes/animation as mentioned in `tailwind.config`. I believe it's not related to `radix-vue`, but some other tailwind related config.

@zernonia  The same thing seems to happen in the demo stackblitz provided in the radix-vue.com docs site 

https://stackblitz.com/run?file=src%2FApp.vue

**Comment by zernonia** [comment]
@fayazara you are right. I've updated the `tailwind.config` and it should be working now for the stackblitz demo

**Comment by SwartZCoding** [comment]
> @fayazara you are right. I've updated the `tailwind.config` and it should be working now for the stackblitz demo

I have same issue on Modal using nuxt 3.10 and radix-vue 1.4.6. Modal doesn't have animation

**Comment by zernonia** [comment]
Closing this as seems like not related to `radix-vue` 😁
You might need to check with `ui.nuxt` and see why the keyframes/animations were not added.
