### ISSUE TITLE
[Bug]: Types are not exported for namespaced components

### ISSUE THREAD

**Issue by aleksey-hoffman** [radix-vue/radix-vue#691]
### Environment

```bash
Developement/Production OS: Windows 11
Node version: 20.10
Package manager: npm 10.2.3
Radix Vue version: 1.4.6
Vue version: 3.4.15
Nuxt version: none
CSS framework: none
Client OS: Windows 11
Browser: Chrome latest
```

### Link to minimal reproduction

https://github.com/aleksey-hoffman/sigma-file-manager/tree/v2

### Steps to reproduce

Import a component using namespaced method 

### Describe the bug

![image](https://github.com/radix-vue/radix-vue/assets/61761672/00de2a71-9729-406b-962e-570f49b11b67)

**Comment by ChrisGV04** [comment]
That's weird. I have been using the namespaced components without issues even today.

Make sure you have installed version 1.2.0 or later, since that's when namespaced components where added.

**Comment by aleksey-hoffman** [comment]
@ChrisGV04 yep, I have `"radix-vue": "^1.4.6"`. I restarted VScode to make sure it's not caused by TS watcher. Still thte same error

**Comment by aleksey-hoffman** [comment]
@ChrisGV04 it works if I import it from dist:

```
import {Dialog} from 'radix-vue/dist/namespaced';
```

Instead of what's specified in the docs:

```
import {Dialog} from 'radix-vue/namespaced';
```

**Comment by ChrisGV04** [comment]
I'm not sure why you can't use `radix-vue/namespaced`. I have been using it exactly as the docs say since I started using Radix Vue.

Here are some suggestions that I can think of:
1. I use pnpm instead of npm or yarn. I don't know if this makes a difference.
2. Try to add a `.npmrc` file to your project directory with this line: `shamefully-hoist=true` then delete the `node_modules` and package-lock file and try to run install again.
3. Try adding `"type": "module"` to your `package.json` and reloading VS Code.

I have that my own project using Radix Vue and it works perfectly

**Comment by aleksey-hoffman** [comment]
@ChrisGV04 it seems `radix-vue/namespaced` directory is not exported from index or index.d.ts file of the package.
It seems the problem is with the package types. 

I have `"type": "module"` specified. Probably shouldn't create `.npmrc` just for one package. 
It seems pnpm resolves missing types automatically somehow

**Comment by ChrisGV04** [comment]
Just checked the source code and it does export the namespaced types correctly.

If they weren't exported, it wouldn't work for anyone at all. But it works fine in my case.

I use Nuxt 3, so the `.npmrc` is actually part of the starter template. I also had it on Vite projects, but I'm not sure if it could affect your app. I suggest you give it a try and revert the changes if it breaks something else

**Comment by ChrisGV04** [comment]
The namespaced types are exported in the `node_modules/radix-vue/package.json` and can be found at `node_modules/radix-vue/dist/namespaced/index.d.ts`.

**Comment by aleksey-hoffman** [comment]
@ChrisGV04 could you please take a look at my [tsconfig](https://github.com/aleksey-hoffman/sigma-file-manager/blob/v2/tsconfig.json)? Is there anything wrong with it?
