### ISSUE TITLE
[Feature]: Listbox

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#696]
### Describe the feature

Extract and improve the logic for `Combobox`. In some case we dont need to have the `Popper`/`Dismissable` effect for list of item.

Feature:
- [ ] Searchable input
- [ ] Support virtual list 
- [ ] Base component for `Combobox`
- [ ] Following https://www.w3.org/WAI/ARIA/apg/patterns/listbox/

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

Closes
- https://github.com/radix-vue/radix-vue/issues/551
- https://github.com/radix-vue/radix-vue/issues/498
- https://github.com/radix-vue/radix-vue/issues/716 (probably)

**Comment by sadeghbarati** [comment]
List of `Virtual List` packages

- https://github.com/TanStack/virtual
- https://github.com/Akryum/vue-virtual-scroller
- https://github.com/inokawa/virtua (founded from your stars 😄)
- VueUse Virtual composable

**Comment by zernonia** [comment]
Im leaning towards https://github.com/TanStack/virtual as it has the composable that would fit our `Primitive` approach of component pretty well.

Was hoping for `virtua` composable, but seems like it's still unstable https://github.com/inokawa/virtua/issues/388

**Comment by romanhrynevych** [comment]
+1, think that TanStack is the best approach for virtualizer, vue-virtual-scroller add additional 2 HTML element wrappers that can be very annoying (inside `<table>` element for example). VueUse is not so customizable, great for small lists. And inokawa/virtua, as zernonia mentioned, not released yet 🙂 

> List of `Virtual List` packages
> 
> * https://github.com/TanStack/virtual
> * https://github.com/Akryum/vue-virtual-scroller
> * https://github.com/inokawa/virtua (founded from your stars 😄)
> * VueUse Virtual composable

**Comment by sadeghbarati** [comment]
a question 

After `Listbox` component isn't better to remove the same Popover functionality from `SelectContent` and `ComboboxList` or another related component that uses `Popover` primitives underhood (but with another name and the same functionality)?

Here the example

https://react-spectrum.adobe.com/react-aria/Select.html#example
https://react-spectrum.adobe.com/react-aria/ComboBox.html#example

Popover primitive handling overlays for Select and Combobox contents not `SelectPopover` or `ComboboxPopover`

**Comment by zernonia** [comment]
@sadeghbarati I would prefer to have the existing components for `Select` and `Combobox` to be the same, as I want to introduce this in v1.6, without introducing major breaking change.

React Aria looks powerful, to match the similar approach we would need to re-construct some of the component from the ground up. Also, not sure this pattern would be adored by the community or not.

**Comment by kristofferdamborg** [comment]
> I want to introduce this in v1.6

@zernonia I can see v1.6 is released now, but I can't seem to find this feature. Was it pushed/delayed or am I not looking in the right place? 😊

**Comment by zernonia** [comment]
Hey @kristofferdamborg . Still working in progress, and don't want to hold back other release. Expect it would be out soon! 😁

**Comment by kilobyte2007** [comment]
Hi @zernonia, can you please expand on the "Searchable input" item and what it means?
Will it work/look similar to this the following?
<img width="374" alt="image" src="https://github.com/radix-vue/radix-vue/assets/1911258/aa9530ec-f80a-4536-990f-ef3da0131147">

I'd like to have a search input inside a select component and it looks like it's not really possible with either the combobox or the select elements.

Thanks a lot for the work on the library!
