### ISSUE TITLE
[Bug]: Missing array type on `ComboboxRoot` `modelValue` prop

### ISSUE THREAD

**Issue by ChrisGV04** [radix-vue/radix-vue#698]
### Environment

```bash
Radix Vue version: 1.4.7
```

### Link to minimal reproduction

Not relevant

### Steps to reproduce

N/A

### Describe the bug

The type for the `modelValue` prop of the `ComboboxRoot` is only

```ts
export type AcceptableValue = string | number | boolean | Record<string, any>;
```

However, the Combobox component accepts the `multiple` prop, so it should also allow for `Array` or `(string | number | boolean | Record<string, any>)[]` to be complete in my opinion.

I know this is minor, but maybe it would make the type definition more complete and useful for type inference when using

```ts
if (Array.isArray(props.modelValue)) {
  props.modelValue // Type is correctly set to be (string | number | boolean | Record<string, any>)[]
}
```

**Comment by ChrisGV04** [comment]
Hi @zernonia! Will you be adding the missing type to `AcceptableValue` or would you like me to open a PR to do it?

**Comment by zernonia** [comment]
Welcome PR! 🤩
