### ISSUE TITLE
[Feature]: Select with filter options

### ISSUE THREAD

**Issue by harrytran998** [radix-vue/radix-vue#700]
### Describe the feature

Adding filterable to `Select` enables filtering. By default, Select will find all the options whose label attribute contains the input value. If you prefer other filtering strategies, you can pass the `filter method` which is a Function that gets called when the input value changes and its parameter is the current input value.

Example detail: https://element-plus.org/en-US/component/select.html#option-filtering

Thank for reading this, but do not try so hard, take care your health!

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by AceXiamo** [comment]
There's another component `Combobox`, perhaps that's what you're looking for.

[https://www.radix-vue.com/components/combobox.html](url)
