### ISSUE TITLE
fix: focus portal triggers only when escaped

### ISSUE THREAD

**Issue by khairulhaaziq** [radix-vue/radix-vue#72]
#11 #9 

affected component:
- [ ] DropdownMenu
- [ ] MenuBar
- [ ] ContextMenu

**Comment by zernonia** [comment]
@khairulhaaziq  what does this ticket means ya? we want to close the portal when we press escape key?

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq what does this ticket means ya? we want to close the portal when we press escape key?

Some portals behave differently when opened, for example, according to radix, the popover locks the scroll and make the body into pointer-events-none, and if we click anywhere it will return focus to the button.

I am still thinking if we want to do use the same behavior for popover. As for the thread it is mainly about dropdownmenu since I copied the function from popover, I accidentally added the same behavior when opening/closing portal, which isnt the right behavior.
