### ISSUE TITLE
[Feature]: Tree

### ISSUE THREAD

**Issue by antonreshetov** [radix-vue/radix-vue#732]
### Describe the feature

It would be nice to have a tree component. 

Examples:

1. https://element-plus.org/en-US/component/tree.html
2. https://github.com/phphe/he-tree

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
https://github.com/formkit/drag-and-drop

**Comment by ChrisGV04** [comment]
Maybe this can wait for Pragmatic Drag-and-Drop to launch the stable and documented v1. I imagine is going to be amazing based on what I have seen from the developer behind it.

Check it out here: https://github.com/atlassian/pragmatic-drag-and-drop

**Comment by antonreshetov** [comment]
Another good example, this is probably the closest I can think of to the concept

https://github.com/dgreene1/react-accessible-treeview

**Comment by alexreardon** [comment]
Pragmatic drag and drop is now public 🚀

**Comment by zernonia** [comment]
Yup @alexreardon ! Will start prototyping this component using Pragmatic dnd soon 😉

**Comment by zernonia** [comment]
Hey guys! I've started developing the component and I realized that `draggable` is not part of the spec for [Tree View](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/).

Thus we will not be including in the primitives. However, we will make sure to expose necessary API to make `draggable` possible and include an example 😁

**Comment by antonreshetov** [comment]
@zernonia Do all components in radix implement the ARIA specification or only it? 

The request was just so a complete tree component with drag & drop. There are many places where such functionality is needed, and if such a component were in radix it would add even more glory.

I also don’t think it was a good idea to rename the request title, it distorts the meaning.

**Comment by zernonia** [comment]
@antonreshetov  yup all the components were built to handle and follow the ARIA specification. As dnd is not part of that, hence we are not planning to implement that, and most likely will not. However it with the dnd feature-request in mind, we will be sure to allow dev to build their own dnd using their favourite dnd package and desired behavior

**Comment by antonreshetov** [comment]
Splitter?

**Comment by zernonia** [comment]
Yup @antonreshetov  

https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/

**Comment by antonreshetov** [comment]
My message was different, ARIA is about accessibility, radix is ​​a set of components that simplify the development of interfaces. Is this the goal?

**Comment by zernonia** [comment]
@antonreshetov 

Radix Vue aims to provide unstyled primitive components, where user would then build custom logic around it.

In the case of dnd, this is something very "custom" and user might want to have very specific behavior and UI representation. Thus it make sense that user should handle it themself. 

Here's a [Stackblitz Demo](https://stackblitz.com/edit/github-8f3fzs?file=src%2FTreeDND.vue) to showcase the dnd feature build with the `Tree` component in the PR above. Hopefully this would aids user to create their desired dnd behavior and styling.

**Comment by zernonia** [comment]
Complete on https://github.com/radix-vue/radix-vue/pull/1087
