### ISSUE TITLE
[Bug]: Datepicker: changind DateField doesn't update popup Calendar value.

### ISSUE THREAD

**Issue by renatodeleao** [radix-vue/radix-vue#736]
### Environment

```bash
N/A
Browser: Chrome 122.0.6261.94 
```

### Link to minimal reproduction

https://www.radix-vue.com/components/date-picker.html

### Steps to reproduce

1. update date to any value manually using `DateField` inputs
1. Open `Calendar` popup and see that the input date is not highlighted in the `Calendar`.

### Describe the bug

`DateField` input model value is not being synced to `Calendar` model value

### Expected behavior

Manually inputting date on `DateField` should update `Calendar` model, the same way that updating `Calendar` updates `DateField`

### Context & Screenshots (if applicable)

We can also see that after selecting value in `Calendar`, manually changing model in `DateField` resets `Calendar` model to null (unselected date).

**Comment by zernonia** [comment]
Thanks @renatodeleao ! Fixed in https://github.com/radix-vue/radix-vue/pull/738
