### ISSUE TITLE
[Feature]: Support other Calendar Systems

### ISSUE THREAD

**Issue by sadeghbarati** [radix-vue/radix-vue#742]
### Describe the feature

https://react-spectrum.adobe.com/blog/date-and-time-pickers-for-all.html#calendar-systems

React-aria uses `Provider` (context) for locale in Dates but in `radix-vue` it's not clear how to change Calendar Systems and locale correctly

--- 

For example PersianCalendar System

### RadixVue

https://stackblitz.com/edit/plbydl

- Persian date segments are `YYYY/MM/DD` ✅  but `v-for` segments are `DD/MM/YYYY` ❌
if I reverse segments array keyboard arrows will not work good with it

- If I select a date cell when my Calendar System is Persian, my DatePicker will Teleport time from 1402 to 2024 or 3266 and ...

### MeltUI

https://stackblitz.com/edit/github-yzqybw-guqhpr

- Persian date segments are correct `YYYY/MM/DD` ✅ 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@epr3 🙏

**Comment by epr3** [comment]
Hello @sadeghbarati,

I checked into the issue you're having and it's related to the `DateValue` objects losing their prototype functions when they get dereferenced when using `ref` (hence the jumps) (e.g. functions like `toJulianDate`, etc. defined on the `calendar` object attached on each `DateValue` which are needed to maintain the calendar).

I'm going to work on forking `@internationalized/date` and refactoring it towards an approach that uses only primitives and uses a compositional approach in handling dates (basically making the `DateValue` objects plain objects and exposing all the manipulation functions as utilities plus identifiers for calendars, an approach resembling `date-fns`).

I'll open a PR here when I get this library in a working shape and keep you posted.
