### ISSUE TITLE
[Bug]: V-Model binding to ref with string value breaks setup

### ISSUE THREAD

**Issue by borovez** [radix-vue/radix-vue#745]
### Environment

```bash
Radix Vue version: 1.5.1
Vue version: latest
Browser: Edge Chromium
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-datepicker-forked-kjvvnv?file=%2Fsrc%2FApp.vue

### Steps to reproduce

1. Setup a ref value to use in v-model on DatePickerRoot component. 
2. Set the initial value of the ref to a valid date string ie. '2021-01-01'
3. Observe that the datepicker component is not visible (broken)
4. Observe the console for errors;

```
index.js:8 
 [Vue warn]: Unhandled error during execution of setup function 
  at <DatePickerRoot id="date-field" modelValue="2021-01-19" onUpdate:modelValue=fn  ... > 
  at <App>
  
  
  Uncaught TypeError: O.copy is not a function
    at setup (index.js:6837:47)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7612:25)
    at setupComponent (runtime-core.esm-bundler.js:7573:36)
    at mountComponent (runtime-core.esm-bundler.js:5901:7)
    at processComponent (runtime-core.esm-bundler.js:5867:9)
    at patch (runtime-core.esm-bundler.js:5335:11)
    at mountChildren (runtime-core.esm-bundler.js:5583:7)
    at mountElement (runtime-core.esm-bundler.js:5490:7)
    at processElement (runtime-core.esm-bundler.js:5455:7)
  ```

### Describe the bug

Just wanted to try out the DatePicker, however when assigning a string value to the initial ref model value, the DatePickerRoot breaks. 

However, if the initial ref value is null, the v-model works as intended.

### Expected behavior

The initial ref value used in v-model should accept a valid string date as the default value.

Speaking about defaultValue, that prop also does not work.
```js
<DatePickerRoot default-value="2021-01-01">
```

**Comment by zernonia** [comment]
This is not a bug ya @borovez .  `modelValue` accepts `DateValue` , do have a look at [Dates](https://www.radix-vue.com/guides/dates.html) section to understand more.

Example of how to use:
```ts
import { CalendarDate } from '@internationalized/date'
import { type Ref, ref } from 'vue'

const modelValue = ref( new CalendarDate(2024, 2, 20))
```
