### ISSUE TITLE
[Feature]: Export component as 'Namespaced Component'

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#75]
**Is your feature request related to a problem? Please describe.**

In `Radix-ui`, they are using namespaced component to export all child component (including root component) as a component.

(eg: DialogRoot.vue -> Dialog.Root).

**Describe the solution you'd like**

We can do the same for Radix-vue too. Can check out https://github.com/xiaoluoboding/vue-command-palette/blob/main/packages/index.ts to learn how it was achievable.

 
(This is just a nice to have, so we don't need to import all the child component manually when building a custom component)

**Comment by khairulhaaziq** [comment]
hi @zernonia , glad to have you here! yes we have considered this and think that a non-namespaced naming convention is more 'vue-like', however I think its also possible to implement both. This is still very early decision though so anything can change. We would really like to have you contribute on this, if you want, I would like to invite you to our discord server so I can get you setup

**Comment by zernonia** [comment]
After testing out using Namespaced component (while developing Primitive), it seems unintuitive for Vue user, as it is not the convention.
So will close out this ticket ya 😁

**Comment by aleksey-hoffman** [comment]
@zernonia would it also be possible to add types to the export?

![image](https://github.com/radix-vue/radix-vue/assets/61761672/024d2aef-6f78-4268-a4de-ca73290b00da)
