### ISSUE TITLE
[Feature]: add "preventScroll" Prop for Select

### ISSUE THREAD

**Issue by XamzatJR** [radix-vue/radix-vue#752]
### Describe the feature

Right now we cannot scroll page if select is open and have to write workarounds to remove added styles from body. It would be great to have this prop not just for Select but also for similar components like Combobox, Dropdown, etc.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by kilobyte2007** [comment]
This would be very useful.

**Comment by zernonia** [comment]
This should be implemented already. Try `bodyLock=false` for [SelectContent](https://www.radix-vue.com/components/select.html#content)
