### ISSUE TITLE
[Bug]: Navigation Menu Content remains visible after hovering out

### ISSUE THREAD

**Issue by jimzrt** [radix-vue/radix-vue#753]
### Environment

```bash
Radix Vue version: 1.5.2
Vue version: 3.4.21
Browser: Chrome and Firefox
```

### Link to minimal reproduction

https://stackblitz.com/edit/byzqud?file=src%2FApp.vue

### Steps to reproduce

- hover over any navigation menu item/trigger
- move the cursor into the opened menu content to interact with it
- move the cursor outside of the menu content area

### Describe the bug

The menu content remains visible even after the cursor is moved outside of the content area, contradicting the expected behavior where it should hide.

### Expected behavior

Upon moving the cursor outside of the menu content area, the content should automatically hide/disappear, as the hover interaction is no longer active.

### Context & Screenshots (if applicable)

After reviewing the WCAG guidelines on hover or focus content at [W3C's Understanding Content on Hover or Focus](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html), it seems the menu's behavior—staying open after hover—isn't standard. A fix or an option to control this might be needed.

**Comment by zernonia** [comment]
Thanks @jimzrt ! Seems like a bug with recent changes in `1.5.2`. Will have a look 😁
