### ISSUE TITLE
[Feature]: Tabs: Prop to not unmount once the Tab is viewed. 

### ISSUE THREAD

**Issue by ManasMadrecha** [radix-vue/radix-vue#756]
### Describe the feature

Currently, we have a prop to `forceMount` a tab content. But, if a child component which fetches data is placed inside a background Tab Content, then the child component will still compulsorily fetch the data (albeit only once), even if not the user doesn't view/open the tab. 

However, it would be optimal if we have a prop called "unmountOnExit" (which can be set to false). This way, Tabs work normally (i.e., no need to force mount background tabs if a tab is never viewed), but if a specific tab is viewed (which has this prop), then the child component would fetch the data only once, and then would not re-render again when the tab is switched back again.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by peter-emad99** [comment]
can you use KeepAlive vue component

**Comment by ManasMadrecha** [comment]
Can you kindly share the anatomy of such usage? I mean, which element should we wrap with KeepAlive... the TabRoot or ...?

**Comment by peter-emad99** [comment]
i didn't try it out ..but i was meaning the tabContent that you want to keep it unmounted ..wrap it with keepAlive.

**Comment by zernonia** [comment]
As @peter-emad99  suggested, you should leverage `KeepAlive` component from Vue. Or you can use `v-show`.

Check this [example](https://stackblitz.com/edit/vszstv?file=src%2FApp.vue) out

**Comment by zernonia** [comment]
Will close this out as the component already offers the capability to achieve the desired output.
Check https://github.com/radix-vue/radix-vue/issues/756#issuecomment-2003338097
