### ISSUE TITLE
[Feature]: Checkbox group 

### ISSUE THREAD

**Issue by peter-emad99** [radix-vue/radix-vue#765]
### Describe the feature

vue support model on array with checkboxes ,currently i didn't find any way to do that with Radix checkbox 
(all checkbox model on same ref that has initial value as array[] it will toggle the selected value of the checkbox from this array

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by peter-emad99** [comment]
or should i use ToggleGroup To achieve same behavior ?

**Comment by MattRogowski** [comment]
Also currently trying to do this, doesn't look like it's possible to have multiple checkboxes for the same model. Quite a big blocker at the moment.

**Comment by peter-emad99** [comment]
any update on this ?

**Comment by zernonia** [comment]
You can construct this feature on your own by wrapping multiple `Checkbox` component. Adding array to a checkbox primitive is not a good component design.

**Comment by ChrisGV04** [comment]
I don't believe it would cause confusion... It is actually how native checkboxes work on Vue.

https://vuejs.org/guide/essentials/forms.html#checkbox
