### ISSUE TITLE
[Feature]: Add Tooltip flag to use only focus from the keyboard.

### ISSUE THREAD

**Issue by remonke** [radix-vue/radix-vue#774]
### Describe the feature

VueUse uses the following trick to match only `:focus-visible` when focusing on an element:

```vue
useEventListener(targetElement, 'focus', (event) => {
   if (!focusVisible || (event.target as HTMLElement).matches?.(':focus-visible'))
     innerFocused.value = true
 })
 ```
 
I suggest making this an optional flag, and using regular focus by default (this would be a breaking change I believe, and it has only 94% support according to caniuse.com). This would slightly improve the UX, as the tooltip currently shows up when say I focused on a button by mouse and focused back from a different tab, or closed a dialog opened by a button with a tooltip.

[Here's an example](https://stackblitz.com/edit/nuxt-starter-wgak7r?file=nuxt.config.ts%2Capp.vue%2Ccomponents%2Ftooltip-button.vue) - try to focus with a mouse on each of the button and then switch browser tabs. The one without `focus-visible` gets triggered. I personally find this not ideal...

I think I can implement this on my own, however I don't know if I should implement this behavior myself or use the `useFocus` hook from VueUse, as VueUse is already included in this library. 

Please let me know what do you think about this. 😊

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the issue and PR @remonke ! I think this would be a good addition to the Tooltip! Some dev might want to have `keyboard` only tooltip! 👍
