### ISSUE TITLE
[Feature]: Provide component specific data attribute names

### ISSUE THREAD

**Issue by remonke** [radix-vue/radix-vue#781]
### Describe the feature

The problem with current composition API is that many components share the same data attributes. Let's take example from the docs:
```vue
<script setup lang="ts">
import { TooltipRoot, TooltipTrigger, TooltipPortal, DialogRoot, DialogTrigger, DialogPortal } from "radix-vue";
import MyButton from from "@/components/MyButton.vue"
</script>

<template>
  <DialogRoot>
    <TooltipRoot>
      <TooltipTrigger asChild>
        <DialogTrigger asChild>
          <MyButton>Open dialog</MyButton>
        </DialogTrigger>
      </TooltipTrigger>
      <TooltipPortal>…</TooltipPortal>
    </TooltipRoot>

    <DialogPortal>...</DialogPortal>
  </DialogRoot>
</template>
```

Both `DialogTrigger` and `TooltipTrigger` share a `data-state` attribute. Since these two components get merged into one, there's no way get access to both or even predict which one will be applied.

I suggest making these attribute component specific like:
- TooltipTrigger `data-state` -> `data-tooltip-trigger-state`
- DialogTrigger `data-state` -> `data-dialog-trigger-state`

This would solve any issues with unambiguity I mentioned before. However, this would also be a breaking change. Another approach would be to allow overriding the default data attribute like this:

```vue
<TooltipTrigger data-state-attr="data-tooltip-trigger-state" />
```

It would be better, as it is not a breaking change, however it is a bit cumbersome to write in my opinion. Maybe it would be nice to allow providing all of these names in a `ConfigProvider`, along with maybe some preset for all components.

Please let me what do you think of this.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
I would prefer having specific attribute name for each component (https://github.com/radix-vue/radix-vue/issues/505) instead of all the relevant attribute. It would be too long and hard to keep track. Imagine `data-tooltip-trigger-state`, `data-tooltip-trigger-disabled`, etc. 

Then, we can use DOM selector as such `document.querySelector('[data-tooltip-trigger][data-state=checked]')`.
