### ISSUE TITLE
[Bug, Nuxt]: Hydration children mismatch on HTMLInputElement

### ISSUE THREAD

**Issue by bogdan0083** [radix-vue/radix-vue#782]
### Environment

```bash
Developement/Production OS: MacBook Air M1, 2020
Node version: v20.11.0 (lts)
Package manager: yarn/npm
Radix Vue version: ^1.5.3
Vue version: 3.4
Nuxt version: 3.11.1
Nuxt mode: universal
Nuxt target: server
CSS framework: nuxtjs/tailwindcss@6.11.4
Client OS: MacBook Air M1, 2020
Browser: Chrome 123.0.6312.58
```

### Link to minimal reproduction

[Reproduction Link](https://codesandbox.io/p/devbox/brave-mestorf-6zhym3?workspaceId=66cad8a9-5fb6-46b2-8c0d-f31f7a6aa7ce&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu53657y00053b6k6pdtth42%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu53657y00023b6ktzq8pix2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu53657y00033b6k4mxsmgih%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu53657y00043b6krezncw1y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu53657y00023b6ktzq8pix2%2522%253A%257B%2522id%2522%253A%2522clu53657y00023b6ktzq8pix2%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu53657y00043b6krezncw1y%2522%253A%257B%2522id%2522%253A%2522clu53657y00043b6krezncw1y%2522%252C%2522activeTabId%2522%253A%2522clu53b4hw007h3b6klh9bkjrj%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clu536dh500183b6kyc1lymx9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clu53b4hw007h3b6klh9bkjrj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clu53657y00033b6k4mxsmgih%2522%253A%257B%2522id%2522%253A%2522clu53657y00033b6k4mxsmgih%2522%252C%2522activeTabId%2522%253A%2522clu539kbp00413b6kx4k6v890%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu539kbp00413b6kx4k6v890%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu539kiu0038dhk99nq2aqa5%2522%257D%252C%257B%2522id%2522%253A%2522clu53iz2q00ky3b6keq0uc5wk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu53iza3003gdhk9e2b913be%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Open my reproduction link
2. Initialize the repro (`yarn && yarn run dev`)
3. Open `devtools` console
4. See Vue Warnings

### Describe the bug

[chadcn-vue TagsInput example combined with combobox](https://www.shadcn-vue.com/docs/components/tags-input.html) when reproduced with `Nuxt.js` throws vue warnings:
```
warn [Vue warn]: Hydration children mismatch on HTMLInputElement 
Server rendered element contains fewer child nodes than client vdom. 
  at <Primitive id=undefined ref=fn<s> type="text"  ... > 
  at <TagsInputInput placeholder="Framework..." class="text-sm min-h-5 focus:outline-none flex-1 bg-transparent w-full px-3" onKeydown= (4) [ƒ, ƒ, ƒ, ƒ]  ... > 
  at <TagsInputInput class="w-full px-3" onKeydown= (4) [ƒ, ƒ, ƒ, ƒ] type="text"  ... > 
  at <PrimitiveSlot type="text" disabled=false value=""  ... > 
  at <Primitive ref=fn<s> as="input" as-child=true  ... > 
  at <ComboboxInput placeholder="Framework..." as-child="" > 
  at <PrimitiveSlot > 
  at <Primitive as-child=true as=undefined > 
  at <PrimitiveSlot > 
  at <Primitive ref=fn<s> as=undefined as-child=true > 
  at <PopperAnchor as-child="" > 
  at <ComboboxAnchor as-child="" > 
  at <Primitive ref=fn<s> style= {pointerEvents: } as=undefined  ... > 
  at <PopperRoot class="w-full" > 
  at <ComboboxRoot modelValue= [] onUpdate:modelValue=fn open=false  ... > 
  at <Primitive dir="ltr" as=undefined as-child=false  ... > 
  at <PrimitiveSlot ref=Ref< undefined > class="flex flex-wrap items-center rounded-md border border-input bg-background py-1.5 text-sm px-0 gap-0 w-80" > 
  at <CollectionSlot class="flex flex-wrap items-center rounded-md border border-input bg-background py-1.5 text-sm px-0 gap-0 w-80" > 
  at <TagsInputRoot modelValue= [] onUpdate:modelValue=fn onInvalid=fn  ... > 
  at <TagsInput class="px-0 gap-0 w-80" model-value= [] > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" vnode= {__v_isVNode: true, __v_skip: true, type: Object, props: Object, key: null, …} route= {fullPath: '/', hash: '', query: Object, name: 'index', path: '/', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <NuxtLayoutProvider layoutProps= {ref: Object} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
```

I have no idea how to properly debug and find the cause for such type of warnings  😄 

### Expected behavior

There should be no vue warnings

### Context & Screenshots (if applicable)

<img width="607" alt="Снимок экрана 2024-03-24 в 13 20 38" src="https://github.com/radix-vue/radix-vue/assets/7077307/4bf2398e-723a-4315-81ff-98d4528e3b25">

**Comment by zernonia** [comment]
This should be fixed with https://github.com/radix-vue/radix-vue/pull/776 where we try to render `<img>` with SSR.

**Comment by bogdan0083** [comment]
@zernonia Sorry for the offtopic question, is it possible to install `radix-vue` directly from github?

I tried to install `radix-vue` as `"radix-vue": "radix-vue/radix-vue#main",` to check if PR you mentioned works, but I get:

```
Pre-transform error: Failed to resolve entry for package "radix-vue". The package may have incorrect main/module/exports specified in its package.json
```

I guess I should wait for a release to test it?
