### ISSUE TITLE
[Feature]: `<SelectRoot>` accept more than just a string as a model.

### ISSUE THREAD

**Issue by kylemilloy** [radix-vue/radix-vue#792]
### Describe the feature

Commonly I find myself with a select dropdown where I want to pick from some IDs of a model I have however when I try to directly use `number` as a value in the v-model of SelectRoot it gives me warnings that v-model may only be a string.

Is this by design or can we extend this type to be more than just a string? If so...lemme know and I'll write a PR.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Duplicated of https://github.com/radix-vue/radix-vue/issues/772
