### ISSUE TITLE
[Bug]: Cannot find package '@internationalized/date' radix-vue@1.6.0

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#797]
### Describe the bug

After the version 1.6.0 when you try to use radix-vue, without `@internationalized/date` package installed, it will throw an error. Although the package is listed as an optional peer dependency, it gets imported anyway when bundled into the single index.js file, causing the error.

We probably need to move the `@internationalized/date` package back to be just dependency.

Looking ahead, it would make sense to split the radix-vue package into a sub-packages for each component (as it does radix-ui). That would resolve this PR https://github.com/radix-vue/radix-vue/pull/469 and allow us to install only dependencies that we actually need. 

### Context & Screenshots (if applicable)

![image](https://github.com/radix-vue/radix-vue/assets/51422045/f83e7087-0ce3-43fc-8ac9-3f4b5b9a2677)

**Comment by zernonia** [comment]
I don't really like splitting components into their own packages.. There's many depedency versioning issue, as you may observe in `radix-ui`. I prefer not to let dev worry about what version of `DismissableLayer` is compatible with which version of `Dialog`. This also ensure that we won't have much compatibility issue.

As for the case of `@internationalized/date`, I think we can future improve on this, maybe a different way to bundle the lib? 
For now yeah we can add it back as deps to unblock `1.6.0`

**Comment by sadeghbarati** [comment]
@MellKam, hi, can you share your project?

having a lot of deps for package is not good imo 

peerDependency means it's user duty to install the package (it's not included in the radix-vue package)

Having it in dependencies means for every release the make we should do it too, which is not good for package maintainers

**Comment by MellKam** [comment]
@sadeghbarati No, sorry. I can't share it. It's my work project. But I think you can easily reproduce it. Since we are bundling all the components into one index.js file, the import for `@internationalized/date` is also included in that file. So if you decide not to use any date components and do not install this dependency, you will see an error.
