### ISSUE TITLE
[Bug]: Out animation doesn't work for `Select` and `DropdownMenu` with `:modal="false"`

### ISSUE THREAD

**Issue by MellKam** [radix-vue/radix-vue#800]
### Link to minimal reproduction

https://stackblitz.com/edit/8sgcno?file=src%2FApp.vue

### Steps to reproduce

I used playground example from shadcn-vue and modified it with `:modal="false"` on the root component. For some reason, enabling this prevents out animation from running. 

This problem happened after the 1.6.0 release.

**Comment by MellKam** [comment]
I think the problem is related to this commit - 12965aa5ada3bd224bce66342758316b5cf19538

**Comment by ChrisGV04** [comment]
This issue exists for many components that have overlay behavior. The Vue `Transition` is not being applied
