### ISSUE TITLE
[Bug]: HoverCardTrigger is untappable on mobile

### ISSUE THREAD

**Issue by remonke** [radix-vue/radix-vue#802]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-kklahm?file=app.vue

### Steps to reproduce

1. Create a HoverCard
2. Try to tap on it with a touch pointer

### Describe the bug

A user cannot press on a link with a HoverCard.

### Context & Screenshots (if applicable)

[Screencast_20240401_011302.webm](https://github.com/radix-vue/radix-vue/assets/102010617/05d8dd99-e1b3-443d-84dc-f3dee3a3ffa6)

**Comment by zernonia** [comment]
This was by designed as mentioned [here](https://github.com/radix-ui/primitives/issues/955#issuecomment-960610209)
As this component only cater for "Hover" interaction, maybe you should consider using `Popover` instead.

**Comment by remonke** [comment]
But it's not like I can't open the hover card (which I can), but I can't simply tap on the link on mobile.

**Comment by remonke** [comment]
Okay I did some digging and appearently Vue registers `touchstart` listener as a non-passive listener, while React uses a passive listener. As a result, `e.preventDefault()` on `touchstart` in Vue prevents any actions on the target, while in React it logs an error to the console.

![Screenshot_20240401_123920](https://github.com/radix-vue/radix-vue/assets/102010617/66129f04-9f98-4505-b9dc-fb2be0291686)
![Screenshot_20240401_123942](https://github.com/radix-vue/radix-vue/assets/102010617/a01b266f-a814-49af-b1f9-37da71755651)
![ezgif-6-46588a02e8](https://github.com/radix-vue/radix-vue/assets/102010617/ba8ca5b7-5650-4602-902c-7fd095aeca22)

**Comment by ChrisGV04** [comment]
What @zernonia means is that this component is only meant to be triggered on **hover** as the name implies. This is because there are certain behaviors you only want to work with a mouse on hover, not because of browser limitations.

To be clear, it would be totally possible to allow opening the card on tap for touch screens, but that's not what this component is made for.

If you really need to support tap-to-open, consider using `Popover` which also allows you to open the card on hover if you manually set it to `:open="true"` on hover.

**Comment by ChrisGV04** [comment]
@zernonia I see what @remonke means...

He's not having issues with hovering to view the `HoverCardContent`. That is working just fine.

The issue is that the link doesn't even work on touch devices. If you tap the link it doesn't go to the `href` at all.

**Comment by zernonia** [comment]
Thanks for the clarification guys! Yup I see the issue here now 😁
