### ISSUE TITLE
[Bug]: Can't compose `DropdownMenu` with `Tooltip`

### ISSUE THREAD

**Issue by remonke** [radix-vue/radix-vue#811]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-gdz8pu?file=app.vue

### Steps to reproduce

Try to add a Tooltip to a DropdownMenu trigger

### Describe the bug

Either both don't work or the `DropdownMenuContent` flies off the screen.

**Comment by rev4324** [comment]
Try like this: https://stackblitz.com/edit/nuxt-starter-dxqano?file=app.vue

**Comment by remonke** [comment]
wow dziękuje
