### ISSUE TITLE
[Feature]: Make tabs component `v-model` generic

### ISSUE THREAD

**Issue by DamianGlowala** [radix-vue/radix-vue#819]
### Describe the feature

Currently, the value passed via `model-value` prop to the tabs component isn't inferred in `@update:model-value` (shows as `string`):

![image](https://github.com/radix-vue/radix-vue/assets/48835293/75dd4ece-a2de-428c-b1a0-dc195f25c043)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@Chrtyaka  I think we can add this generic type similar to this PR you made https://github.com/radix-vue/radix-vue/pull/832 😁

Maybe something like `<script setup lang="ts" generic="T extends StringOrNumber = StringOrNumber">`

**Comment by Chrtyaka** [comment]
Yep, this looks cool! Definitely  do that!

Somehow I missed this feature. I should read the vue changelog more carefully 😅
