### ISSUE TITLE
[Bug]: Hydration children mismatch on Component with slots

### ISSUE THREAD

**Issue by nethriis** [radix-vue/radix-vue#826]
### Environment

```bash
Developement/Production OS: Windows 11
Node version: 20.10.0
Package manager: pnpm@8.15.4
Radix Vue version: 1.6.1
Vue version: 3.4.21
Nuxt version: 3.11.1
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.4.3
Client OS: Windows 11
Browser: Firefox
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-3jevr5

### Steps to reproduce

1. Create a component that wrap radix-vue component (DropdownMenu for example).
2. Place a slot in the created component (in DropdownMenuTrigger for example).
3. When the created component have a slot in it, it produce the mismatch error.

### Describe the bug

I have the error [Vue warn]: Hydration children mismatch when there is a slot in component.

**Comment by nethriis** [comment]
I think that this issue is due to this commit https://github.com/radix-vue/radix-vue/pull/801/commits/c0f1a7b83c55902cf13096a9a98b7656bfb0e11c from @MellKam

**Comment by zernonia** [comment]
I believe it's due to having `button` wrap inside another `button`, and it's causing server hydration issue.

https://stackblitz.com/edit/nuxt-starter-rll2rb?file=components%2FDropdown.vue

**Comment by nethriis** [comment]
Oh yes my bad thanks !
