### ISSUE TITLE
[Feature]: DateField locale vs language vs format

### ISSUE THREAD

**Issue by Antonimo** [radix-vue/radix-vue#829]
### Describe the feature

https://www.radix-vue.com/components/date-field.html

How can I separately select language and format?
![image](https://github.com/radix-vue/radix-vue/assets/612902/47c808a6-3d18-4db4-9614-3949901c95d7)

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by epr3** [comment]
The `locale` property changes the language of the `DateField`, but it also sets the implicit order of the `DateField` segments specific to that `locale`. 

The default order is defined through [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts) by using `@internationalized/date`'s [`DateFormatter`](https://react-spectrum.adobe.com/internationalized/date/DateFormatter.html)

You can change the format by reordering the `segments` slot prop to your needed format.

**Comment by Antonimo** [comment]
yeah but the format is not only the order, its also the symbols. Notice the dots between the date segments.
It should be possible to set locale and format and language separately.

**Comment by epr3** [comment]
You can always replace the values to fit your needs:
```            
<DateFieldInput
  v-if="item.part === 'literal'"
  :part="item.part"
>
  {{ item.value === '.' ? '/' : ':' }}
</DateFieldInput>
```

**Comment by epr3** [comment]
@zernonia From my side, I don't think it is a bug, as we don't have a `format` property for the `DateField` components, it is the default behaviour of `[Intl.DateTimeFormat.formatToParts`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts) which handles the format, literals and order of the `DateField` parts according to the provided `locale`. 

I think this feature can be handled manually, replacing the `literal` values with anything and reordering the fields could be achieved easily with an object handling the order of the fields like `{ 'month': 2, 'year': 1, etc.}` then using something like `toSorted()` on the `segments` `v-slot` property using the object defined above.

**Comment by zernonia** [comment]
That make sense @epr3 . If this is the behavior of `Intl.DateTimeFormat` then it would be best if devs handle the desired separator themselves. 

@Antonimo  I believe the above comment should solve your issue. Closing this as we have a solution here, and adding a prop to handle format is unncessary. 😁
