### ISSUE TITLE
[Feature]: the ability to disable switching the focus of a document to a DropdownMenuItem on hover

### ISSUE THREAD

**Issue by masawik** [radix-vue/radix-vue#845]
### Describe the feature

the ability to disable switching the focus of a document to a DropdownMenuItem on hover

**use cases:** 
1. The search field embedded in the list constantly loses focus when the user hovers over the list to, for example, scroll through it and view the results
![image](https://github.com/radix-vue/radix-vue/assets/56366545/e6993ba2-df19-413a-bc7f-18779c791b0f)

2. When the height of the list is limited and the last element is not fully displayed, then when you move the cursor over the list, the last element focuses, which causes the list to twitch back and forth in an ugly way

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
@masawik  I'm not sure I understand the ticket. Can you please elaborate more, or perhaps add a stacklbitz to explain what are you looking for?

**Comment by zernonia** [comment]
Closing as stale
