### ISSUE TITLE
[Feature]: Add `data-placeholder` to date picker input

### ISSUE THREAD

**Issue by DamianGlowala** [radix-vue/radix-vue#858]
### Describe the feature

It would be useful to somehow be able to differentiate input placeholders (e.g. `mm` or `dd`) from the actual user input. This would allow to style default values e.g. with a grayish color, and user input with more prominent one. One of the ideas I can think of is having `data-placeholder` appear whenever a placeholder is present instead of user-provided value.

cc @epr3 

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by epr3** [comment]
You can try something like `aria-[valuetext=Empty]:text-green9` for styling default values for the time being.

But, if you think it's cumbersome I can add a `data-placeholder` attribute.

cc @zernonia & @sadeghbarati what would be your opinion about adding a new data attribute on the `DateFieldSegment` component?

**Comment by DamianGlowala** [comment]
This works well, thanks! I wouldn't come up with it on my own though (hence might be good to provide and/or document it) 😄

**Comment by zernonia** [comment]
I think we can add this 😁 We usually tend not to use `aria` as styling, but `data`. This addition I believe might bring clarity for user wanting the style based on the `data-placeholder` value 😁
