### ISSUE TITLE
[Bug]: Tooltip not showing up when rendered on the server

### ISSUE THREAD

**Issue by nethriis** [radix-vue/radix-vue#861]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 20.10.0
Package manager: pnpm@9.0.0
Radix Vue version: 1.7.0
Vue version: 3.4.21
Nuxt version: 3.11.2
Nuxt mode: universal
Nuxt target: server
Client OS: Windows 10 19043.1110
Browser: Firefox
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-hrb7vm?file=app.vue%2Cnuxt.config.ts

### Steps to reproduce

Render a Tooltip using SSR.

Reload the page then hover the element that should be hovered.

### Describe the bug

Tooltip not showing up when rendered on the server

**Comment by nethriis** [comment]
> This is duplicate of #848. If you have any issue do comment there. Patch will be released soon. Do help test again after the release. 😁

I know, I just resignal it, but the issue is not fixed so why closing it

**Comment by zernonia** [comment]
I close it because it's the same issue, no point creating multiple issue. If you want resignal it just a comment at that will do. The fixes to that hasn't been publish. Thus I ask to check again when we release the patch.
