### ISSUE TITLE
[Feature]: Emit event when Dialog's animation are completed

### ISSUE THREAD

**Issue by noook** [radix-vue/radix-vue#878]
### Describe the feature

Hi, contributor of [@nuxt/ui](https://github.com/nuxt/ui) here. As we are porting features from v2 to v3, I noticed something I am unable to port when transitioning from HeadlessUI to Radix.

When using [modals programmatically](https://ui.nuxt.com/components/modal#control-programmatically), we listen to [`TransitionRoot @after-leave`](https://headlessui.com/react/transition#component-api) so we know we can reset the modal safely.

I understand that `Presence` is used under the hood, but I can't determine if I can use anything to hook into that.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Currently there's no way to hook into the `animation end` event. I believe this can be easily done if we dispatch a custom event for dev to capture and hook into

**Comment by noook** [comment]
That's exactly what I had in mind, is it something easy to detect and dispatch ? I could do a PR but I'm not sure where to look for this

**Comment by genu** [comment]
I see that this is closed and completed. 

Is there any documentation on how to do this? I wasn't able to find any example or any documentation on the `Presence` component.

**Comment by zernonia** [comment]
Hi @genu ! You may check out the docs [here](https://reka-ui.com/docs/utilities/presence#api-reference). It's v2 but it should be almost the same 😁

**Comment by mkeyy0** [comment]
@zernonia Can we now listen for the `animation-end` even on the dialog content in v2, or do we need to wrap it in the `Presence` component to make it work? Cause as I see Dialog and other similar components are already wrapped in the `Presence` component, but I don't see that they're emitting some events
