### ISSUE TITLE
[Feature]: Treat null as an empty value for Select

### ISSUE THREAD

**Issue by kilobyte2007** [radix-vue/radix-vue#880]
### Describe the feature

From what I see here, for the Select component - only `undefined` and `''` is treated as an empty value - see here: https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Select/utils.ts

Is there any reason why `null` is not treated the same way? If it's a design decision - I think it would make sense to have a way to configure this somehow.

The same situation is present in ToggleGroup, Calendar, and some other components where null is not accepted as a type while it's a pretty common situation where some values can come as null from a backend or API.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the issue @kilobyte2007 .. I think it make sense to consider `null` as nullish value and show the placeholder here

**Comment by kilobyte2007** [comment]
Thanks for the fix @zernonia.

Shouldn't we then also add null as the type to the`modelValue` prop type here: https://github.com/radix-vue/radix-vue/blob/64d7eb233c9c6009a5069ccb9d21849eff47b0a4/packages/radix-vue/src/Select/SelectRoot.vue#L14

Or is this going to be part of a bigger change with v2, where `Select` will accept more types?
