### ISSUE TITLE
[Feature]: Focus trigger on dialog close

### ISSUE THREAD

**Issue by enkot** [radix-vue/radix-vue#921]
### Describe the feature

Currently, if a dialog is controlled by modelValue and does not use the DialogTrigger, focus cannot be handled properly (move focus back to the trigger after closing).
I suggest adding a `triggerElement` prop to the `DialogRoot` so that the user can specify which trigger was used to open the dialog.

### Additional information

- [X] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for the issue and PR @enkot . However I have different solution in mind, similar to [Headless UI](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/hooks/use-outside-click.ts#L87).. perhaps internally we can track the previous focus of the target, and focus on it again when the dialog close. 

This way, user might need to not set additional prop, and have a more consistent behaviour. Imagine 2 buttons could trigger the same dialog.

**Comment by enkot** [comment]
I agree, it will be a better solution.
