### ISSUE TITLE
[Bug]: `CustomEvent` is not defined on SSR

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#930]
We’re getting a fatal error on latest Nuxt and 1.8.0

```
500

CustomEvent is not defined

at ee.immediate (./node_modules/.pnpm/radix-vue@1.8.0_vue@3.4.27_typescript@5.4.5_/node_modules/radix-vue/dist/index.js:1506:163)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

In console:
```
Loading Failed for the module with source “http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/perfect-debounce.js?v=768501e7”.
```
and
```
Uncaught (in promise) TypeError: error loading dynamically imported module: http://localhost:3000/_nuxt/@fs/Users/[PERSONAL_FOLDER]/node_modules/.pnpm/@nuxt+devtools@1.3.1_@unocss+reset@0.60.2_change-case@4.1.2_floating-vue@5.2.2_@nuxt+kit@3.11_gpokhtbjebjqlsaipxd7yrpxba/node_modules/@nuxt/devtools/dist/runtime/plugins/view/client.mjs?v=57a21bdb
```

_Originally posted by @luigigorlero in https://github.com/radix-vue/radix-vue/issues/901#issuecomment-2117244298_

**Comment by zernonia** [comment]
Yup might be Node18 doesn't support `CustomEvent` https://github.com/nodejs/node/issues/40678.
@luigigorlero  @roberthgnz  can you try bump the Node version and see if it works? 😁

**Comment by roberthgnz** [comment]
I am using the library with Nuxt, I have solved it by loading the route in SPA mode, in that case I don't need it to be SSR.

**Comment by BayBreezy** [comment]
So what now? What about the apps running on node18?

**Comment by sadeghbarati** [comment]
I'm curious why not Vue emits? why we recreate the emits again? 
at least for events on components we can use Vue emits but for document or window scope we need CustomEvent


Perhaps using `isClient` before using CustomEvents might help solving this issue

**Comment by DamianGlowala** [comment]
Could someone prepare a minimal reproduction which fails on Node 18?

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/github-uewhkz

node v18 and pnpm working

**Comment by zernonia** [comment]
> I'm curious why not Vue emits? why we recreate the emits again?
at least for events on components we can use Vue emits but for document or window scope we need CustomEvent

@sadeghbarati  I think using Custom Event here make sense, as we can target the specifc node with the event, and user can listen to that event by using `v-on` from Vue. `v-on:enter` or `@enter`. 


Yeah we should add `isClient` in this function as it make sense to have this animation custom event to be triggered only in client-side.
