### ISSUE TITLE
[Bug]: ComboboxContent forceMount prop not working wrigth

### ISSUE THREAD

**Issue by sedmedgh** [radix-vue/radix-vue#932]
### Environment

```bash
Developement OS: Ubuntu 23.10
Node version: 20.5.1
Package manager: pnpm@8.15.4
Radix Vue version: 1.8.0
Vue version: 3.4.21
CSS framework: unocss@0.59.0
Client OS: Ubuntu 23.10
Browser: Chrome 123.0.6312.105
```

### Link to minimal reproduction

dont have

### Steps to reproduce

<ComboboxPortal>
    <ComboboxContent force-mount>
    
    </ComboboxContent>
</ComboboxPortal>

### Describe the bug

I need to render ComboboxItems on mount to get default slot of selected item to render inside ComboboxTrigger
When I set the prop forceMount on the ComboboxContent Element, the popover is open by default and never closes, otherwise it should render the html tag on the mount and the popover won't open.

**Comment by zernonia** [comment]
Can you please create a minimal reproduction? 😁

**Comment by sedmedgh** [comment]
https://stackblitz.com/edit/qfkmpu?file=src%2FApp.vue,src%2Fcomponents%2FCombobox.vue,package.json,src%2Fcomponents%2FComboboxContent.vue,src%2Fcomponents%2FComboboxGroup.vue,src%2Fcomponents%2FComboboxItem.vue,src%2Fcomponents%2FComboboxLabel.vue,src%2Fcomponents%2FComboboxSeparator.vue,src%2Fcomponents%2FComboboxTrigger.vue,.vscode%2Fsnippets.json

**Comment by sedmedgh** [comment]
my code is like this:
https://stackblitz.com/edit/qfkmpu?file=src%2FApp.vue,src%2Fcomponents%2FCombobox.vue,package.json,src%2Fcomponents%2FComboboxContent.vue,src%2Fcomponents%2FComboboxGroup.vue,src%2Fcomponents%2FComboboxItem.vue,src%2Fcomponents%2FComboboxLabel.vue,src%2Fcomponents%2FComboboxSeparator.vue,src%2Fcomponents%2FComboboxTrigger.vue,.vscode%2Fsnippets.json

**Comment by zernonia** [comment]
`forceMount` prop is behaving as expected where it would always force mount the component, thus it will always be open. If you need greater control, you can always use `forceMount` with `v-if`/`v-show`.
