### ISSUE TITLE
[Bug]: ToggleGroup allows a type='single' to deselect and have no value

### ISSUE THREAD

**Issue by RieMars** [radix-vue/radix-vue#947]
### Environment

```bash
Development/Production OS: MacOS 14.3
Node version: 20.9.0
Package manager: npm@10.1.0
Radix Vue version: 1.8.1
Vue version: 3.4.27
CSS framework: tailwindcss@3.3.3
Firefox: 125.0.1, Safari 17.3
```

### Link to minimal reproduction

https://www.radix-vue.com/components/toggle-group.html

### Steps to reproduce

When using the RadixVue ToggleGroup docs, top example, click on the selected value of the alignment toggle. It will deselect.

Also if you click through to the CodeSandbox link in the example at the top, it has a different bug where it doesn't allow you to deselect the selected item, but then it gets stuck in a mode where multiple items appear selected (but they are not the ones you chose to select).

### Describe the bug

That you can deselect the selected value in a toggle group type='single' which is meant to always have a value.

It appears this different functionality was introduced somewhere between radix-vue 0.1.16 and today:
https://codesandbox.io/p/devbox/radix-vue-togglegroup-w84wmd?file=%2Fsrc%2FApp.vue

There is a section in the docs to deal with this situation:
https://www.radix-vue.com/components/toggle-group.html#ensuring-there-is-always-a-value

But that doesn't fix things, but it also contradicts the earlier part of the docs for the 'type' property. 
```
'single' | 'multiple'

Determines whether a "single" or "multiple" items can be pressed at a time.

This prop will be ignored if any of v-model or defaultValue is an defined, as the type will be inferred from the value.
```
So the added direction to add the type in _Ensure there is always a value_ section shouldn't have any effect. It seems that the 'single' or 'multiple' functionality is meant to be inferred from the reference object it's passed being a string ('single') or an array ('multiple')? Really that section needs reviewing to make sense with prop's directions.

### Expected behavior

That the ToggleGroup has a mode where it cannot be null. That you cannot deselect in 'single' mode.

I can also imagine a form where you only want a 'single' mode but it starts with no selected value and it might be a required field so it needs to allow a way for a null value to start with.

Also I'd suggest revising the API Reference to the property 'type' if this is indeed how it's meant to work.
```
This prop will be ignored if v-model or defaultValue is defined, as the type will be inferred from the value.
```

**Comment by zernonia** [comment]
Sorry for the confusion @RieMars . We implemented the toggle behavior similar to Radix UI, where we can deselect a value. As for the example in docs, that should be updated as it doesn't demonstrate the behavior.

Essentially the `type` will be auto-inferred if `defaultValue` or `modelValue` is provided.

**Comment by zernonia** [comment]
@RieMars  I've updated the docs here https://947-bug-togglegroup-allows-a.radix-vue.pages.dev/components/toggle-group.html#ensuring-there-is-always-a-value

See if it make sense 😁

**Comment by RieMars** [comment]
Thanks for updating that. Makes more sense now and solved my problem!
