### ISSUE TITLE
[Bug]: When using Primitive to build components, got This is likely not portable. A type annotation is necessary.ts(2742)

### ISSUE THREAD

**Issue by Shana-AE** [radix-vue/radix-vue#950]
### Environment

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 154.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.volta/tools/image/node/20.12.2/bin/node
    Yarn: 1.22.19 - ~/.volta/bin/yarn
    npm: 10.5.0 - ~/.volta/tools/image/node/20.12.2/bin/npm
    pnpm: 8.3.0 - ~/.volta/bin/pnpm
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-vue: ^5.0.4 => 5.0.4
    radix-vue: ^1.8.1 => 1.8.1
    typescript: ^5.2.2 => 5.2.2
    vite: ^5.2.0 => 5.2.0
    vue: ^3.4.21 => 3.4.21
```

### Link to minimal reproduction

https://github.com/Shana-AE/radix-vue-portable-issue

### Steps to reproduce

1. clone the code and install it
2. remember to use workspace version typescript
3. see /src/index.ts#L3

### Describe the bug

When using radix-vue to build component and export the built component with `as typeof ComponentA` with tsconfig `declaration: true`
I got ts2742 error
![image](https://github.com/radix-vue/radix-vue/assets/31391693/7eca329d-8df7-4064-8b84-27bf0aaf7832)

`The inferred type of 'default' cannot be named without a reference to '../../../../node_modules/radix-vue/dist/Primitive'. This is likely not portable. A type annotation is necessary.ts(2742)`

**Comment by zernonia** [comment]
Might be related to https://github.com/radix-vue/radix-vue/discussions/946
