### ISSUE TITLE
[Bug]: Number Field value remains after deleting field value 

### ISSUE THREAD

**Issue by sadeghbarati** [radix-vue/radix-vue#953]
### Environment

```bash
radix-vue v1.8.1
```

### Link to minimal reproduction

https://www.radix-vue.com/components/number-field.html

### Steps to reproduce

empty/delete Number Field value then click on **plus** or **minus** buttons

value starts from the current value ❌ 

### Describe the bug

Number Field value remains even after empty/delete the field value

### Expected behavior

value should start from zero or from starter value ✅ 

https://react-spectrum.adobe.com/react-aria/useNumberField.html#example

**Comment by sadeghbarati** [comment]
Same bug is happening in Combobox

When I delete the Combobox value I expect to deselect the option in the list

https://www.radix-vue.com/components/combobox.html

- select apple
- delete/empty combobox value
- close combobox
- value is still apple after closing combobox

**Comment by zernonia** [comment]
@sadeghbarati  @epr3  that combobox behavior would be some breaking change, and might not be what some dev want. We can include a behavior props in v2.
