### ISSUE TITLE
[Feature]: Remove NumberFieldLabel

### ISSUE THREAD

**Issue by romanslonov** [radix-vue/radix-vue#965]
### Describe the feature

As per [shadcn-vue-571](https://github.com/radix-vue/shadcn-vue/pull/571) PR @zernonia decided to remove `NumberFieldLabel`. 

Should I remove this part completely?

```ts
const labelId = useId(undefined, 'number-field-label')
const inputId = useId(undefined, 'number-field-input')
```

And user will target label to input similar as regular `Label` and `Input`?

Example:

```vue
<template>
  <Label for="example-number-field">Number field</Label>
  <NumberFieldRoot>
    <NumberFieldDecrement />
    <NumberFieldInput id="example-number-field" />
    <NumberFieldIncrement />
  </NumberFieldRoot>
</template>
```

### Additional information

- [X] I intend to submit a PR for this feature.
- [x] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks @romanslonov ! We need to make sure we can focus the input given an id to `NumberFieldRoot`
