### ISSUE TITLE
[Feature]: Dialog overlay click event

### ISSUE THREAD

**Issue by gokhantaskan** [radix-vue/radix-vue#967]
### Describe the feature

At present, the dialog overlay does not have certain functionalities. I have observed that the mask click option does not function as expected. When clicking outside the content component, the dialog closes, and I am unable to trigger a click event on the overlay.

I want to incorporate a `beforeClose` callback function to control whether the dialog should be closed. While I can easily achieve this with `DialogClose`, I am facing challenges with `DialogOverlay`, regardless of whether it wraps `DialogContent`.

```vue
<script setup lang="ts">
import type { TeleportProps } from "node_modules/radix-vue/dist/Teleport";
import {
  DialogContent,
  DialogDescription,
  DialogOverlay,
  DialogPortal,
  DialogRoot,
  DialogTitle,
} from "radix-vue";

type DoneFn = (cancel?: boolean) => void;
export type DialogBeforeCloseFn = (done: DoneFn) => void;

defineOptions({
  inheritAttrs: false,
});

const props = withDefaults(
  defineProps<{
    ...
    beforeClose?: DialogBeforeCloseFn;
  }>(),
  {
   ...
    beforeClose: undefined,
  }
);

const open = defineModel<boolean>("open");

function handleBeforeClose() {
  const hide = (cancel?: boolean) => {
    if (cancel) {
      return;
    }

    open.value = false;
  };

  props.beforeClose?.(hide);
}
</script>
```

I wonder how to trigger `handleBeforeClose` with an overlay click.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Actually we already have this feature, you can use

```vue
<DialogContent
   @pointer-down-outside="ev => {
   // check if clicked on modal
   // if true, ev.preventDefault()
  }"
>
```

**Comment by gokhantaskan** [comment]
`@pointer-down-outside.prevent="() => handleBeforeClose()"` just worked. Thanks!
