### ISSUE TITLE
[Bug]: `as-child` type issues with 1.8.2

### ISSUE THREAD

**Issue by gu-stav** [radix-vue/radix-vue#983]
### Environment

```bash
Developement/Production OS: MacOS 14.5
Node version: 20.0.0
Package manager: npm@10.2.4
Radix Vue version: 1.8.4
Vue version: 3.4.27
```

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-ksc3vz?file=src%2Fcomponents%2FBox.vue

### Steps to reproduce

1. `npm i`
2. `npm run build`
3. 💥 types don't work

### Describe the bug

Starting with some version of 1.8 `Primitive` no longer accepts `Ref` for the `as-child` prop coming from `useForwardProps`:

```src/components/Box.vue:14:4 - error TS2345: Argument of type '{ as: Ref<AsTag | Component | undefined>; asChild: Ref<boolean>; }' is not assignable to parameter of type 'Partial<{ asChild: boolean; as: AsTag | Component; }> & Omit<{ readonly asChild: boolean; readonly as: AsTag | Component; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Readonly<...>, "asChild" | "as"> & Record<...>'.
  Type '{ as: Ref<AsTag | Component | undefined>; asChild: Ref<boolean>; }' is not assignable to type 'Partial<{ asChild: boolean; as: AsTag | Component; }>'.
    Types of property 'asChild' are incompatible.
      Type 'Ref<boolean>' is not assignable to type 'boolean | undefined'.

14   <Primitive v-bind="forwarded">
      ~~~~~~~~~
```

This doesn't apply to `as-child` only. I am also seeing many type issues in other parts of the application, which is tied to vanilla-extract/ sprinkles. If it is of any help I can also try and create a bigger reproduction there.

We are updating from 1.7.4.

### Expected behavior

I'd expect the types of `Primitive` and the composable to be compatible.

**Comment by zernonia** [comment]
You are using `useForwardProps` wrongly. It should be a computed or a ref, and not object of ref.
Check out https://stackblitz.com/edit/vitejs-vite-dgmjpq?file=src%2Fcomponents%2FBox.vue

**Comment by gu-stav** [comment]
@zernonia Apologies, I just realized my reproduction maybe was a bit too minimal to showcase the problem properly. 🙈 

I have created a more realistic and extensive version of it. The following is working in 1.7.4, but can not build in 1.8.x:

1.7.4: https://stackblitz.com/edit/vitejs-vite-4xcuqh?file=src%2Fcomponents%2FText.vue
1.8.2: https://stackblitz.com/edit/vitejs-vite-ksc3vz?file=src%2Fcomponents%2FText.vue

`sprinkles()` is just a stub for https://vanilla-extract.style/documentation/packages/sprinkles/ for demostration purposes. In reality the code for `Text` looks something like this:

```vue
<script setup lang="ts">
import { defineProps, toRefs } from 'vue'

import { useForwardProps } from 'radix-vue'

import { Box, type BoxProps } from '../Box'

import { sprinkles, type Sprinkles } from '@/styles/sprinkles.css'

export interface TextProps extends BoxProps {
  align?: Sprinkles['textAlign']
}

const props = defineProps<TextProps>()
const { align, ...rest } = toRefs(props)
const forwarded = useForwardProps(rest)
</script>

<template>
  <Box
    v-bind="forwarded"
    :class="
      sprinkles({
        textAlign: align,
      })
    "
  >
    <slot />
  </Box>
</template>
```

I think pulling out props for `Text` and passing on the rest (`BoxProps`) via a spread is a valid usecase for `useForwardProps`, don't you think?

```js
const props = defineProps<TextProps>();
const { align, family, ...rest } = toRefs(props);
const forwarded = useForwardProps(rest);
```

As far as I understand in Vue@3.5 we would be able to replace this with a destructuring assignment:

```js
const { align, family, ...rest } = defineProps<TextProps>();
const forwarded = useForwardProps(rest);
```

and I believe this also would return every prop of type `Ref`.
