### ISSUE TITLE
[Bug]: Error when pressing an already selected toggle group again

### ISSUE THREAD

**Issue by black7375** [radix-vue/radix-vue#992]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/components/toggle-group

### Steps to reproduce

1. Go to [toggle group](https://www.radix-vue.com/components/toggle-group)
2. Enable developer tools
3. Press `Left align` button

### Describe the bug

If you press the toggle that was pressed on `type=“single”` again, an error occurs.

```
Error: Either the `type` or the `value` or `default-value` prop must be defined
```

### Expected behavior

The last button pressed should remain selected, not unchecked like a checkbox.
Or, since it's a toggle group, it can be turned off, but shouldn't throw an error.

**Comment by zernonia** [comment]
Thanks for reporting the issue @black7375 ! Given that we are auto infer the `type` when the `v-model` is `undefined`, thus throwing the error. 

So `ToggleGroup` would required to add `type=single` to prevent such error. 😁

**Comment by black7375** [comment]
Thank you for fast bugfix!!
