### ISSUE TITLE
[Bug]: ESLint config doesn't have the Vue plugin enabled

### ISSUE THREAD

**Issue by epr3** [radix-vue/radix-vue#996]
### Environment

```bash
Package manager: pnpm@8.15.4
Radix Vue version: 1.8.3
```

### Link to minimal reproduction

N/A

### Steps to reproduce

Steps to reproduce:
1. Run `pnpm lint` on any `.vue` file
2. Observe that linting may not work

### Describe the bug

Found this bug while trying to format `.vue` files on save in the editor.

According to this line: https://github.com/antfu/eslint-config/blob/523bc04549541b27f145eb8ec30fe215fd2a6fa7/src/factory.ts#L98, the eslint config does not load any `Vue` related plugins because the`package.json` file that is the closest to the `eslint.config.mjs` file doesn't have `vue` listed as a dependency, `typescript` gets loaded fine though.

### Expected behavior

Linting should work on `.vue` files.

**Comment by zernonia** [comment]
I also noticed this recently and thought it was my vscode issue (as it was working previously). Thanks for the issue and PR! 💚
