### ISSUE TITLE
[Feature]: Integrate Renovate/Dependabot

### ISSUE THREAD

**Issue by epr3** [radix-vue/radix-vue#998]
### Describe the feature

Would it be beneficial to integrate something like [Renovate](https://github.com/apps/renovate) or [Dependabot](https://github.com/dependabot) to help keeping our dependencies up to date?

I can look into integrating one of these if it would be helpful for us.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by DamianGlowala** [comment]
I'd first suggest comparing these two to make a conscious decision (**both Vue and Nuxt are using renovate**):
https://docs.renovatebot.com/bot-comparison/#table-of-features

**Comment by epr3** [comment]
Looks like Renovate has better features, I think I'll try implementing that one then. Thank you @DamianGlowala.

**Comment by epr3** [comment]
Renovate added and working. Closing issue.
